aspect-build/rules_js

- docs/npm_import.md
- js/private/npm_import.bzl
- js/private/pnpm_utils.bzl
> fix: don't instantiate __lc target of package unless there is a lifecycle hook

- example/package.json
- example/pnpm-lock.yaml
- js/private/npm_import.bzl
- js/private/pnpm_utils.bzl
Pre-factored this fix from https://github.com/aspect-build/rules_js/pull/61
> fix: handle non-dict bin entry in package.json

- js/private/link_node_package.bzl
- js/private/npm_import.bzl
There is no way to do lifecycle hooks with circular deps between them without having an entire node_modules tree per package that has a lifecycle hook. This doesn't scale. For the set of packages that have lifecycle hooks, we're going to require a DAG between them.
We may need to add options to break circular deps between packages with lifecycle hooks so you can specify which order they should run in .
> fix: get rid of _lc/node_modules tree and run lifecycle hooks in main node_modules tree

- docs/js_binary.md
- js/private/js_binary.bzl
- js/private/js_binary.sh.tpl
- js/private/test/shellcheck_launcher.sh
Seems that it was broken following #22 in some rewrite
> refactor: make nodejs_binary amenable to custom rules

- example/BUILD.bazel
- js/private/npm_import.bzl
- js/private/test/package_json_checked.bzl
- js/private/test/package_json_with_dashes_checked.bzl
Fixes https://github.com/aspect-build/rules_js/issues/121
> fix: add js_package of npm package to the data of the generated js_binaries for its bins

- js/private/translate_pnpm_lock.bzl
needed so that bzlmod module extension can reuse the logic without loading generated code
> refactor: split npm_import data logic from starlark code generation

- MODULE.bazel
Diverged from `repositories.bzl`.
> fix: bazel-lib version in MODULE.bazel

- e2e/bzlmod/BUILD.bazel
- e2e/bzlmod/MODULE.bazel
- e2e/bzlmod/main.mjs
- npm/extensions.bzl
- npm/npm_import.bzl
- npm/private/npm_import.bzl
I need this for some of the bzlmod e2e additions to the other repos.
> feat: import single packages as bzlmod extension

- MODULE.bazel
- js/repositories.bzl
Update some versions so that our bzlmod e2e tests pass.
> chore: update versions

- WORKSPACE
- docs/npm_import.md
- e2e/npm_link_package/WORKSPACE
- e2e/pnpm_workspace/WORKSPACE
- e2e/pnpm_workspace_dot_dot/.bazelignore
- e2e/pnpm_workspace_dot_dot/WORKSPACE
- npm/private/npm_translate_lock.bzl
- npm/private/test/BUILD.bazel
- npm/private/test/translate_lock_tests.bzl
> feat: check that node_modules folders are in .bazelignore

- examples/npm_deps/BUILD.bazel
> fix: windows test newline error

- js/private/js_binary.sh.tpl
- js/private/node-patches/fs.js
- js/private/node-patches/src/BUILD.bazel
- js/private/node-patches/src/fs.ts
- js/private/node-patches/src/tsconfig.json
- js/private/test/node-patches/BUILD.bazel
- js/private/test/node-patches/escape.js
- js/private/test/node-patches/lstat.js
- js/private/test/node-patches/opendir.js
- js/private/test/node-patches/readdir.js
- js/private/test/node-patches/readlink.js
- js/private/test/node-patches/realpath.js
- js/private/test/node-patches/tsconfig.json
- js/private/test/shellcheck_launcher.sh
> Misc fixes; mostly for Windows issues

- .fasterci/config.yaml
- npm/private/npm_import.bzl
the build is broken here:
https://github.com/aspect-build/rules_js/pull/195/checks?check_run_id=6868676346
> temporary workaround for fasterci 

- npm/private/npm_translate_lock.bzl
For example,
```
public_hoist_packages = {
"ms": ["examples/npm_deps"],
},
```
produces error messaage:
```
ERROR: /Users/greg/aspect/rules/js/rules_js/WORKSPACE:46:19: fetching npm_translate_lock rule //external:npm: Traceback (most recent call last):
File "/private/var/tmp/_bazel_greg/7aed427a991d86f99332ab79b9b11780/external/aspect_rules_js/npm/private/npm_translate_lock.bzl", line 649, column 21, in _impl
fail(msg)
Error in fail: 
Invalid public hoist configuration with multiple packages to hoist to `examples/npm_deps/node_modules/ms`: ["ms@0.7.3", "ms@2.0.0", "ms@2.1.2", "ms@2.1.3"]
Trying selecting a specific version of `ms` to hoist in public_hoist_packages. For example `ms@0.7.3`:
public_hoist_packages = {
"ms@0.7.3": ["examples/npm_deps"]
}
```
and 
```
public_hoist_packages = { …
```
> fix: improve error handling if there are conflicting public hoisted packages

- js/private/js_run_binary.bzl
https://github.com/aspect-build/bazel-lib/pull/175 introduces a fail in the underlying rule this macro wraps,
so we just want to provide another suggestion here.
> chore: add suggestion when js_run_binary has no outs

- npm/private/BUILD.bazel
- npm/private/ini.bzl
- npm/private/test/BUILD.bazel
- npm/private/test/ini_test.bzl
Is this about what we're looking for? A basic skylark method that can be used anywhere... 🤷 
idk if we have a standard for where to put private utils like this?
> util: add basic ini parser

- js/private/js_library.bzl
> fix: remove DefaultInfo.files from js_library

- npm/private/test/yaml_tests.bzl
- npm/private/yaml.bzl
fyi: @arobinson
Addresses https://github.com/aspect-build/rules_js/issues/282.
> feat: parse literal mulitline yaml strings

- npm/private/npm_translate_lock.bzl
A useful pre-factor for https://github.com/aspect-build/rules_js/pull/280
> chore: refactor duplicate code info helper function in npm_translate_lock

- WORKSPACE
- js/private/test/node-patches/BUILD.bazel
- js/private/test/node-patches/spawn.js
- js/private/test/node-patches/spawn_print.js
- js/private/test/node-patches/spawn_which.sh
Closes #236
Currently all pass. Let me know if you can think of more cases or think any of these are unnecessary/overkill.
> test: add node process spawning tests

- js/private/BUILD.bazel
- js/private/js_binary.bzl
- js/private/js_binary.sh.tpl
- js/private/node-patches/register.js
- js/private/node_wrapper.bat
- js/private/node_wrapper.sh
- js/private/test/node-patches/BUILD.bazel
- js/private/test/node-patches/spawn.js
- js/private/test/node-patches/spawn_node_path.js
- js/private/test/node-patches/spawn_node_path.sh
- js/private/test/node-patches/spawn_patch_depth.js
- js/private/test/node-patches/spawn_patch_depth.sh
- js/private/test/node-patches/spawn_print.js
- js/private/test/node-patches/spawn_which.sh
- js/private/test/shellcheck_launcher.sh
Fixes https://github.com/aspect-build/rules_js/issues/311
> fix: apply node fs patched symlink guards in spawned child node processes

- e2e/js_image/README.md
#312 did not quite fix the issue.
> docs: fix squished file tree

- docs/js_binary.md
- js/private/js_binary.bzl
Meant to make this change in #334
> chore: update out-of-date js_library docs

- .github/workflows/bcr/presubmit.yml
Making this template match the one we have in the real bcr.
> chore: update presubmit.yml file for bcr ci

- npm/private/npm_link_package_store.bzl
- npm/private/test/BUILD.bazel
- npm/private/test/bin_test.sh
- npm/private/test/defs_checked.bzl
- npm/private/test/package.json
- npm/private/test/repositories_checked.bzl
- pnpm-lock.yaml
Pre-factor from https://github.com/aspect-build/rules_js/pull/392
> fix: provide runfiles of all transitives from npm_link_package_store

- js/private/node-patches/fs.js
- js/private/node-patches/src/fs.ts
- js/private/test/node-patches/realpath.js
This will be needed to support RBE once https://github.com/bazelbuild/bazel/compare/master...fmeum:bazel:direct-symlink-staging-no-api lands.
It handles the case where a directory symlink is relative within the sandbox but there is a symlink farm within that directory that point outside of the sandbox (since they are real files). When determining the nextHop, if a symlink escapes then we should check its parent directories to see if they are symlinks and can be followed to a non-escaping result.
Without the fix the new test case fails as expected:
```
Executing tests from //js/private/test/node-patches:realpath_test
-----------------------------------------------------------------------------
node:internal/process/promises:246
triggerUncaughtException(err, true /* fromPromise */);
^ …
```
> fix: handle nested symlinks via relative directory symlinks in sandbox

- js/private/node-patches/fs.js
- js/private/node-patches/src/fs.ts
- js/private/test/node-patches/realpath.js
Hit this one working on https://github.com/aspect-build/bazel-examples/pull/9
Test case added to realpath.js that fails without the fix,
```
$ cat /private/var/tmp/_bazel_greg/7aed427a991d86f99332ab79b9b11780/execroot/aspect_rules_js/bazel-out/darwin-fastbuild/testlogs/js/private/test/node-patches/realpath_test/test.log
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
Executing tests from //js/private/test/node-patches:realpath_test
-----------------------------------------------------------------------------
/private/var/tmp/_bazel_greg/7aed427a991d86f99332ab79b9b11780/execroot/aspect_rules_js/bazel-out/darwin-fastbuild/bin/js/private/node-patches/src/fs.js:788
let err = new Error(`ENOENT: no such file or directory, ${s} '${p}'`);
^
Error: ENOENT: no such file or directory, realpath …
```
> fix: fix bug in realpath symlink guards

- e2e/pnpm_workspace/lib/a/package.json
- e2e/pnpm_workspace/pnpm-lock.yaml
- e2e/pnpm_workspace/vendored/b/BUILD.bazel
- e2e/pnpm_workspace/vendored/b/index.js
- e2e/pnpm_workspace/vendored/b/package.json
- npm/private/npm_translate_lock.bzl
- npm/private/transitive_closure.bzl
- Add failing test case
- Fix issue #435
> fix: handle link: dependencies in pnpm-lock.yaml packages

- npm/private/utils.bzl
Testing against bazel HEAD this morning I ran into this failure building rules_js
```
ERROR: /Users/greg/aspect/rules/js/rules_js/BUILD.bazel:10:22: in npm_link_package_store rule //:node_modules/@types/node: 
Traceback (most recent call last):
File "/Users/greg/aspect/rules/js/rules_js/npm/private/npm_link_package_store.bzl", line 94, column 31, in _impl
files = utils.make_symlink(ctx, root_symlink_path, virtual_store_directory)
File "/Users/greg/aspect/rules/js/rules_js/npm/private/utils.bzl", line 106, column 28, in _make_symlink
ctx.actions.symlink(
Error in symlink: symlink() with "target_file" directory param requires that "output" be declared as a directory (did you mean to use declare_directory() instead of declare_file()?)
```
This is due to a BREAKING CHANGE in Bazel that …
> fix: required for to use rules_js with Bazel HEAD without --allow_experimental_unresolved_symlinks

- renovate.json
> fix(deps): fix renovate config requiring packageRules.matchDatasources

- renovate.json
I sure hope this is the last 🙏
> renovate: fix regex syntax error

- MODULE.bazel
- e2e/js_image/WORKSPACE
- js/repositories.bzl
This version is the minimum version for rules_js bzlmod support
> chore: update to @aspect_bazel_lib v1.3.1

- js/private/expand_template.bzl
- js/private/test/expand_template/BUILD.bazel
Related to aspect-build/silo#550.
- Update to `expand_template`.
- Add test that ensures that the `DefaultInfo` is returned.
> fix: update `expand_template` to return `DefaultInfo`

- renovate.json
I really wish these were easier to validate :(
> renovate: fix typo

- js/private/node-patches/fs.js
- js/private/node-patches/src/fs.ts
This reverts commit ca2ba36a719e2f7920fdcb367007a23170020422.
Fixes #577
> Revert "perf: prevent preparing stack traces in fs *Sync patches"

- npm/private/npm_package_store.bzl
Fixes https://github.com/aspect-build/rules_js/issues/497
Looks like during development I fixed the impossible case of a dyadic circular deps in the transitive closure of a lifecycle npm package target but in doing that I disabled all dyadic circular deps. This change allows for dyadic circular deps again in the simple case where there are no lifecycle hooks involved.
> fix: fix virtual store circular deps between npm packages

- .aspect/workflows/config.yaml
Enables Aspect Workflows on rules_js
> build: add Aspect Workflows

- npm/private/npm_translate_lock.bzl
For large lock files with many importers the `_gen_npm_imports` in `npm_translate_lock` can take upwards of 60s with the inner loop of the deeply nested loop:
```
for package, package_info in packages.items():
for import_path, importer in importers.items():
for dep_package, dep_version in dependencies.items():
```
being executed 47M times!
https://bazelbuild.slack.com/archives/CEZUUKQ6P/p1668182891000739?thread_ts=1668127667.932669&cid=CEZUUKQ6P
This resolves the issue by unwinding the deeply nested loop and making a lookup table instead:
```
importer_links = {}
for import_path, importer in importers.items():
for dep_package, dep_version in dependencies.items():
for package, package_info in packages.items():
for import_path, links in importer_links.items():
```
> fix: improve npm_translate_lock perf by unwinding deeply nested loop and using a lookup table instead for importer links

- e2e/bzlmod/.bazeliskrc
- e2e/js_image/.bazeliskrc
- e2e/npm_link_package-esm/.bazeliskrc
- e2e/npm_link_package/.bazeliskrc
- e2e/npm_translate_lock/.bazeliskrc
- e2e/npm_translate_lock_auth/.bazeliskrc
- e2e/npm_translate_package_lock/.bazeliskrc
- e2e/npm_translate_yarn_lock/.bazeliskrc
- e2e/package_json_module/.bazeliskrc
- e2e/pnpm_workspace/.bazeliskrc
- e2e/pnpm_workspace_rerooted/.bazeliskrc
- e2e/rules_foo/.bazeliskrc
- e2e/vendored_node/.bazeliskrc
Except for js_run_devserver which seems to be failing on CI in a way that I can't repro locally. 
https://github.com/aspect-build/rules_js/actions/runs/3463927116/jobs/5784823402
> build: use Aspect CLI in e2e tests

- docs/faq.md
- docs/npm_import.md
- npm/npm_import.bzl
> doc: say how to bootstrap a pnpm lockfile with managed pnpm

- npm/private/test/npm_auth_test.bzl
GH actions auto-merge pulled the trigger early on https://github.com/aspect-build/rules_js/pull/663 🤷
> fix: broken .npmrc _authToken tests

- .bazelversion
- .github/workflows/ci.bazelrc
Testing that fix in https://github.com/bazelbuild/bazel/pull/16812 resolves issue https://github.com/bazelbuild/bazel/issues/16789 seen in Bazel 6.0.0rc1 & rc2
> chore: update to Bazel last_green

- js/private/js_library_helpers.bzl
The subtle difference in this helper between data & deps could use some more detail. Also added links to relevant spots in the Bazel docs that apply to handling runfiles in build rules.
> chore: add more details to docstring of js_library_helpers gather_runfiles helper function

- .github/workflows/ci.yaml
https://aspect-build.slack.com/archives/C03LXS06TA7/p1670518320554809
Verified works as expected here:: https://github.com/aspect-build/rules_js/actions/runs/3651141369
> ci: cancel previous actions from the same PR

- WORKSPACE
- examples/npm_deps/patches/test-a.patch
- examples/npm_deps/patches/test-a@0.0.1.patch
- examples/npm_deps/patches/test-b.patch
- npm/private/npm_translate_lock_generate.bzl
- npm/private/test/repositories_checked.bzl
> feat: support "*" in npm_translate_lock patch_args dict

- e2e/bzlmod/BUILD.bazel
- e2e/bzlmod/MODULE.bazel
- e2e/bzlmod/my.less
- e2e/bzlmod/package.json
- e2e/bzlmod/pnpm-lock.yaml
- npm/private/npm_translate_lock_generate.bzl
> fix(bzlmod): use canonical name for package_json.bzl loads

- npm/private/test/repositories_checked.bzl
> chore: update failing //npm/private/test:write_npm_translate_lock diff test

- .aspect/rules/external_repository_action_cache/npm_translate_lock_LTE4Nzc1MDcwNjU=
- npm/private/test/repositories_checked.bzl
- package.json
- pnpm-lock.yaml
> chore: update devDeps of @kubernetes/client-node needed for prepare lifecycle hook to match the commit hash we're pulling

- .github/workflows/ci.yaml
- e2e/update_pnpm_lock/MODULE.bazel
- e2e/update_pnpm_lock/WORKSPACE.bzlmod
- e2e/update_pnpm_lock/test.sh
- npm/extensions.bzl
In support of https://github.com/aspect-build/rules_js/issues/644
> ci: run e2e/update_pnpm_lock under bzlmod

- .github/workflows/ci.yaml
- e2e/npm_translate_lock_auth/MODULE.bazel
- e2e/npm_translate_lock_auth/WORKSPACE.bzlmod
- npm/extensions.bzl
- npm/private/npm_translate_lock_generate.bzl
> feat: support npm auth under bzlmod

- .github/workflows/ci.yaml
- e2e/package_json_module/MODULE.bazel
- e2e/package_json_module/WORKSPACE.bzlmod
> chore: run e2e/package_json_module under bzlmod

- .github/workflows/ci.yaml
- e2e/npm_translate_package_lock/MODULE.bazel
- e2e/npm_translate_package_lock/WORKSPACE.bzlmod
- e2e/npm_translate_yarn_lock/MODULE.bazel
- e2e/npm_translate_yarn_lock/WORKSPACE.bzlmod
- npm/extensions.bzl
> feat: support npm_package_lock and preupdate in bzlmod

- .github/workflows/ci.yaml
- e2e/pnpm_workspace/MODULE.bazel
- e2e/pnpm_workspace/WORKSPACE.bzlmod
- e2e/pnpm_workspace_rerooted/MODULE.bazel
- e2e/pnpm_workspace_rerooted/WORKSPACE.bzlmod
- npm/extensions.bzl
- npm/npm_import.bzl
> feat: support bins attr in bzlmod

- e2e/verify_patches/MODULE.bazel
- e2e/verify_patches/WORKSPACE
- e2e/verify_patches/test.sh
- npm/private/npm_translate_lock_helpers.bzl
> fix: fix a bug where patch extensions weren't correctly verified

- npm/private/npm_translate_lock_state.bzl
This is a pre-factor for https://github.com/aspect-build/rules_js/pull/815. Usage and test coverage for this fix will be in that PR.
> fix: handle binary files in data attribute of npm_translate_lock

- npm/private/npmrc.bzl
- npm/private/test/npmrc_test.bzl
> fix: support single quotes in npmrc properties

- .github/workflows/ci.yaml
- e2e/js_run_devserver/MODULE.bazel
- e2e/js_run_devserver/WORKSPACE.bzlmod
- e2e/js_run_devserver/multirun_test.sh
- e2e/js_run_devserver/serve_test.sh
- e2e/js_run_devserver/test.sh
> chore: run e2e/js_run_devserver under bzlmod

- e2e/update_pnpm_lock_with_import/test.sh
- e2e/verify_patches/test.sh
Revert the two broken files and just suppress the shellchecks for now
> chore: fix main after PR landed on red

- .aspect/cli/plugins.yaml
- .aspect/workflows/config.yaml
- .bazeliskrc
- BUILD.bazel
- WORKSPACE
- js/dev_repositories.bzl
Can't turn on gazelle quite yet as the bzl_library targets are out-of-date and not sure if gazelle is generating the right things there yet
> chore: update to latest version of Aspect CLI and turn on additional workflows features

- .github/workflows/ci.yaml
- e2e/webpack_devserver/MODULE.bazel
- e2e/webpack_devserver/WORKSPACE.bzlmod
- e2e/webpack_devserver/serve_test.sh
- e2e/webpack_devserver/test.sh
- e2e/webpack_devserver_esm/MODULE.bazel
- e2e/webpack_devserver_esm/WORKSPACE.bzlmod
- e2e/webpack_devserver_esm/serve_test.sh
- e2e/webpack_devserver_esm/test.sh
Related to https://github.com/aspect-build/rules_js/issues/644
> chore: run webpack e2es under bzlmod

- npm/extensions.bzl
Related to https://github.com/aspect-build/rules_js/issues/644
> feat: add remaining missing attributes to bzlmod api

- BUILD.bazel
- e2e/pnpm_workspace/MODULE.bazel
- e2e/pnpm_workspace/app/a/BUILD.bazel
- npm/private/npm_translate_lock_generate.bzl
Resolves https://github.com/aspect-build/rules_js/issues/933
> feat: generated npm_link_targets() macro that lists links generated by npm_link_all_packages()

- npm/private/npm_translate_lock_generate.bzl
Tested in https://github.com/aspect-build/rules_swc/actions/runs/4469546895/jobs/7851817497
> fix(windows): make bazelignore logic tolerate CRLF

- e2e/npm_translate_yarn_lock/.aspect/rules/external_repository_action_cache/npm_translate_lock_LTE4Nzc1MDcwNjU=
- e2e/npm_translate_yarn_lock/pnpm-lock.yaml
- e2e/npm_translate_yarn_lock/yarn.lock
Resolves https://github.com/aspect-build/rules_js/security/dependabot/15
> chore: re-pin e2e/npm_translate_yarn_lock lock file to resolve dependabot alert

- e2e/npm_translate_package_lock/.aspect/rules/external_repository_action_cache/npm_translate_lock_LTE4Nzc1MDcwNjU=
- e2e/npm_translate_package_lock/package-lock.json
- e2e/npm_translate_package_lock/pnpm-lock.yaml
Resolves https://github.com/aspect-build/rules_js/security/dependabot/20, https://github.com/aspect-build/rules_js/security/dependabot/1 && https://github.com/aspect-build/rules_js/security/dependabot/14
> chore: re-pin e2e/npm_translate_package_lock lock file to resolve dependabot alert

- js/private/coverage/coverage.sh.tpl
Please include a summary of the changes and the related issue (if any). Please also include relevant motivation and context.
Fixes # (issue)
How has this been tested?
If part of the test plan included manual testing, please provide instructions so we can reproduce. Please also list any relevant details for your test configuration.
> fix(coverage): set runfiles directory correctly

- docs/js_image_layer.md
- js/private/js_image_layer.bzl
Please include a summary of the changes and the related issue (if any). Please also include relevant motivation and context.
Fixes #921
How has this been tested?
If part of the test plan included manual testing, please provide instructions so we can reproduce. Please also list any relevant details for your test configuration.
> docs: clarify workdir and cmd attributes

- npm/private/test/yaml_tests.bzl
- npm/private/yaml.bzl
> fix: support pnpm lockfile v6 use of yaml complex mapping keys

- npm/private/npm_translate_lock_state.bzl
Using `rctx.download` with a `file:` URL as a trick to copy binary files from the source tree to the external repository has been reported to cause issues https://bazelbuild.slack.com/archives/CEZUUKQ6P/p1674797114540009?thread_ts=1674795430.508959&cid=CEZUUKQ6P as well as warnings:
```
cache-bazel-remote-7696dc456-cnfc7 bazel-remote 2023/04/23 12:57:25 unsupported URI: file:/runner/builds/3CxP_XNN/0/js/pnpm-lock.yaml
cache-bazel-remote-7696dc456-cnfc7 bazel-remote 2023/04/23 12:57:25 unsupported URI: file:/runner/builds/3CxP_XNN/0/js/yarn.lock
cache-bazel-remote-7696dc456-cnfc7 bazel-remote 2023/04/23 12:57:25 unsupported URI: file:/runner/builds/3CxP_XNN/0/js/package.json
cache-bazel-remote-7696dc456-cnfc7 bazel-remote 2023/04/23 12:57:25 unsupported URI: …
```
> fix: don't use rctx.download file: URL trick to copy binary files in npm_tarnslate_lock

- npm/private/npm_translate_lock_state.bzl
When `update_pnpm_lock` is `False` then we can read the list of packages from the lock file since that won't break the update pnpm lock workflow when it is not enabled. This means that there is no phantom read of an undeclared package.json file for users in this case.
Fixes https://github.com/aspect-build/rules_js/issues/910.
Also related to Bazel Slack conversation: https://bazelbuild.slack.com/archives/CEZUUKQ6P/p1682614797831909
> fix: read list of pnpm patches from lock file when update_pnpm_lock is False

- e2e/js_run_devserver/multirun_test.sh
- e2e/js_run_devserver/serve_test.sh
- e2e/js_run_devserver/src/BUILD.bazel
- e2e/js_run_devserver/src/naughty.js
- e2e/js_run_devserver/src/simple.js
- e2e/js_run_devserver/test.sh
Ref https://github.com/aspect-build/rules_js/issues/1025
> test: use unique port for js_run_devserver multirun_test

- .bazeliskrc
- e2e/npm_translate_lock_subdir_patch/.bazeliskrc
> chore: update to Aspect CLI 5.3.4

- js/private/js_binary.bzl
- js/private/test/fixed_args/BUILD.bazel
- js/private/test/fixed_args/test.txt
> feat: support location expansion in fixed_args

- .github/workflows/buildifier.yaml
- .pre-commit-config.yaml
- CONTRIBUTING.md
- MODULE.bazel
- e2e/bzlmod/MODULE.bazel
- e2e/git_dep_metadata/MODULE.bazel
- e2e/gyp_no_install_script/MODULE.bazel
- e2e/js_run_devserver/MODULE.bazel
- e2e/npm_translate_lock/MODULE.bazel
- e2e/npm_translate_lock_auth/MODULE.bazel
- e2e/npm_translate_lock_empty/MODULE.bazel
- e2e/npm_translate_lock_subdir_patch/MODULE.bazel
- e2e/npm_translate_package_lock/MODULE.bazel
- e2e/npm_translate_yarn_lock/MODULE.bazel
- e2e/package_json_module/MODULE.bazel
- e2e/patch_from_repo/MODULE.bazel
- e2e/pnpm_workspace/MODULE.bazel
- e2e/pnpm_workspace_deps/MODULE.bazel
- e2e/pnpm_workspace_rerooted/MODULE.bazel
- e2e/update_pnpm_lock/MODULE.bazel
- e2e/update_pnpm_lock_with_import/MODULE.bazel
- e2e/verify_patches/MODULE.bazel
- e2e/webpack_devserver/MODULE.bazel
- e2e/webpack_devserver_esm/MODULE.bazel
- e2e/worker/MODULE.bazel
- npm/private/npm_translate_lock.bzl
- npm/private/test/generated_pkg_json_test.bzl
Are we in favour of doing this to all the repos?
---
> ci: enable buildifier check on ci

- .github/workflows/ci.yaml
Excluding e2e and rbe for now to reduce the number of jobs to just some essentials.
---
> ci: enable testing on bazel 7

- .aspect/rules/external_repository_action_cache/npm_translate_lock_LTE4Nzc1MDcwNjU=
- e2e/pnpm_workspace_deps/.aspect/rules/external_repository_action_cache/npm_translate_lock_LTE4Nzc1MDcwNjU=
- e2e/pnpm_workspace_deps/.bazelignore
- e2e/pnpm_workspace_deps/MODULE.bazel
- e2e/pnpm_workspace_deps/WORKSPACE
- e2e/pnpm_workspace_deps/lib-dupes/BUILD.bazel
- e2e/pnpm_workspace_deps/lib-dupes/index.js
- e2e/pnpm_workspace_deps/lib-dupes/package.json
- e2e/pnpm_workspace_deps/pnpm-lock.yaml
- e2e/pnpm_workspace_deps/pnpm-workspace.yaml
- e2e/pnpm_workspace_deps/tests/BUILD.bazel
- e2e/pnpm_workspace_deps/tests/package.json
- e2e/pnpm_workspace_deps/tests/test_pkg_dupe_deps_linked.js
- npm/private/npm_package_store.bzl
- npm/private/test/BUILD.bazel
- npm/private/test/npm_package/BUILD.bazel
- npm/private/test/npm_package/index.js
- npm/private/test/npm_package/package.json
- npm/private/test/package.json
- npm/private/test/repositories_checked.bzl
- package.json
- pnpm-lock.yaml
No fix yet but the e2e test reproduces it, note that the unit test does not reproduce it so it might have something to do with references between workspaces?
---
> fix: multiple versions of a package using aliases in pnpm workspaces crashes

- docs/pnpm.md
- e2e/update_pnpm_lock/test.sh
- npm/private/npm_translate_lock_state.bzl
Feature request from one of our Bazel OSS Support customers.
---
> feat: add support for disabling update_pnpm_lock feature via ASPECT_RULES_JS_DISABLE_UPDATE_PNPM_LOCK environment variable

- docs/pnpm.md
Documentation correctness.
N/A
> Fix starlark patching example syntax

- js/private/js_run_devserver.mjs
We recently upgraded `rules_js` from `v1.25.4` to `v1.30.0` and discovered a regression introduced by #1043 in `v1.26.0` that impacts `js_run_devserver`. That PR introduces a custom function `fileExists` to leverage `fs.promises.access` as an alternative to the deprecated `fs.exists` (see [comment](https://github.com/aspect-build/rules_js/blob/d565889912e97a4eba9d0d059263f1c22ba2f452/js/private/js_run_devserver.mjs#L16-L17) and [review thread](https://github.com/aspect-build/rules_js/pull/1043#discussion_r1187955118)).
But the implementation of `fileExists` is missing a return statement, resulting in the two callsites to interpret `undefined` as a signal that the given file does not exist.
While it is tempting to add a return statement, this PR proposes the removal of `fileExists` in …
> `js_run_devserver` should use `existsSync` instead of a custom `fileExists`

- renovate.json
> chore(renovate): reduce the volume of changes by excluding e2e/ folders

- docs/js_run_devserver.md
- js/private/js_run_devserver.bzl
> fix: documentation typos

- npm/BUILD.bazel
- Bug fix. Fixes #1197
- No additional suggested release notes (other than PR title in release list).
- No direct testing.
- Solution taken from workaround tested in private repository.
> fix: declare dependency on @bazel_features in //npm:repositories

- docs/README.md
> chore(docs): mention configure exists now

- docs/README.md
- docs/faq.md
- docs/pnpm.md
- docs/troubleshooting.md
> Add module not found troubleshooting guide

- js/dev_repositories.bzl
> build: upgrade buildifier_prebuilt to 6.3.3

- js/private/js_run_devserver.mjs
Fixes https://github.com/aspect-build/rules_js/issues/1242
- Suggested release notes are provided below: 
The child process of `js_run_devserver` can now consume `stdin` without preventing `js_run_devserver` from syncing upon ibazel's notifications
I'm only alerting the child process of ibazel success after the files have been synced in order to allow the child process to pick up the latest files in the `js_run_devserver` sandbox. This should not be a breaking change because `js_run_devserver` simply doesn't respond to ibazel's success messages currently when the child process adds a 'data' event handler on `process.stdin`.
Have been trying to …
> Fix for js_run_devserver to sync file changes if child process consumes stdin

- .aspect/workflows/terraform/workflows.tf
Also bump remote cache load balancer replicas to 2.
> chore: bump GKE machine type to e2-standard-2

- .aspect/workflows/terraform/workflows.tf
> chore: update to latest version of Aspect Workflows starter image

- js/private/js_helpers.bzl
Update `gather_transitive_declarations` docstring to reflect the actual function body.
> Update gather_transitive_declarations docstring

- .github/workflows/ci.yaml
- e2e/npm_translate_lock_auth/test.sh
- npm/extensions.bzl
This attribute from WORKSPACE was missed when we wrote the bzlmod extension
> fix: support use_home_npmrc with bzlmod

- .github/workflows/release_prep.sh
> chore: clarify bazel-lib 2.x compatibility

- docs/README.md
- docs/troubleshooting.md
> docs: add section with troubleshooting performance tips

- .aspect/workflows/config.yaml
- .pre-commit-config.yaml
- BUILD.bazel
- WORKSPACE
- js/dev_repositories.bzl
- tools/BUILD.bazel
The format task is new in Aspect Workflows 5.9
> chore: bring in aspect_rules_lint and add format task to Aspect Workflows

- .aspect/workflows/config.yaml
- .aspect/workflows/terraform/workflows.tf
Same as https://github.com/aspect-build/rules_jasmine/pull/102
> chore: run Aspect Workflows setup step on small instances

- npm/private/npm_translate_lock_generate.bzl
- npm/private/transitive_closure.bzl
> refactor: transitive_closure.bzl comments

- .aspect/workflows/config.yaml
- .aspect/workflows/terraform/workflows.tf
- docs/BUILD.bazel
- docs/delivery.sh
Tested here https://buildkite.com/aspect-build/rules-js/builds/1179
> chore: enable workflows delivery on demostration target

- .aspect/workflows/terraform/workflows.tf
Some copy-pasta from rules_jasmine GHA deployment snuck in here
> chore: cleanup terraform

- .aspect/cli/config.yaml
- .aspect/workflows/bazelrc
- .aspect/workflows/config.yaml
- .aspect/workflows/terraform/workflows.tf
- .bazeliskrc
- .bazelversion
> chore: upgrade to Aspect Workflows 5.9.0-rc.9

- .github/workflows/ci.bazel5.bazelrc
- .github/workflows/ci.bazelrc
- .github/workflows/ci.yaml
- .github/workflows/release.yml
- js/private/test/BUILD.bazel
Spent a lot of time on an improved ci.yml pattern for our rules sets. After this lands I'll roll it out to all our other rule sets repositories and also upstream a variation of it to https://github.com/bazel-contrib/.github/tree/master/.github/workflows.
Same as https://github.com/aspect-build/rules_esbuild/pull/180.
> chore: update GHA ci.yml with improved matrix pattern

- npm/private/npm_import.bzl
> refactor: remove dependency on internal /pkg npm target

- npm/private/npm_import.bzl
- npm/private/npm_translate_lock_generate.bzl
- npm/private/test/utils_tests.bzl
- npm/private/transitive_closure.bzl
- npm/private/utils.bzl
> refactor: simplify pnpm parse_pnpm_name util

- docs/pnpm.md
- Relevant documentation has been updated
> docs: add note about npm_translate_lock_<hash> merge conflict resolution

- npm/private/npm_import.bzl
- npm/private/npm_translate_lock_state.bzl
Pre-factor out of https://github.com/aspect-build/rules_js/pull/1458.
---
> chore: improve error messages on rctx.execute calls

- .bazelversion
- .github/workflows/ci.yaml
plus bump bazel 6 CI coverage to 6.5.0
> chore: upgrade to Bazel 7.0.2

- .aspect/workflows/config.yaml
Disables rebase on Buildkite CI.
> chore: disable rebase on Buildkite Workflows

- js/private/js_image_layer.bzl
This makes it possible to apply modify_execution_info
- Add missing feature
> fix: Add mnemonic to JsImageLayer

- npm/private/npm_import.bzl
- npm/private/npm_translate_lock_generate.bzl
- npm/private/test/utils_tests.bzl
- npm/private/utils.bzl
Random "cleanup" while looking into dropping bazel5.
---
> refactor: reduce duplicate npm_import logic

- examples/js_binary/custom_rule.bzl
- js/private/test/create_launcher/custom_test.bzl
- npm/extensions.bzl
- npm/private/npm_import.bzl
> refactor: improve rule internal implementation method names

- npm/private/transitive_closure.bzl
When manually testing by counting the number of iterations in the "infinite" loop the count is often significantly reduced, although will always depend on the iteration order. For example, `@angular/core` coming before `@angular/material` (which depends on `core`) will result in a cache hit while the opposite order will not due to the the cache persisting being outside the "infinite" loop method.
- Performance (a code change that improves performance)
> perf: cache transitive_closure computations

- npm/private/npm_import.bzl
- npm/private/test/chalk_links_defs_checked.bzl
- npm/private/test/fsevents_links_defs_checked.bzl
- npm/private/test/rollup_links_defs_checked.bzl
- npm/private/test/unused_links_defs_checked.bzl
It's already inlined in most places.
---
> refactor: inline utils.package_directory_output_group in npm_import repo rules

- .aspect/rules/external_repository_action_cache/npm_translate_lock_LTE4Nzc1MDcwNjU=
- .bazelignore
- examples/linked_empty_node_modules/BUILD.bazel
- examples/linked_empty_node_modules/index.js
- examples/linked_empty_node_modules/package.json
- npm/private/test/npm_defs_checked.bzl
- pnpm-lock.yaml
- pnpm-workspace.yaml
Close https://github.com/aspect-build/rules_js/issues/918
> test: add test of empty node_modules target

- e2e/gyp_no_install_script/test/segfault-handler_defs.bzl.checked
- npm/private/npm_import.bzl
- npm/private/npm_translate_lock_generate.bzl
- npm/private/test/fsevents_links_defs_checked.bzl
- npm/private/test/rollup_links_defs_checked.bzl
- npm/private/test/unused_links_defs_checked.bzl
Started working on the tar extraction as action improvement and hit this pre-factor first.
---
- Refactor
> refactor: remove duplicate npm_package_internal from npm_import

- renovate.json
I'm not sure if we also need the lockfile there but this is a start and needed even if we do move the lockfile.
---
> chore: do not run renovate on examples

- MODULE.bazel
- e2e/bzlmod/MODULE.bazel
- e2e/js_image_docker/WORKSPACE
- e2e/js_run_devserver/MODULE.bazel
- e2e/js_run_devserver/WORKSPACE
- e2e/npm_translate_lock/MODULE.bazel
- e2e/npm_translate_lock_auth/MODULE.bazel
- e2e/npm_translate_lock_empty/MODULE.bazel
- e2e/npm_translate_lock_git+ssh/MODULE.bazel
- e2e/npm_translate_lock_multi/MODULE.bazel
- e2e/npm_translate_lock_partial_clone/MODULE.bazel
- e2e/npm_translate_package_lock/MODULE.bazel
- e2e/npm_translate_yarn_lock/MODULE.bazel
- e2e/patch_from_repo/MODULE.bazel
- e2e/pnpm_workspace/MODULE.bazel
- e2e/update_pnpm_lock/MODULE.bazel
- e2e/update_pnpm_lock_with_import/MODULE.bazel
- e2e/vendored_tarfile/MODULE.bazel
- e2e/verify_patches/MODULE.bazel
- e2e/webpack_devserver/MODULE.bazel
- e2e/webpack_devserver/WORKSPACE
- e2e/webpack_devserver_esm/MODULE.bazel
- e2e/webpack_devserver_esm/WORKSPACE
- js/dev_repositories.bzl
> chore: upgrade bazel rulesets

- .aspect/workflows/config.yaml
- .github/workflows/ci.yaml
- e2e/gyp_no_install_script/MODULE.bazel
- e2e/gyp_no_install_script/WORKSPACE
- e2e/gyp_no_install_script/snapshots/bzlmod/segfault-handler_defs.bzl
- e2e/patch_from_repo/MODULE.bazel
> chore: run all e2e tests on CI

- e2e/git_dep_metadata/WORKSPACE.bzlmod
- e2e/pnpm_repo_install/MODULE.bazel
- e2e/pnpm_repo_install/WORKSPACE.bzlmod
- e2e/worker/MODULE.bazel
- e2e/worker/WORKSPACE.bzlmod
> test: separate e2e bzlmod vs workspace repository rules

- npm/extensions.bzl
> refactor: simplify bzlmod tag implementations

- npm/private/npm_translate_lock_generate.bzl
To reduce the diff on related changes in 2.x
> refactor: move npm_import repository rule template into util method

- npm/private/npm_translate_lock_generate.bzl
- npm/private/test/snapshots/bzlmod/npm_defs.bzl
- npm/private/test/snapshots/wksp/npm_defs.bzl
- Performance (a code change that improves performance)
> perf: construct single list of linked packages

- examples/npm_deps/BUILD.bazel
- npm/private/npm_import.bzl
- npm/private/npm_package_store.bzl
Pre-factor from https://github.com/aspect-build/rules_js/pull/1649
> chore: improve comments in npm rules

- npm/private/utils.bzl
> refactor: remove unreachable code

- e2e/pnpm_lockfiles/.bazelignore
- e2e/pnpm_lockfiles/.npmrc
- e2e/pnpm_lockfiles/MODULE.bazel
- e2e/pnpm_lockfiles/WORKSPACE
- e2e/pnpm_lockfiles/package.json
- e2e/pnpm_lockfiles/pnpm-workspace.yaml
- e2e/pnpm_lockfiles/projects/a/package.json
- e2e/pnpm_lockfiles/projects/b/package.json
- e2e/pnpm_lockfiles/projects/c/package.json
- e2e/pnpm_lockfiles/v53/pnpm-lock.yaml
- e2e/pnpm_lockfiles/v54/pnpm-lock.yaml
- e2e/pnpm_lockfiles/v60/pnpm-lock.yaml
- e2e/pnpm_lockfiles/v61/pnpm-lock.yaml
Just to add more test cases where lockfile versions differ.
> test: add link,workspace,custom registry cases to lockfile tests

- e2e/git_dep_metadata/WORKSPACE
- e2e/gyp_no_install_script/WORKSPACE
- e2e/js_run_devserver/WORKSPACE
- e2e/npm_translate_lock/WORKSPACE
- e2e/npm_translate_lock_auth/WORKSPACE
- e2e/npm_translate_lock_empty/WORKSPACE
- e2e/npm_translate_lock_git+ssh/WORKSPACE
- e2e/npm_translate_lock_multi/WORKSPACE
- e2e/npm_translate_lock_partial_clone/WORKSPACE
- e2e/npm_translate_lock_subdir_patch/WORKSPACE
- e2e/npm_translate_package_lock/WORKSPACE
- e2e/npm_translate_yarn_lock/WORKSPACE
- e2e/package_json_module/WORKSPACE
- e2e/patch_from_repo/WORKSPACE
- e2e/pnpm_lockfiles/WORKSPACE
- e2e/pnpm_repo_install/WORKSPACE
- e2e/pnpm_workspace/WORKSPACE
- e2e/pnpm_workspace_deps/WORKSPACE
- e2e/stamped_package_json/WORKSPACE
- e2e/update_pnpm_lock/WORKSPACE
- e2e/update_pnpm_lock_with_import/WORKSPACE
- e2e/vendored_tarfile/WORKSPACE
- e2e/verify_patches/WORKSPACE
- e2e/webpack_devserver/WORKSPACE
- e2e/webpack_devserver_esm/WORKSPACE
For consistency and clarity that that is how you set the node_version now
> chore: be explicit about node_version in all places we register rules_js_register_toolchains

- .aspect/workflows/bazelrc
- .aspect/workflows/config.yaml
For demonstration purposes.
Related to https://aspect-build.slack.com/archives/C04BWU1519D/p1713802211634389.
> chore: generate and save binary BEP on Workflows

- e2e/pnpm_lockfiles/package.json
- e2e/pnpm_lockfiles/v53/pnpm-lock.yaml
- e2e/pnpm_lockfiles/v54/pnpm-lock.yaml
- e2e/pnpm_lockfiles/v60/pnpm-lock.yaml
- e2e/pnpm_lockfiles/v61/pnpm-lock.yaml
Just to see the variations in lockfiles which should have no effect.
> test: add different pnpm specifier types

- .github/workflows/ci.yaml
> chore: fixup typos in gha ci yaml

- MODULE.bazel
Fixes https://github.com/aspect-build/rules_js/issues/1599.
> fix: make rules_lint a dev dependency

- npm/private/npm_translate_lock_state.bzl
This just makes it more like the other fields that are initialized once and have a getter. This will be helpful when loading other `pnpm.*` properties from the root package.json.
---
> refactor: access root_package_json via getter

- .github/workflows/ci.yaml
- e2e/js_image_oci/.bazelrc
- e2e/js_image_oci/MODULE.bazel
- e2e/js_image_oci/WORKSPACE.bzlmod
- e2e/js_image_oci/src/BUILD.bazel
- e2e/js_image_oci/src/main.js
Repro for https://github.com/aspect-build/rules_js/issues/1530
> chore: add bzlmod to js_image_oci e2e

- npm/private/npm_translate_lock_generate.bzl
In 2.x this is not generated at all with bzlmod, this makes the `if bzlmod:` cleaner in 2.x.
This may be required for #1563 as well as pnpm v9.
---
> refactor: extract repositories.bzl generation

- npm/private/test/parse_pnpm_lock_tests.bzl
- npm/private/test/utils_tests.bzl
- npm/private/transitive_closure.bzl
- npm/private/utils.bzl
Minor comments + cleanup done while looking into pnpm v9
---
> refactor: pnpm repository rule cleanup and comments

- npm/private/npm_translate_lock_generate.bzl
- npm/private/npm_translate_lock_helpers.bzl
> refactor: inline check_for_conflicting_public_links

- npm/private/npm_translate_lock_generate.bzl
> fix: error message .format generated with missing argument

- e2e/pnpm_lockfiles/.bazelignore
- e2e/pnpm_lockfiles/README.md
- e2e/pnpm_lockfiles/base/package.json
- e2e/pnpm_lockfiles/lockfile-test.bzl
- e2e/pnpm_lockfiles/projects/a/BUILD.bazel
- e2e/pnpm_lockfiles/projects/b/BUILD.bazel
- e2e/pnpm_lockfiles/projects/c/BUILD.bazel
- e2e/pnpm_lockfiles/projects/d/BUILD.bazel
- e2e/pnpm_lockfiles/projects/d/package.json
- e2e/pnpm_lockfiles/v54/pnpm-lock.yaml
- e2e/pnpm_lockfiles/v60/pnpm-lock.yaml
- e2e/pnpm_lockfiles/v61/pnpm-lock.yaml
- e2e/pnpm_lockfiles/v90/pnpm-lock.yaml
- npm/extensions.bzl
Various edge cases I'm running into
---
> test: add more pnpm_lockfiles test cases

- MODULE.bazel
- e2e/bzlmod/MODULE.bazel
- e2e/gyp_no_install_script/MODULE.bazel
- e2e/js_image_oci/MODULE.bazel
- e2e/js_run_devserver/MODULE.bazel
- e2e/npm_translate_lock/MODULE.bazel
- e2e/npm_translate_lock_empty/MODULE.bazel
- e2e/pnpm_lockfiles/MODULE.bazel
- e2e/pnpm_workspace/MODULE.bazel
- e2e/repo_mapping/MODULE.bazel
- e2e/stamped_package_json/MODULE.bazel
- e2e/webpack_devserver/MODULE.bazel
- e2e/webpack_devserver_esm/MODULE.bazel
- e2e/worker/MODULE.bazel
- js/repositories.bzl
bazel-lib 2.7.3 has a bad URL in coreutils for darwin x86
> chore: bump miminum dep to aspect_bazel_lib 2.7.6

- npm/private/npm_translate_lock_helpers.bzl
- npm/private/test/utils_tests.bzl
- npm/private/transitive_closure.bzl
- npm/private/utils.bzl
> refactor: simplify handling of #423, package aliases

- e2e/pnpm_lockfiles/README.md
- e2e/pnpm_lockfiles/lockfile-test.bzl
- e2e/pnpm_lockfiles/v54/pnpm-lock.yaml
- e2e/pnpm_lockfiles/v60/pnpm-lock.yaml
- e2e/pnpm_lockfiles/v61/pnpm-lock.yaml
Add a few test cases, uncomment some that have been fixed recently.
---
> test: add lockfile test cases

- e2e/pnpm_lockfiles/.bazelignore
- e2e/pnpm_lockfiles/base/package.json
- e2e/pnpm_lockfiles/base/pnpm-workspace.yaml
- e2e/pnpm_lockfiles/lockfile-test.bzl
- e2e/pnpm_lockfiles/v54/pnpm-lock.yaml
- e2e/pnpm_lockfiles/v54/snapshots/defs.bzl
- e2e/pnpm_lockfiles/v60/pnpm-lock.yaml
- e2e/pnpm_lockfiles/v60/snapshots/defs.bzl
- e2e/pnpm_lockfiles/v61/pnpm-lock.yaml
- e2e/pnpm_lockfiles/v61/snapshots/defs.bzl
- e2e/pnpm_lockfiles/v90/pnpm-lock.yaml
- e2e/pnpm_lockfiles/v90/snapshots/defs.bzl
- e2e/pnpm_lockfiles/vendored/is-number/BUILD.bazel
- e2e/pnpm_lockfiles/vendored/is-number/index.js
- e2e/pnpm_lockfiles/vendored/is-number/package.json
- npm/private/utils.bzl
Ref https://github.com/aspect-build/rules_js/issues/1753
---
> fix(pnpm): support pnpm9 URL, github version package versions

- e2e/pnpm_lockfiles/MODULE.bazel
- e2e/pnpm_lockfiles/WORKSPACE
- e2e/pnpm_lockfiles/cases/BUILD.bazel
- e2e/pnpm_lockfiles/cases/override-with-alias-url-v9.yaml
- e2e/pnpm_lockfiles/cases/package.json
- e2e/pnpm_lockfiles/projects/d/package.json
A test case from https://github.com/lodash/lodash/issues/5809#issuecomment-1910560681 that a client had. This was fixed in https://github.com/aspect-build/rules_js/commit/1574619720716abcda9303cdc0f8d8d05e7e1182 but I think individual test cases like this are good to keep around, tiny lockfiles that we will never change to test individual cases...
---
> test: add test cases for individual pnpm lockfile issues

- js/private/js_helpers.bzl
- npm/private/npm_package.bzl
- npm/private/npm_package_store.bzl
> perf: avoid large temp arrays, use single loop

- npm/private/utils.bzl
This is a pretty tiny speedup but it also seems cleaner so might as well take it
---
> perf: use string.elems for char iteration

- js/private/js_helpers.bzl
- npm/private/npm_package.bzl
Mainly just to be consistent 🤷 
---
> refactor: remove optional empty depset direct

- npm/private/npm_import.bzl
- npm/private/npm_translate_lock_generate.bzl
> perf: remove unused template vars

- npm/private/pnpm.bzl
> perf: reduce string concatenation in lockfile parsing

- js/private/dev_deps.bzl
- js/repositories.bzl
This reverts commit 6d341688be0997aec7c556858410500bb3dec050.
---
> Revert "chore(deps): update bazel (#1633)"

- npm/private/utils.bzl
> perf: reduce use of starlark .split

- npm/private/npm_translate_lock_generate.bzl
> refactor(npm): change string template var from overused "name" to "pkg"

- e2e/gyp_no_install_script/snapshots/bzlmod/segfault-handler_defs.bzl
- e2e/gyp_no_install_script/snapshots/wksp/segfault-handler_defs.bzl
- e2e/pnpm_lockfiles/v54/snapshots/defs.bzl
- e2e/pnpm_lockfiles/v54/snapshots/rollup_links_defs.bzl
- e2e/pnpm_lockfiles/v60/snapshots/defs.bzl
- e2e/pnpm_lockfiles/v60/snapshots/rollup_links_defs.bzl
- e2e/pnpm_lockfiles/v61/snapshots/defs.bzl
- e2e/pnpm_lockfiles/v61/snapshots/rollup_links_defs.bzl
- e2e/pnpm_lockfiles/v90/snapshots/defs.bzl
- e2e/pnpm_lockfiles/v90/snapshots/rollup_links_defs.bzl
- npm/private/npm_import.bzl
- npm/private/npm_link_package.bzl
- npm/private/npm_translate_lock_generate.bzl
- npm/private/test/snapshots/bzlmod/chalk_links_defs.bzl
- npm/private/test/snapshots/bzlmod/fsevents_links_defs.bzl
- npm/private/test/snapshots/bzlmod/npm_defs.bzl
- npm/private/test/snapshots/bzlmod/rollup_links_defs.bzl
- npm/private/test/snapshots/bzlmod/unused_links_defs.bzl
- npm/private/test/snapshots/wksp/chalk_links_defs.bzl
- npm/private/test/snapshots/wksp/fsevents_links_defs.bzl
- npm/private/test/snapshots/wksp/npm_defs.bzl
- npm/private/test/snapshots/wksp/rollup_links_defs.bzl
- npm/private/test/snapshots/wksp/unused_links_defs.bzl
> perf(npm): reduce package_name() calls

- docs/README.md
> docs(npm): document support for pnpm9

- docs/js_binary.md
- js/private/js_binary.bzl
> docs: add note about js_binary shell script

- npm/private/npm_translate_lock_helpers.bzl
> refactor(npm): improve pnpm.onlyBuiltDependencies error message

- npm/private/npm_package.bzl
- npm/private/test/npm_package/BUILD.bazel
> fix(npm): respect npm_package include_transitive_sources attribute

- docs/pnpm.md
Close https://github.com/aspect-build/rules_js/issues/1915
> docs(pnpm): add note about pnpm vs bazel patching

- .bcr/presubmit.yml
- e2e/bzlmod/MODULE.bazel
Windows Bazel users are real and will be a major market segment
> chore: restore windows testing

- .github/workflows/ci.yaml
Rolls out https://github.com/bazel-contrib/rules-template/pull/124
> chore: adopt conclusion job for stable status check

- .aspect/workflows/bazelrc
- .aspect/workflows/config.yaml
- .github/workflows/ci.bazelrc
- .github/workflows/ci.yaml
Broken by https://github.com/aspect-build/rules_js/pull/1909
> ci: fix matrix job on GitHub Actions

- js/private/js_helpers.bzl
- npm/private/npm_translate_lock_generate.bzl
- npm/private/pnpm.bzl
- npm/private/pnpm_extension.bzl
- npm/private/utils.bzl
> perf(npm): reduce use of .keys() for has-entry check

- docs/README.md
Small PR - fixes the `troubleshooting.md` reference in `docs/README.md`.
> docs: update troubleshooting reference

- js/private/js_run_devserver.mjs
Fix #2033
---
Cleanup the `js_run_devserver` temp directory on SIGINT in addition to standard process exit.
- Manual testing: run the devserver in `e2e/js_run_devserver` and `cmd-c` to trigger a SIGINT
> fix: cleanup js_run_devserver directory on SIGINT

- e2e/pnpm_lockfiles/v54/snapshots/defs.bzl
- e2e/pnpm_lockfiles/v60/snapshots/defs.bzl
- e2e/pnpm_lockfiles/v61/snapshots/defs.bzl
- e2e/pnpm_lockfiles/v90/snapshots/defs.bzl
- npm/private/npm_translate_lock_generate.bzl
- npm/private/test/snapshots/bzlmod/npm_defs.bzl
- npm/private/test/snapshots/wksp/npm_defs.bzl
> refactor: reduce unnecessary npm_translate_lock loop iterations

- docs/README.md
- Suggested release notes appear below: no
https://github.com/orgs/pnpm/discussions/9090
> Add example pnpm workspace configuration

- examples/coverage/BUILD.bazel
- js/private/js_binary.bzl
- js/private/js_library.bzl
---
See comment in the source file where I added repro
> fix(coverage): ensure js_library#srcs are instrumented for coverage

- docs/troubleshooting.md
- Suggested release notes appear below: no
> [docs] update exclude pattern docs

- e2e/npm_translate_lock_exclude_package_contents/BUILD.bazel
- e2e/npm_translate_lock_exclude_package_contents/MODULE.bazel
- e2e/npm_translate_lock_exclude_package_contents/WORKSPACE
- e2e/npm_translate_lock_exclude_package_contents/exclude-test.sh
- npm/private/npm_import.bzl
- npm/private/npm_package_store.bzl
[bugfix] allow multiple patterns in exclude package contents and ignore empty string as a pattern
- New test cases added (updated available one)
> [bugfix] handle multiple exclude patterns in exclude package contents

- js/private/js_image_layer.bzl
> fix: js_image_layer when binary file is directly in bin_dir

- .bazelignore
- .bazelrc
- .github/workflows/ci.yaml
- MODULE.bazel
- contrib/nextjs/BUILD.bazel
- docs/.bazelversion
- docs/BUILD.bazel
- docs/MODULE.bazel
- js/BUILD.bazel
- js/private/BUILD.bazel
- npm/BUILD.bazel
- npm/private/BUILD.bazel
Prevents compiling protoc from source in main repository
---
> refactor: move stardoc to docs/ submodule

- docs/.bazelrc
- docs/MODULE.bazel
- docs/docs.bzl
- docs/tools/BUILD.bazel
> chore: don't compile protoc under docs/ either

- docs/troubleshooting.md
- npm/private/npm_package_store.bzl
- npm/private/npm_package_store_internal.bzl
Close https://github.com/aspect-build/rules_js/issues/1179
---
> docs: add npm_package vs js_library info to troubleshooting.md

- npm/private/npm_import.bzl
> refactor: reduce use of overlapping variable names

- .aspect/rules/external_repository_action_cache/npm_translate_lock_LTE4Nzc1MDcwNjU=
- e2e/pnpm_lockfiles/base/aliases-test.js
- e2e/pnpm_lockfiles/base/package.json
- e2e/pnpm_lockfiles/lockfile-test.bzl
- e2e/pnpm_lockfiles/v54/pnpm-lock.yaml
- e2e/pnpm_lockfiles/v54/snapshots/defs.bzl
- e2e/pnpm_lockfiles/v60/pnpm-lock.yaml
- e2e/pnpm_lockfiles/v60/snapshots/defs.bzl
- e2e/pnpm_lockfiles/v61/pnpm-lock.yaml
- e2e/pnpm_lockfiles/v61/snapshots/defs.bzl
- e2e/pnpm_lockfiles/v90/pnpm-lock.yaml
- e2e/pnpm_lockfiles/v90/snapshots/defs.bzl
- examples/js_lib_pkg/b/package.json
- examples/js_lib_pkg/b/test.js
- npm/private/test/snapshots/npm_defs.bzl
- pnpm-lock.yaml
> test: aliases to local link: packages

- .github/workflows/publish.yaml
- .github/workflows/release.yml
Note, I've disabled the Publish to BCR GH app
> chore: publish attestations to BCR

- js/private/js_run_devserver.bzl
> fix: add live reload tag for ibazel

- docs/migrate.md
- docs/migrate_2.md
Most users have accomplished these migrations now so the SEO bump is not important anymore.
> chore: move docs back from aspect docsite.

- js/private/js_run_devserver.mjs
> perf: avoid extra js_run_devserver regex mem allocation

- js/private/js_run_devserver.mjs
Add experimental support for a new watch protocol to replace the ibazel stdin messages.
---
- Manual testing; please provide instructions so we can reproduce: run with tool such as aspect-cli `run --watch`
> feat: add experimental incremental watch protocol support

- MODULE.bazel
> chore: upgrade aspect_tools_telemetry to v0.2.3

- MODULE.bazel
> chore: upgrade aspect_tools_telemetry to 0.2.5
