.github/workflows/ci.yaml
.github/workflows/release.yml
docs/npm_import.md
js/npm_import.bzl
js/private/translate_package_lock.bzl
js/test/translate_package_lock_tests.bzl

We have to do a second lookup through the file to get the actual version
of the package that satisfied the dependency.
Also add the ability to patch npm packages as we fetch them,
since there's no way to use the patch-package package in this setup
where npm packages are installed individually.
These fixes needed for rules_swc

fix: translate_package_lock handles semver ranges

---

js/npm_import.bzl

We can't rely on the npm_install generated repos having the name we expect

fix: account for repository mapping

---

js/private/nodejs_binary.bzl

By default on Mac/Linux, the flag isn't set so we get a false positive here, requiring users to put --enable_runfiles in bazelrc

fix: only check for --enable_runfiles on windows

---

.github/workflows/workspace_snippet.sh
internal_deps.bzl
js/repositories.bzl

Required per https://github.com/bazel-contrib/SIG-rules-authors/issues/11

Update github archive URLs to have stable SHAs

---

js/private/nodejs_binary.bzl

Prefer to use `merge_all` when merging runfiles in a loop to avoid creating deeply nested depset.
See the docs for more info: https://bazel.build/rules/lib/runfiles#merge_all

perf: use merge_all to avoid deeply nested runfiles depsets

---

docs/nodejs_binary.md
js/nodejs_binary.bzl
js/private/nodejs_binary.bzl

I'm using this for a new jest_test rule which wants to return a similar launcher binary but control the args

refactor: allow more reuse of nodejs_binary starlark lib

---

.bazelrc
docs/BUILD.bazel
js/npm_import.bzl
js/repositories.bzl

We no longer use a fork of bazel-skylib under rules_nodejs.
This might be removable in the future if we upstream it to bazel-skylib, but no real need since we depend on aspect_bazel_lib either way.

chore: update to copy_directory

---

WORKSPACE
js/repositories.bzl

This is what is in the template https://github.com/bazel-contrib/rules-template/blob/main/mylang/repositories.bzl#L18
so that's what all our other rulesets use, and much of the community, since it comes from the style guide
> Create a file named [LANG]/repositories.bzl and provide a single entry point macro named rules_[LANG]_dependencies.
from https://docs.bazel.build/versions/main/skylark/deploying.html#dependencies

rename js_dependencies back to rules_js_dependencies

---

docs/js_binary.md
example/BUILD.bazel
js/private/js_binary.bzl
js/private/js_binary.sh.tpl
js/private/test/shellcheck_launcher.sh

- also add `verbose` attribute which sets the `JS_BINARY__VERBOSE` env var
- fix-up template params to use double `{{` braces instead of single so as not to accidentally collide with variable expansions
- remove unused template params
- fix verbose log prefix to differentiate between js_binary and js_test

fix: fix expected_exit_code attribute on js_binary/js_test

---

docs/js_binary.md
docs/node_package.md
js/defs.bzl
js/node_package.bzl
js/private/js_binary.bzl
js/private/node_package.bzl

Based on https://github.com/bazelbuild/proposals/blob/main/designs/2019-11-11-target-platform-constraints.md#proposal-a-check-method-that-takes-a-constraint-value-label
Flag added in bazel 2.1.0 https://docs.bazel.build/versions/main/skylark/lib/ctx.html#target_platform_has_constraint

chore: replace is_windows select pattern with target_platform_has_constraint pattern

---

.bazelignore
.gitignore
e2e/link_js_package/.bazelversion
js/private/link_js_package_internal.bzl

Misc cleanups,
- .bazelignore everything under /e2e
- .gitignore .pnpm-* files
- make a .bazelversion symlink in e2e folders so we are testing on consistent bazel versions
- remove print statement in bzl that was for debugging

chore: misc cleanup

---

e2e/link_js_package/pnpm-lock.yaml
js/private/translate_pnpm_lock.js

pnpm 7.0.0 was released five days ago;
also support `importers` top-level field as a pre-factor for supporting pnpm workspaces

feat: support pnpm lockfile 5.4 which was introduced in pnpm 7.0.0

---

js/private/link_js_package.bzl
js/private/npm_import.bzl

Some npm package tarballs such as https://registry.npmjs.org/usng.js/-/usng.js-0.4.5.tgz have folder permissions set to 644 (not executable) when extracted which means that the contents can be listed or copied (since they can't be listed). This resolved that by always setting folder permissions to 755 on macOS and linux.
2nd commit fixes a logic bug in lifecycle ref deps handlings

fix: set 755 folder permissions on extract npm packages

---

js/private/js_package.bzl
js/private/js_package_internal.bzl
js/private/npm_import.bzl

This speeds up linking time on after a bazel clean by approx 35%

fix: don't double copy 3rd party packages when linking with no lifecycle hook

---

.prettierignore
e2e/link_js_package/pnpm-lock.yaml
e2e/pnpm_workspace/pnpm-lock.yaml
e2e/rules_foo/foo/pnpm-lock.yaml
example/pnpm-lock.yaml

My train of thought was that by using pnpm's formatting we could simplify the parsing logic, but then I realized that consumers may run any formatter on their lockfile before passing it in 🤷‍♂️ . So it doesn't matter if we do this or not.

chore: don't run prettier on pnpm-lock.yaml files

---

js/private/npm_import.bzl

Some packages have broken directory permissions. These broken permissions can prevent GNU tar from being able to extract the files contained within the directories. Give `tar` `--delay-directory-restore` to delay setting directory permissions until after the files have been extracted.
Only enable this on linux because it appears that macOS does not hit this issue. It likely uses delayed permission expansion by default, as it also doesn't have the flag available. I don't have a windows machine to test on, but given that the other `chmod` fix directly below executing `tar` only runs on non-windows platforms, I'm assuming we don't need to worry there.
One example package that hits this issue:
* https://registry.npmjs.org/react-virtualized/-/react-virtualized-9.22.3.tgz
* After applying this …

Delay expanding permissions on directories when extracting packages on linux

---

js/private/npm_import.bzl
js/private/test/package_json_checked.bzl
js/private/test/package_json_with_dashes_checked.bzl
js/run_js_binary.bzl

Also add a friendly failure message if a user specifies data instead of srcs in `run_js_binary`

fix: don't pop data from kwargs attribute in generated bins build (run_js_binary) macro

---

js/private/npm_import.bzl

to support patches such as these
```
translate_pnpm_lock(
name = "npm",
pnpm_lock = "//:pnpm-lock.yaml",
patches = {
"stringify-entities@4.0.2": ["//:patches/stringify-entities@4.0.2.patch"],
"decode-named-character-reference@1.0.1": ["//:patches/decode-named-character-reference@1.0.1.patch"],
},
)
```

fix: apply npm_import patches before reading the package.json file incase package.json itself needs patching

---

examples/js_binary/BUILD.bazel
js/run_js_binary.bzl

The dictionary value of `env` was being masked over by a for loop, resulting in a string (the debug key) being passed to `dicts.add`, which caused it to error out:
```
ERROR: Traceback (most recent call last):
File "/home/alex.torok/code/rules_js/examples/js_binary/BUILD.bazel", line 27, column 14, in <toplevel>
run_js_binary(
File "/home/alex.torok/code/rules_js/js/run_js_binary.bzl", line 159, column 24, in run_js_binary
env = dicts.add(extra_env, env),
File "/home/alex.torok/.cache/bazel/_bazel_alex.torok/a35b6b5cd0642228cee40197cc66bc5c/external/bazel_skylib/lib/dicts.bzl", line 37, column 22, in _add
result.update(d)
Error in update: in update, got string, want iterable
```
Use a new variable name when iterating over the log level env values and update an example to set the log_level …

fix: fix bug when setting log_level in `run_js_binary`

---

js/private/js_binary.sh.tpl
js/private/test/shellcheck_launcher.sh

Fix how the logging function in the `js_binary` runner calls printf.
Previously, the format string was being treated like an argument to be
placed in the formatted output. This lead to incorrect rendering of the
formatted string. This PR fixes that by pulling the format string out of
the args list and using that in the printf call.
Compare debug output and failing `expected_exit_code = X` tests
before/after this change:
before:
```
DEBUG: aspect_rules_js[js_binary]: BAZEL_BINDIR %s bazel-out/k8-fastbuild/bin
DEBUG: aspect_rules_js[js_binary]: BAZEL_TARGET_CPU %s k8
DEBUG: aspect_rules_js[js_binary]: BAZEL_COMPILATION_MODE %s fastbuild
```
```
ERROR: aspect_rules_js[js_test]: expected exit code to be '%s', but got '%s' 1 0
```
after:
```
DEBUG: aspect_rules_js[js_binary]: BAZEL_BINDIR …
```

fix debug message formatting

---

js/private/js_binary.bzl

This makes it easier to migrate to rules_js, if you were referring directly to paths in bazel-out

refactor: name launcher script like nodejs_binary does

---

js/private/js_binary.bzl

The windows `.bat` script calls the bash script, but it's missing from runfiles.

fix: broken windows build caused by missing bash script in runfiles

---

npm/private/npm_translate_lock.bzl
npm/private/test/defs_checked.bzl

Relevant for downstream rules that vendor in the generated file

fix: remove unused load in generated code & that also generated a private visiblity warning in buildifier

---

examples/js_binary/BUILD.bazel

The test compares `js_run_binary` `stdout` which always seems to produce unix line endings, and a `write_file` which by default uses the platform's line ending format. I'm not sure which one of the two to change.

fix: failing windows test due to wrong expected line endings

---

MODULE.bazel
examples/assert_lockfile_up_to_date/BUILD
js/repositories.bzl

This is the last windows regression aside from the `node-gyp` issue.

fix: keep lockfile up to date example windows regression

---

examples/macro/mocha.bzl

js_test will copy data files to bin that are in the current bazel package

chore: mocha example doesn't need copy_to_bin

---

docs/migrate.md
e2e/npm_link_package/BUILD.bazel
e2e/pnpm_workspace/app/a/BUILD.bazel
e2e/pnpm_workspace_dot_dot/app/a/BUILD.bazel
examples/js_binary/BUILD.bazel
examples/js_library/two/BUILD.bazel
examples/macro/mocha.bzl
examples/npm_deps/BUILD.bazel
js/private/node-patches/src/BUILD.bazel
npm/private/npm_import.bzl
npm/private/npm_translate_lock.bzl

(small) BREAKING CHANGE
Examples:
------------
```
load("@npm//typescript:package_json.bzl", typescript_bin = "bin")
```
becomes,
```
load("@npm//:typescript/package_json.bzl", typescript_bin = "bin")
```
------------
```
load("@rules_foo_npm//foo/@aspect-test/a:package_json.bzl", aspect_test_a_bin = "bin")
```
becomes,
```
load("@rules_foo_npm//foo:@aspect-test/a/package_json.bzl", aspect_test_a_bin = "bin")
```

refactor: tweak ':' separator locations in package_json.bzl load paths

---

npm/private/npm_import.bzl
npm/private/test/package_json_checked.bzl
npm/private/test/package_json_with_dashes_checked.bzl

https://github.com/aspect-build/rules_js/pull/218 added the ability to use the bin name as the default mnemonic for generated package_json.bzl entries. Some generated bin entries have underscores in their name, which is not allowed in action mnemonics. 
Without this change, you can get:
```
Error in run: mnemonic must only contain letters and/or digits, and have non-zero length, was: "webpack_cli"
```
Use a CamelCase version of the bin name instead.

fix: use camel case in generated bin mnemonics

---

.prettierignore
examples/js_library/two/BUILD.bazel
examples/js_library/two/tsc-docs.md
examples/js_library/two/tsc.bzl
examples/macro/BUILD.bazel
examples/macro/mocha-docs.md
npm/private/npm_import.bzl
npm/private/npm_translate_lock.bzl

This allows users to document their starlark code which loads from the generated bins.
It also makes bazel query look better when exploring the @npm repository, as there are now targets everywhere.

refactor: expose bzl_library targets for generated bins

---

npm/private/npm_link_package.bzl

This lets them be propagated to a container_image layer which also wants to have them, just via the binary target
Pulled this file from https://github.com/aspect-build/rules_js/pull/249/

refactor: ask the runfiles API to create our symlinks

---

js/private/coverage/bundle/BUILD.bazel
js/private/node-patches/fs.js
js/private/node-patches/src/fs.ts
js/private/test/node-patches/realpath.js

Since fs.realpath uses fs.lstat, this can create an infinite loop. Same fix for the sync versions.

fix: don't use orig fs.realpath from patched lstat

---

e2e/pnpm_workspace/.bazelignore
e2e/pnpm_workspace/app/c/BUILD.bazel
e2e/pnpm_workspace/app/c/main.js
e2e/pnpm_workspace/app/c/package.json
e2e/pnpm_workspace/lib/c/BUILD.bazel
e2e/pnpm_workspace/lib/c/index.js
e2e/pnpm_workspace/lib/c/package.json
e2e/pnpm_workspace/pnpm-lock.yaml
e2e/pnpm_workspace_dot_dot/.bazelignore
e2e/pnpm_workspace_dot_dot/app/c/BUILD.bazel
e2e/pnpm_workspace_dot_dot/app/c/main.js
e2e/pnpm_workspace_dot_dot/app/c/package.json
e2e/pnpm_workspace_dot_dot/lib/c/BUILD.bazel
e2e/pnpm_workspace_dot_dot/lib/c/index.js
e2e/pnpm_workspace_dot_dot/lib/c/package.json
e2e/pnpm_workspace_dot_dot/root/pnpm-lock.yaml
js/private/js_run_binary.bzl
npm/private/npm_translate_lock.bzl
npm/private/transitive_closure.bzl

Fixes https://github.com/aspect-build/rules_js/issues/167
NB: packages references by `file:` links cannot themselves `file:` or `workspace:` links. You'll get a friendly error message if you try. For that pattern just switch to pnpm workspaces and drop the `file:` links altogether and use `workspace:` links between packages.

feat: support file: links in package.json & pnpm lockfile

---

examples/js_binary/BUILD.bazel

We've got some user reports that this is not working but don't have a repro yet

chore: add an example of using out_dirs with js_run_binary

---

examples/webpack_cli/BUILD.bazel
examples/webpack_cli/index.js

After updating to the latest release of rules_js, I hit an issue where `js_library` targets no longer pull the files from their `deps` into the sandbox's bin directory. I bisected the problem to #252, which modified the `DefaultInfo` for `js_library`.
I'm not sure if I'm not following the correct usage pattern for `js_library`, but also noticed that there are no cases of `js_library` with `deps` on a `:node_modules/*` target within the `examples/` or `e2e/` directories.
This PR reproduces what I'm seeing by building on top of the existing `webpack_cli` example. You can see the build failure with `bazel build //examples/webpack_cli:bundle`
Should `js_library` work in the way showcased here? If not, what is the recommended way to express a library target with srcs and a dependency on an npm …

bug: js_library with 'deps' no longer pulls deps into sandbox output tree

---

examples/js_binary/BUILD.bazel
js/private/js_binary.sh.tpl
js/private/test/shellcheck_launcher.sh

Fixes https://github.com/aspect-build/rules_js/issues/285
Without the fix commit,
```
$ bazel run //examples/js_binary:bin10
INFO: Analyzed target //examples/js_binary:bin10 (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //examples/js_binary:bin10 up-to-date:
bazel-bin/examples/js_binary/launch_case10.sh
bazel-bin/examples/js_binary/bin10
INFO: Elapsed time: 0.139s, Critical Path: 0.00s
INFO: 2 processes: 2 internal.
INFO: Build completed successfully, 2 total actions
INFO: Build completed successfully, 2 total actions
FATAL: aspect_rules_js[js_binary]: RUNFILES environment variable is not set
```
with the commit
```
$ bazel run //examples/js_binary:bin10
INFO: Analyzed target //examples/js_binary:bin10 (0 packages loaded, 0 targets configured).
INFO: Found 1 …
```

fix: determine the RUNFILES directory when running a js_binary in an sh_binary

---

js/private/node-patches/fs.js
js/private/node-patches/src/fs.ts

This fix comes from https://github.com/aspect-build/rules_js/pull/283 where we are using declare_symlink that creates relative symlinks. Coverage for regression will come when that lands so we support RBE with rules_js.

fix: fix relative symlinks handing in node fs patches

---

js/private/BUILD.bazel

This is a direct dependency of all `js_binary()` targets and is currently `//visibility:public` by default, however this behavior is changing and can be opted in early via the [`--incompatible_config_setting_private_default_visibility`](https://bazel.build/reference/command-line-reference#flag--incompatible_config_setting_private_default_visibility) flag. Making this target explicitly public passes the build with that flag.
See [this CI failure](https://github.com/dgp1130/rules_prerender/runs/7423144733?check_suite_focus=true) using the `--incompatible_*` flag.

fix: make `//js/private:enable_runfiles` explicitly have `//visibility:public`

---

.bazelrc.common

They fixed this issue I raised: https://github.com/bazelbuild/bazel-skylib/issues/376.

chore: add reminder to clean up bazelrc once skylib fix is released

---

js/private/test/node-patches/spawn.js

These are failing for me locally on macos since macos doesn't have realpath

fix: only run tests cases that depend on realpath on linux

---

npm/private/npm_link_package.bzl

No CI for this yet as its not yet load bearing; waiting on support in Bazel

fix: fix typo in make_symlink helper for the declare_symlink path that is not load bearing yet

---

.github/workflows/release.yml

The reason this works is because the default github actions token is not allowed to trigger followup actions, so the bcr actions that listen for releases won't be triggered unless a more authoritative token is used here.

fix: bcr actions not triggering

---

npm/private/npm_translate_lock.bzl

this change allows us to do `bazel fetch @npm//:all`

fix: generate package_json.bzl only when pkg has bins

---

examples/js_binary/BUILD.bazel
examples/js_binary/custom_rule.bzl
js/private/js_binary.sh.tpl
js/private/test/shellcheck_launcher.sh

This bug was hit when upgrading rules_swc and rules_ts to 1.0.0-rc.2
cc @thesayyn @jbedard

fix: ensure RUNFILES environment variable is always absolute

---

js/private/js_library.bzl

This is to support upgrade rules_ts to the latest rules_js. Skipping regression test cases for this since this code will all change with the refactors coming in https://github.com/aspect-build/rules_js/pull/318

fix: pick up DeclarationInfo from srcs in js_libary

---

e2e/bzlmod/BUILD.bazel
js/private/js_binary.bzl
js/private/test/node-patches/BUILD.bazel

We technically don't need to copy anything to bin that is passed to runfiles since bazel flattens that tree. Not copying things to bin in js_binary has some interesting side-effects that are seen. Copying was hiding some bugs/bad behavior.

fix: js_binary doesn't need to copy files to bin for runfiles inputs

---

docs/js_binary.md
e2e/bzlmod/BUILD.bazel
js/private/js_binary.bzl
js/private/test/shellcheck_launcher.sh

Fixes https://github.com/aspect-build/rules_js/issues/341, the issue of .mjs entry files escaping the runfiles and sandbox

feat: set --preserve-symlinks-main in js_binary by default and add preserve_symlinks_main attribute for opt-out

---

npm/private/transitive_closure.bzl

There's no problem with having these empty.
Fixes #363

refactor: remove check for empty root importers

---

.github/workflows/ci.yaml

Currently,  caching outputs of `bazel test` seems not working when I looked at "Post Mount bazel caches" step:
``` 
Warning: Path Validation Error: Path(s) specified in the action for caching do(es) not exist, hence no cache is being saved.
```
When I removed double quotes from cache paths, the warning was gone.

Fix bazel caches in GitHub Actions

---

e2e/js_image/BUILD.bazel

Makes it more clear what our direct dependencies are, vs transitives from python/pkg

refactor: cleanup bzl_library in js_image

---

WORKSPACE
docs/npm_import.md
npm/npm_import.bzl
npm/private/npm_import.bzl
npm/private/npm_link_package_store.bzl
npm/private/npm_translate_lock.bzl
npm/private/test/BUILD.bazel
npm/private/test/bin_test.sh
npm/private/test/repositories_checked.bzl

This will be most useful for integration tests that want to run `node_modules/.bin` tools directly.
Only generating bash binaries for now. Windows can use sh_test.
For now the bin entries must be entered manually.
In the future, this field may be automatically populated by translate_lock_file from information in the pnpm lock file. That feature is currently blocked on https://github.com/pnpm/pnpm/issues/5131.

feat: add node_modules/.bin binary files support to npm_translate_lock, npm_import and npm_link_package_store

---

e2e/pnpm_workspace/BUILD.bazel
e2e/pnpm_workspace/WORKSPACE
e2e/pnpm_workspace/package.json
e2e/pnpm_workspace/pnpm-lock.yaml
e2e/pnpm_workspace/test.sh
e2e/pnpm_workspace_rerooted/BUILD.bazel
e2e/pnpm_workspace_rerooted/WORKSPACE
e2e/pnpm_workspace_rerooted/root/package.json
e2e/pnpm_workspace_rerooted/root/pnpm-lock.yaml
e2e/pnpm_workspace_rerooted/test.sh
npm/private/npm_link_package_store.bzl

Missed this case in the original impl

fix: fix node_modules/.bin script pathing when pnpm workspace is not at the root of the WORKSPACE

---

npm/private/npm_translate_lock.bzl

Otherwise we just skip past this and give the user an unhelpful error that pnpm-lock.yaml isn't found
Partial fix for #396

fix: add error handling for failure of pnpm import

---

MODULE.bazel

MODULE.bazel version was out of sync with the standard dependency version

chore: update aspect_bazel_lib to 1.11.1 in MODULE.bazel

---

.github/workflows/ci.yaml

... can this PR test the ability for forked PRs to run? 🤔 (I'll assume not)

ci: run PR workflow on main repo and not forks

---

docs/faq.md
docs/migrate.md

Following up to our Slack conversation, here is a small addition to the migration guide that mentions how `npm_translate_lock` attributes interacts with `pnpm-workspace.yaml`.
Indirect follow-up of https://github.com/aspect-build/rules_js/issues/396

doc caveat with pnpm-workspace.yaml and auto import

---

e2e/npm_link_package-esm/BUILD.bazel
e2e/npm_link_package-esm/lib/BUILD.bazel
e2e/npm_link_package-esm/lib/index.mjs
e2e/npm_link_package-esm/package.json
e2e/npm_link_package-esm/pnpm-lock.yaml
e2e/npm_link_package-esm/src/BUILD.bazel
e2e/npm_link_package-esm/wrapper-lib/index.mjs

Closes #434
Adds the test using `uvu` and adds some comments clarifying things. Also trying to keep the diff between the folders to only be the cjs vs esm changes.

test: align commonjs + esm npm_link_package tests

---

docs/faq.md
docs/migrate.md
docs/npm_import.md
npm/npm_import.bzl
npm/private/npm_import.bzl

This lets us document how to run Bazel's managed node and pnpm, without leaking out to the system node.
Requires a new feature on npm_import so that we can inject more content to the BUILD file.
Fixes #247

feat: supply a @pnpm//:pnpm binary

---

.github/workflows/ci.yaml

Stop using Aspect's fork of Bazel.
Next step is once there's a rolling release, we should pin to that here, so we know Bazel 6 will work.

chore: prove that Bazel at HEAD works with RBE now

---

docs/faq.md
docs/migrate.md

Otherwise it will run with a working directory in the bazel-out/.../pnpm.runfiles/

docs: suggest --dir when bazel run pnpm

---

renovate.json

This configures the renovate bot to only open PRs Monday, and only on releases at least 3 days old. The `config:base` has a few things such as limiting the total number of PRs (I think 10) etc.

chore(deps): only open renovate PRs weekly, on packages stable for 3 days

---

.github/workflows/ci.yaml
js/private/coverage/bundle/c8.js
js/private/coverage/coverage.js
js/private/test/coverage/BUILD.bazel
js/private/test/coverage/lib.js
js/private/test/coverage/test.bzl

fix: do not run coverage reporter if already reported

---

js/private/js_library.bzl
js/private/test/js_library_test.bzl

See https://github.com/bazelbuild/rules_nodejs/issues/3551

fix(typescript): include all .json in JsInfo.declarations

---

docs/js_binary.md
js/private/js_binary.bzl
js/private/js_run_binary.bzl
js/private/test/create_launcher/BUILD.bazel
js/private/test/create_launcher/custom_test.bzl
js/private/test/create_launcher/test.js

@mrmeku's work on rules_cypress showed that there is a need for this
The API change here is not breaking and only affects downstream rules

feat: add missing fixed_env attribute to create_launcher helper for downstream rules to use

---

renovate.json

The main thing is group all non-major updates into single PRs.
I'm still tempted to group updates into smaller PRs instead of one giant one. Things like "all npm dev dependencies", "all npm non-dev dependencies", "all bazel deps", "all java deps" etc. Is that better then a single PR for everything? Or is less PRs better no matter what gets mixed in?

chore: configure renovate to group PRs

---

.bcr/config.yml

Because we use the github actions bot to publish a release, the Publish to BCR app doesn't have a way to identify someone as the commit author for a new bcr entry. This sets it to you always.

ci: use fixed releaser for bcr commit

---

.github/workflows/ci.yaml
e2e/npm_translate_lock_auth/.npmrc
e2e/npm_translate_lock_auth/package.json
e2e/npm_translate_lock_auth/pnpm-lock.yaml
e2e/rules_foo/npm_repositories.bzl
npm/private/npm_import.bzl
npm/private/npm_translate_lock.bzl
npm/private/test/BUILD.bazel
npm/private/test/npm_auth_test.bzl
npm/private/test/repositories_checked.bzl
npm/private/test/utils_tests.bzl
npm/private/utils.bzl

This PR adds the ability to support multiple registries and auth tokens via .npmrc.
This branch was cloned from #499 and addresses #502. 
It is being developed in an upstream branch because the e2e test won't run on my fork since it requires a secret which isn't available for forks.

feat: support multiple npm registries and tokens via .npmrc

---

docs/js_binary.md
js/private/js_binary.bzl

From a thread on Bazel slack https://bazelbuild.slack.com/archives/CEZUUKQ6P/p1664906135068089?thread_ts=1664899186.632239&cid=CEZUUKQ6P

chore: add additional information to js_test docstring re: the Bazel test runner contract

---

renovate.json

This to to (hopefully) merge things like the 3 rollup major updates in shown in https://github.com/aspect-build/rules_js/issues/179 into a single PR instead of 3. I'm not sure if these rollup ones are actually in the recommended/monorepos but lets start with just these 2 preset configs.
I think non-major version will all still be in one giant PR such as https://github.com/aspect-build/rules_js/pull/509 and this will only effect major versions.
Reducing the `stabilityDays` to 3 which is the standard value since npm packages can be unpublished the first 3 days.

renovate - group recommended/monorepo including major version, reduce stabilityDays to 3

---

renovate.json

The current PR (see https://github.com/aspect-build/rules_js/commit/327b79c77ae3093f14d98942d30be5aabe2405da) with every minor+patch update is too big and hard to determine the reason for the CI error, so everyone has ignored it for a week now.
So lets try only grouping patches? Minor+major updates will (hopefully 🤞) be grouped by monorepo and "recommended" groups.
This is a modified version of https://docs.renovatebot.com/presets-group/#groupallnonmajor

renovate: only group patch updates of unrelated deps

---

renovate.json

Currently rules_js has 3 of these in separate PRs (or they will be once the schedule runs). They are unfortunately not part of the `group:monorepos` or `group:recommended` I guess because they aren't versioned together. But I'd like to take the chance of one of them breaking just to reduce PRs.
Again I haven't found a way of testing this so we'll have to merge to test it :(

renovate: group rollup related updates

---

renovate.json

The main rollup was in its own PR, also adding bazel groups with aspect rules in their own group.

renovate: rollup, aspect, bazel groups

---

js/private/coverage/bundle/package.json

This was the offending commit; https://github.com/aspect-build/rules_js/commit/893bbcbc4ebd70e7ed7e729c965c6ae52a53d53e
Looks like renovate did update the lockfile but maybe it was using an old version of pnpm as when I update the lockfile locally I still see changes that break the coverage bundle

fix: downgrade rollup back to 2.79.0

---

js/private/node-patches/fs.js
js/private/node-patches/src/fs.ts
js/private/test/node-patches/lstat.js
js/private/test/node-patches/readdir.js
js/private/test/node-patches/readlink.js
js/private/test/node-patches/realpath.js

This makes my test of 500 basic files about 2x faster, going from a fairly consistent 7.5-8 to 3.5-4. Those 500 files are just `expect(true).toBeTrue()` so the time invoking tests should be ~0 and it's all jest running, node loading files etc.
Originally I only wrapped some internal functions such as `guardedRealPathSync` but I think it's better to just wrap the full public methods so the `Error` try/catch modifications only happen once. The worry with that is stack traces thrown within the implementations wouldn't be complete but that seems to still work, see the stack trace tests.
See https://github.com/aspect-build/rules_jest/issues/50

perf: prevent preparing stack traces in fs *Sync patches

---

.bazelversion
.github/workflows/ci.bazelrc
.github/workflows/ci.yaml
MODULE.bazel
e2e/bzlmod/.bazelversion
js/repositories.bzl

Looks like --remote_download_toplevel regressed in the 6.0.0rc1 release. It now breaks the build.
Tested with yesterday's pre-release https://github.com/bazelbuild/bazel/releases/tag/6.0.0-pre.20221012.2 and it was not broken there.
Also adds bazelversion matrix axis so we continue to test bazel v5.3.2 on CI

chore: update to Bazel 6.0.0rc1

---

npm/private/npm_translate_lock.bzl
npm/private/test/npm_auth_test.bzl
npm/private/test/utils_tests.bzl
npm/private/utils.bzl

Assigning the default registry protocol is now done when reading them from npmrc instead of when using them. So the `registries` map passed around now has the protocols in the URLs.
I'm not sure how the `//no-protocol.com` cases should be handled though. Normally that means to "use the current protocol", but idk what the "current" is?

fix: support non-https registry protocols

---

js/private/bash.bzl
js/private/js_binary.sh.tpl
js/private/test/shellcheck_launcher.sh

This has been broken for a while on Windows. We don't have Windows CI yet for rules_js so it wasn't caught until the BCR pre-submit failed.

fix: fix windows regression in js_binary launcher bash script

---

renovate.json

Further attempts at reducing spam by...
* adding a webpack group similar to rollup (both have tons of plugins/addons)
* fixing `"matchPackageNames": ["^aspect_"]` which should be `matchPackagePatterns`
* reordering to put the more specific/strict rules at the bottom

renovate: fix aspect rule group, add webpack group, prioritize strict groups

---

js/private/test/js_library_test.bzl
npm/private/npm_link_package_store.bzl

This way it will be a valid `ts_project` dep like we were discussing.
This PR currently does the same as what `js_library` does for directories but 100% of the time. Here `js_library` does this only when finding a directory with unknown content: https://github.com/aspect-build/rules_js/blob/2bc5e8622b9509b370fbbd44e9022900d15b5244/js/private/js_library.bzl#L126-L129

fix: always set JsInfo.declarations on npm_link_package_store targets

---

.bcr/config.yml

Made a breaking change to the BCR app API. `fixedReleaser` now needs an email because the app can't reliably get a user's email to use in the bcr commit unless they make their email public.

fix: update fixed releaser format

---

.bazelrc.common

`--experimental_allow_unresolved_symlinks` is already on by default in Bazel 6.0.0rc1 which is the version used with RBE

chore: remove redunant --experimental_allow_unresolved_symlinks

---

js/private/node-patches/fs.js
js/private/node-patches/src/fs.ts

Caches all fs access operations when reading symlinks, specifically: if a file is a symlink, and what it points.
The underlying `readlinkSync` call throws when called on a non-symlink. Previously calculating the exception stack trace used a significant amount of time. This prevents the exception by doing `lstat` first, the combined result of `lstat` + `readlink` are then cached.

perf: cache fs patch fs lookups 

---

renovate.json

Still playing around with this config in rules_js before we put it into each of our repos and enable it everywhere. Main goal is the reduce spam while still automating things. Can hopefully enable automerge as well.
The summary:
* use standard/recommended config, group by monorepo etc, send PRs weekly by default
* group all patches (unless one of the below matches)
* group all bazel minor/patch
* group all in the aspect github org, open PRs instantly
* group a few spamy npm packages (types/rollup/webpack) and do them monthly
* otherwise it will open individual PRs weekly

renovate: upgrade aspect deps asap, reduce spam of various dep types/names

---

e2e/vendored_node/.bazelignore
e2e/vendored_node/.bazelrc
e2e/vendored_node/.bazelversion
e2e/vendored_node/BUILD.bazel
e2e/vendored_node/WORKSPACE
e2e/vendored_node/test.js
e2e/vendored_node/toolchains/BUILD.bazel
js/private/js_binary.sh.tpl
js/private/test/shellcheck_launcher.sh

I also ported over the e2e test from rules_nodejs for a vendored node but there still is no test coverage for the absolute path to node & npm as that test would depend on having a node on the local machine. Could be added to a CI only test at some point but not that important atm. I had a need for this change when testing against a locally built node from source which is how this came up. Tested locally that the absolute path to node works:
```
load("@rules_nodejs//nodejs:toolchain.bzl", "node_toolchain")
toolchain(
name = "node_macos_toolchain",
exec_compatible_with = [
"@platforms//os:macos",
"@platforms//cpu:x86_64",
],
toolchain = ":node_macos",
toolchain_type = "@rules_nodejs//nodejs:toolchain_type",
)
node_toolchain(
name = "node_macos",
target_tool_path = …
```

fix: allow for absolute path to node specified in target_tool_path in node_toolchain

---

WORKSPACE
npm/npm_import.bzl
npm/private/npm_import.bzl
npm/private/npm_translate_lock.bzl
npm/private/test/repositories_checked.bzl

These targets are only needed in rules_js itself for a test case. Not currently needed in any downstream rule sets AFAIK and definitely not needed in user workspaces.

fix: don't generate bzl_library targets in npm_translate_lock and npm_import by default

---

docs/js_run_devserver.md
e2e/js_run_devserver/package.json
e2e/js_run_devserver/pnpm-lock.yaml
e2e/js_run_devserver/src/BUILD.bazel
e2e/js_run_devserver/src/simple.js
e2e/js_run_devserver/test.sh
js/private/BUILD.bazel
js/private/js_run_devserver.bzl

Fixes https://github.com/aspect-build/rules_webpack/issues/66
Also address Bazel Slack question https://bazelbuild.slack.com/archives/CEZUUKQ6P/p1667857230697759

fix: include transitive linked npm deps in js_run_devserver sandbox

---

docs/js_run_devserver.md
e2e/js_run_devserver/multirun_test.sh
e2e/js_run_devserver/serve_test.sh
e2e/js_run_devserver/src/BUILD.bazel
js/private/BUILD.bazel
js/private/js_run_devserver.bzl

Resolves issue reported on Bazel Slack https://bazelbuild.slack.com/archives/CEZUUKQ6P/p1667931292061319?thread_ts=1667857230.697759&cid=CEZUUKQ6P

fix: include transitive source in js_run_devserver sandbox

---

e2e/js_run_devserver/multirun_test.sh
e2e/js_run_devserver/serve_test.sh
e2e/js_run_devserver/src/BUILD.bazel

I've seen this randomly failing, specifically timing out I think due to a port conflict?
If I'm understanding this correctly the multirun test was assuming the first run would take port 8080 and the second would take 8081 because 8080 was in use? This is a race condition and I'm finding the second one often also tries 8080 and then fails, the "waiting (8081)" loop then loops forever.
I found the logging info useful when trying to debug so leaving it in.

test: explicitly set devserver test ports

---

js/private/node-patches/register.js

For example as a test... without the `syncBuiltinESMExports` the last log (5) is false:
```
import('fs').then(importFS => {
console.log(1, origReaddirSync === fs.readdirSync)          // pre patched
console.log(2, origReaddirSync === importFS.readdirSync)    // pre patch
patchfs(fs, roots)
console.log(3, origReaddirSync !== fs.readdirSync)          // post patched
console.log(4, origReaddirSync === importFS.readdirSync)    // pre synced
module.syncBuiltinESMExports()
console.log(5, origReaddirSync !== importFS.readdirSync)    // post sync
});
```

fix: sync fs esm library after patching cjs version

---

MODULE.bazel

Version no longer needed in the MODULE.bazel file thanks to @kormide's wizardry in the bzlmod bot

chore: unrelease

---

e2e/js_image/js_image_layer.bzl
js/private/js_binary_helpers.bzl
npm/npm_import.bzl
npm/private/npm_translate_lock.bzl
npm/private/transitive_closure.bzl
npm/private/utils.bzl
npm/private/yaml.bzl

Looks like some formatting got tripped on yaml.bzl as well

chore: tidy up error messages for string substitutions so they show up cleaner when they are hit

---

npm/private/npm_package.bzl

The copy_to_direction action accepts a depset https://github.com/aspect-build/bazel-lib/blob/main/lib/private/copy_to_directory.bzl#L744

perf: remove unnecessary additiona_files.to_list() in npm_package

---

npm/private/npm_translate_lock.bzl

Tricky one. npm_imports can fall out of line from packages list when one of the packages is a `file:` link. Code was relying on the back practice of indexes lining up in two different lists 🤦

fix: fix npm_imports and packages list unaligned bug

---

.aspect/workflows/config.yaml
.github/workflows/ci.yaml
e2e/vendored_node/WORKSPACE
e2e/vendored_node/test.js

Also bump vendored version to node 16 since node 15 doesn't support the `node:fs` style imports. Those were added in 16 and then back-ported to 14 but not 15.

chore: enable vendored_node e2e test on CI

---

npm/private/BUILD.bazel
npm/private/npm_translate_lock.bzl
npm/private/npmrc.bzl
npm/private/test/BUILD.bazel
npm/private/test/npmrc_test.bzl

Fixes https://github.com/aspect-build/rules_js/issues/622
We're diverging from the INI format by not treating keys as case-insensitive to resolve #622

fix: treat npmrc keys as case-sensitive

---

.github/workflows/workspace_snippet.sh
e2e/workspace/.bazelignore
e2e/workspace/.bazeliskrc
e2e/workspace/.bazelversion
e2e/workspace/BUILD.bazel
e2e/workspace/WORKSPACE
e2e/workspace/package.json
e2e/workspace/pnpm-lock.yaml

Right now we tell everyone to copy-paste a thing which assumes they have typescript

doc: make the release snippet easier to use

---

npm/private/npm_translate_lock.bzl

This regressed in rules_js 1.8.0 with https://github.com/aspect-build/rules_js/pull/642 but the problem was masked on CI by the external repository cache. Didn't see it failing until that cache was busted on GH actions: https://github.com/aspect-build/rules_js/actions/runs/3568511414/jobs/5997665772#step:8:62

fix: fix regression in .npmrc _authToken parsing

---

npm/npm_import.bzl

There's no reason to restrict visibility, anyone might want to depend on this program
Fixes #657

chore: make @pnpm//:pnpm target public

---

e2e/npm_translate_lock/.npmrc
e2e/npm_translate_lock/package.json
e2e/npm_translate_lock/pnpm-lock.yaml
e2e/npm_translate_lock/repositories_checked.bzl
e2e/npm_translate_lock/test.sh
npm/private/npm_translate_lock.bzl

Not sure when this regressed since we only had the bzl snapshot test for coverage. I added a `test.sh` script now to make appropriate assertions on the bzl snapshot.

fix: fix .npmrc default registry logic

---

npm/private/npm_translate_lock_state.bzl

To match pnpm behaviour we should only look for an `.npmrc` file next to the lock file and not at the root of the WORKSPACE. This also prevents an incorrect warning with `npm_translate_lock` rules from external workspaces as is done in downstream rule sets to provision tools.

fix: don't look for root nmprc

---

npm/private/npm_translate_lock.bzl

Printing out the working directory in the status was a bit much in retrospect

chore: simplify preupdate script status message

---

npm/npm_import.bzl

https://github.com/aspect-build/rules_js/pull/718 introduced a bug when using lifecycle hook exclusions where the values in the frozen dict `lifecycle_hooks` are mutated, which results in a hard error.
Just before the check, create a copy of the original frozen value. This is likely very cheap as these dicts are small if not empty.
Unblocks https://github.com/aspect-build/silo/pull/1005

fix: don't mutate the frozen values in lifecycle_hooks dict

---

npm/extensions.bzl
npm/private/npm_translate_lock_generate.bzl

Check that all patches files specified were used; this is a defense-in-depth since it is too easy to make a type in the patches keys or for a dep to change both of with could result in a patch file being silently ignored.
Tested manually to trigger the fail:
```
ERROR: Error computing the main repository mapping: no such package '@npm//': 
ERROR: Patch file key `not_a_package@1.2.3` does not match any npm packages in `npm_translate_lock(name = "npm").
Either remove this patch file if it is no longer needed or change its key to match an existing npm package.
```

feat: fail if any npm_translate_lock patches are not used

---

e2e/js_image/BUILD.bazel
e2e/js_image/js_image_layer.bzl

The `js_image_layer`  rule currently relies on a hacky approach to get the symlinks targets working in the built Docker images by stripping the `execroot` from the path. The problem is that there is no `execroot` on the RBE, so I tried to get the paths corrected on remote builds too.
This has been tested on the open-source [Bazel Buildfarm](https://github.com/bazelbuild/bazel-buildfarm) RBE.

fix: js_image_layer build on RBE

---

README.md

At this point we're not introducing ourselves as an alternative to an old thing, that changed 9 months ago

docs: move mention of rules_nodejs lower in README

---

npm/extensions.bzl

Prefactor for https://github.com/aspect-build/rules_js/pull/647. Step towards https://github.com/aspect-build/rules_js/issues/644.
Sorting the attributes alphabetically makes it easier to keep track of what's missing from the WORKSPACE api.

prefactor: sort bzlmod attributes and fix npm_translate_lock name

---

.github/workflows/ci.yaml

In support of: https://github.com/aspect-build/rules_js/issues/644
This adds a test matrix vector that exercises bzlmod for all unit and e2e tests. This way we can test that all of our e2es work under bzlmod and can keep the WORKSPACE/bzlmod apis in sync.
Currently this will fail because we need to add `MODULE.bazel` files to each e2e and actually fix the bzlmod api. The module files should be ignored during non-bzlmod test runs.
I can either ignore failing tests for now, or we can keep this PR open until all are fixed.

chore: add bzlmod test matrix

---

.github/workflows/ci.yaml

Missed one that only runs after merging.

ci: ignore a bzlmod e2e that doesn't yet have a MODULE.bazel file

---

npm/private/npmrc.bzl
npm/private/test/npmrc_test.bzl

Essentially just stripping quotes, no escaped characters etc.
Fixes #746

fix: support quoted npmrc values

---

renovate.json

I assumed setting it to "major" meant "major and below", that seems to be wrong :/

renovate: correct grouping of minor/patch releases

---

.aspect/rules/external_repository_action_cache/npm_translate_lock_LTE4Nzc1MDcwNjU=
npm/private/test/package.json
pnpm-lock.yaml

Not sure why but at some point the following error started to happen outside of bazel in the prepare lifecycle hook which is being testing:
```
src/oidc_auth.ts(2,48): error TS2307: Cannot find module 'openid-client' or its corresponding type declarations.
```
full error log:
```
...2107_38676d339eae84ca91c8293d2287683a npm-install$ npm install
│ npm WARN deprecated har-validator@5.1.5: this library is no longer supported
│ npm WARN deprecated mkdirp@0.5.4: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
│ npm WARN deprecated debug@3.2.6: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.
│ npm …
```

build: bump @kubernetes/client-node dep due to failure

---

js/private/BUILD.bazel

For removal of downstream patch in silo

chore: add missing bzl_library for expand_template.bzl

---

WORKSPACE
docs/npm_import.md
e2e/verify_patches/MODULE.bazel
e2e/verify_patches/README.md
e2e/verify_patches/WORKSPACE
e2e/verify_patches/patches/BUILD.bazel
e2e/verify_patches/patches/patches.list
e2e/verify_patches/test.sh
examples/npm_deps/patches/BUILD.bazel
examples/npm_deps/patches/patches
npm/BUILD.bazel
npm/extensions.bzl
npm/npm_import.bzl
npm/private/BUILD.bazel
npm/private/list_sources.bzl
npm/private/npm_translate_lock.bzl
npm/private/npm_translate_lock_helpers.bzl
npm/private/npm_translate_lock_state.bzl

This solves the problem where npm_translate_lock wouldn't invalidate when a patch was added to the patch folder.

feat: verify patches via a generated source file

---

js/private/node-patches/fs.js
js/private/node-patches/src/fs.ts

This allows inspecting the unsandboxed view of the file system if it's needed, such as for writing other sandbox guarding logic.

Set fs._unpatched when patching the 'node:fs' module

---

npm/private/npm_translate_lock_state.bzl

With this approach text files & binary files can follow the same code path

refactor: use rctx.download with file: URL to copy files in npm_translate_lock

---

.github/workflows/ci.yaml
e2e/git_dep_metadata/.bazeliskrc
e2e/git_dep_metadata/.bazelrc
e2e/git_dep_metadata/.bazelversion
e2e/git_dep_metadata/BUILD.bazel
e2e/git_dep_metadata/MODULE.bazel
e2e/git_dep_metadata/README.md
e2e/git_dep_metadata/WORKSPACE
e2e/git_dep_metadata/no_git_metadata_test.sh
npm/private/npm_import.bzl

An ssh keypair is required to clone via ssh. Secrets aren't accessible in GitHub actions on forks, so I had to move the test to an e2e that is exclusively run inside this repo.

fix: delete .git folder when downloading npm package from git

---

.github/workflows/ci.yaml

Currently, all matrix members use the same cache key for storing caches, preventing all matrix folders to upload their own caches and use the from the root folder all the time. this slows down all matrices except the root.

ci: make folder part of cache key

---

.aspect/workflows/config.yaml

Greens up the warming jobs for rules_js builds

fix: add missing 'warming' task

---

npm/extensions.bzl

Needed for a client.
This one doesn't have an e2e to exercise it. I could add one if you prefer, or we could just wait until `test //...` is ready to run under bzlmod and that should exercise it.

feat: add public_hoist_packages to bzlmod api

---

.github/workflows/new_issue_labels.yaml
.github/workflows/new_issue_project.yaml

Closes the loop so that new issues automatically show up on project board and don't fall through the cracks.
Follow-up later today will do the same for new PRs

chore: add new issues to Aspect OSS Bazel Rules project and label untriaged

---

README.md

It is fixed in the 1.9.0 release.
https://github.com/aspect-build/rules_js/releases/tag/v1.19.0 https://github.com/aspect-build/rules_js/pull/771

docs: remove "docker containers" from known issues

---

js/private/test/BUILD.bazel

Without this, on osx we get the diff_test error:
```
9c9
< export JS_BINARY__TARGET_CPU="linux_amd64"
---
> export JS_BINARY__TARGET_CPU="k8"
FAIL: files "js/private/test/shellcheck_launcher_sed.sh" and "js/private/test/shellcheck_launcher.sh" differ. 
```
This variable is the one case where we don't want to substitute `linux_amd64` for the `host.platform`.

fix: fix a unit test that fails on osx

---

.github/workflows/ci.yaml

This e2e was already converted but for some reason was added back to the ignore list.
Related: https://github.com/aspect-build/rules_js/issues/644

chore: run e2e/js_run_deverser on ci with bzlmod

---

js/private/image/index.ts
js/private/js_image_layer.mjs

This bug only surfaces on OSX. Can't reproduce on Linux.

fix: workaround ambiguous symlinks on osx

---

e2e/js_image_docker/test.sh
e2e/js_image_oci/test.sh
js/private/js_image_layer.bzl

Fixes https://github.com/aspect-build/rules_js/issues/902.
The runfiles tree doesn't need to exist, we just need the correct path to it.

fix: include runfiles tree in js_image_layer when --nobuild_runfile_links is set

---

MODULE.bazel
e2e/pnpm_workspace/MODULE.bazel
e2e/pnpm_workspace_deps/MODULE.bazel
e2e/pnpm_workspace_rerooted/MODULE.bazel
e2e/vendored_node/MODULE.bazel
js/repositories.bzl

Fixes https://github.com/aspect-build/rules_js/issues/864.
Node toolchain no longer needs to be explicitly registered unless using a different default version or registering a second copy.

chore: update to rules_nodejs 5.8.2

---

.bazelrc.common
.github/workflows/ci.yaml
BUILD.bazel
MODULE.bazel
docs/BUILD.bazel
docs/docs.bzl
e2e/pnpm_workspace_rerooted/MODULE.bazel
examples/js_library/two/BUILD.bazel
examples/macro/BUILD.bazel
js/dev_repositories.bzl
js/private/test/BUILD.bazel
js/private/test/expand_template/BUILD.bazel
js/private/test/expand_template/a_expected_bzlmod
js/private/test/expand_template/a_stamp_expected_bzlmod
js/private/test/image/structure/BUILD.bazel
js/private/test/image/symlink_tree.test.mjs
js/private/test/js_binary_sh/BUILD.bazel
npm/private/npm_translate_lock_generate.bzl
npm/private/test/BUILD.bazel

Fixes https://github.com/aspect-build/rules_js/issues/644
This should close off the bzlmod support for rules_js ticket.
Depends on: https://github.com/aspect-build/bazel-lib/pull/375

ci: build and run unit tests with bzlmod

---

.aspect/workflows/config.yaml

This option has been superseded by `bazel_debug_assistance` and defaults false.

chore: remove legacy Workflows option

---

README.md

Similar to bazel-contrib/rules-template#52

docs: include from-HEAD install

---

js/private/js_image_layer.bzl

fix(js_image_layer): use name to dedupe labels, not package

---

js/private/js_binary.bzl
js/private/js_binary.sh.tpl
js/private/test/shellcheck_launcher.sh

I often find launcher.sh files are the entry point to some failed command. When I inspect launcher.sh, it takes some digging to figure out what js_binary it corresponds to. Some additional comments at the top of the script will reduce this debug time.
Before:
#!/usr/bin/env bash
set -o pipefail -o errexit -o nounset
export JS_BINARY__BINDIR="bazel-out/k8-opt-exec-2B5CBBC6/bin"
export JS_BINARY__BUILD_FILE_PATH="BUILD.bazel"
export JS_BINARY__COMPILATION_MODE="opt"
export JS_BINARY__PACKAGE=""
After:
#!/usr/bin/env bash
#
#
set -o pipefail -o errexit -o nounset
export JS_BINARY__BINDIR="bazel-out/k8-opt-exec-2B5CBBC6/bin"
export JS_BINARY__BUILD_FILE_PATH="BUILD.bazel"
export JS_BINARY__COMPILATION_MODE="opt"
export JS_BINARY__PACKAGE=""

Make launcher.sh generated by js_binary more self-documenting.

---

js/private/coverage/coverage.sh.tpl
js/private/coverage/merger.bzl
js/private/js_binary.bzl
js/private/js_binary.sh.tpl
js/private/test/shellcheck_launcher.sh

This closes https://github.com/aspect-build/rules_js/issues/899 and it has all the context. Make the `_target_tool_short_path` path resolve when it’s in an external repo or repo-local.

fix: add support for local `node_toolchain`

---

npm/private/npm_translate_lock.bzl

```
~/p/vscode-ng-language-service  main *5  bazel run @//npm:sync                                                                    INT х  pgschwendtner@devversion  01:26:14 PM 
Starting local Bazel server and connecting to it...
ERROR: Skipping '@//npm:sync': no such package 'npm': BUILD file not found in any of the following directories. Add a BUILD file to a directory to mark it as a package.
- /usr/local/google/home/pgschwendtner/projects/vscode-ng-language-service/npm
WARNING: Target pattern parsing failed.
ERROR: no such package 'npm': BUILD file not found in any of the following directories. Add a BUILD file to a directory to mark it as a package.
- /usr/local/google/home/pgschwendtner/projects/vscode-ng-language-service/npm
INFO: Elapsed time: 11.058s
INFO: 0 processes.
FAILED: …
```

fix: invalid error when `translate_lock` action cache needs update

---

docs/README.md

These have been out-of-date for a little while

docs: fixup out-of-date docs on generated bzl_library targets within npm_translate_lock external repository

---

.github/workflows/ci.yaml

Less concerned with Bazel 5.1 regressions at this point with Bazel 6.1 out.

chore: remove Bazel 5.1.1 from CI matrix since to reduce CI queue times

---

js/private/js_binary.bzl
js/private/js_library.bzl

The need for this param was removed a long time ago in the bazel-lib copy action helpers so it is no longer bearing.
How has this been tested?

refactor: removed unused is_windows params

---

js/private/js_run_devserver.bzl
js/private/test/coverage/BUILD.bazel
js/private/test/create_launcher/custom_test.bzl

rules_js js_test base attributes that js_run_devserver uses requires setting `unresolved_symlinks_enabled` to True based on the `@aspect_rules_js//js/private:experimental_allow_unresolved_symlinks` condition to enable the optimized Bazel 6 patches only when the user is using Bazel 6 **AND** unresolved symlinks are enabled. They are enabled by default but they can be disabled by the user so we need to check anyway.
**Type of change**
**Test plan**

perf: use Bazel 6 optimized patches in js_run_devserver when --experimental_allow_unresolved_symlinks is set

---

docs/README.md

This seems to be a point of confusion sometimes 🤷

docs: add note of js_binary to npm binaries section

---

docs/faq.md

docs: add faq regarding the bazel output tree being readonly

---

js/private/js_run_binary.bzl

This came up on Bazel slack as a question from a new user.
**Type of change**
**Test plan**

chore: fail friendly if deps is passed to js_run_binary

---

e2e/js_run_devserver/multirun_test.sh
e2e/js_run_devserver/serve_test.sh
e2e/js_run_devserver/src/naughty.js
e2e/js_run_devserver/src/simple.js

I'm not sure if or what could have change but these devserver tests are failing frequently on CI atm, often >50% of the time, and we run them 4x (bzlmod x bazel 5/6).

fix: cleanup flaky devserver tests

---

docs/js_binary.md
js/private/js_binary.bzl

Fix #1019
All binary+test targets have an `args` but I don't see a way to document it. I think this is a stardoc issue and an issue should be created?

docs: add note documenting js_binary(args)

---

e2e/js_run_devserver/multirun_test.sh
e2e/js_run_devserver/serve_test.sh
e2e/js_run_devserver/src/BUILD.bazel
e2e/js_run_devserver/src/naughty.js
e2e/js_run_devserver/src/simple.js
e2e/js_run_devserver/test.sh

Ref #1025
Still not sure if it's perfect but it's still a lot better then before, and with more polling instead of waiting so it should at least be faster.

 test: poll for js_run_devserver changes instead of timeout, add logging

---

docs/js_binary.md
docs/js_run_binary.md
js/private/js_binary.bzl
js/private/js_run_binary.bzl

docs: add docs for the public js_binary env vars

---

MODULE.bazel
e2e/bzlmod/MODULE.bazel
e2e/js_image_oci/WORKSPACE
e2e/js_run_devserver/MODULE.bazel
e2e/npm_translate_lock/MODULE.bazel
e2e/npm_translate_lock_empty/MODULE.bazel
e2e/pnpm_workspace/MODULE.bazel
js/repositories.bzl

Reverts aspect-build/rules_js#1039
That version of bazel-lib had a breaking change in yq and was yanked.

Revert "chore(deps): update dependency aspect_bazel_lib to v1.31.0"

---

js/private/js_run_devserver.mjs

This resolves an issue in a complex Next.js devserver run downstream.
This fix is in the same spirit as running `js_binary` and `js_run_binary` targets from the output tree instead of the runfiles to prevent node being able to find libraries such as react in multiple node_modules trees. This applies the same principle to `js_run_devserver` by symlinks node_modules packages from the devserver custom sandbox to the output tree instead of the runfiles.
---
- Manual testing:
Ran the devserver in `e2e/webpack_devserver` manually.
Tested downstream with existing `js_run_devserver` targets that use Next.js and react-CRA in bazel-examples, https://github.com/aspect-build/bazel-examples/pull/212 as well as a very complex …

fix: when symlinking node_modules symlinks in js_run_devserer, prefer the bazel-out copy instead of the runfiles copy if it exists

---

docs/faq.md

Copying and pasting the starlark snippet resulted in a `no such file` error
---
Tested by copying the snippet into a WORKSPACE file

docs(pnpm_workspace): Fix code snippet

---

npm/private/test/parse_pnpm_lock_tests.bzl
npm/private/utils.bzl

Fix https://github.com/aspect-build/rules_js/issues/925

fix: support running pnpm on empty lockfile

---

npm/private/npm_translate_lock_state.bzl

For users of Phabricator (or other code review tools that respect this pattern) add a `@generated` to the top of the generated file so it can be collapsed during a PR/Diff review
---
- Suggested release notes are provided below:
action cache lock will now add a `@generated` banner to the file to mark it as "generated" for relevant code review tools.

Add `@generated` to npm_translate_lock_state.bzl action cache

---

MODULE.bazel

This was unintentionally bumped to 1.32.0 in https://github.com/aspect-build/rules_js/pull/1074 since that PR was initially depending on the new expand_template but that dep was removed before landing.
---

chore: reduce bzlmod min aspect_bazel_lib version back to 1.31.2

---

npm/private/npm_import.bzl

I had a hard to debug failure which was due to the fact that on my darwin machine I had gnutar on the $PATH as tar. Without the extra flag "--delay-directory-restore" I would get failures due to permission errors. This commit updates ensures we always add that flag if the version output of tar reports it is GNU tar.
Manually tested on my MacBook which has GNU tar on PATH as tar. Ran `bazel build //enterprise/cmd/frontend:frontend` on https://github.com/sourcegraph/sourcegraph. Before this PR it would fail.

fix: detect GNU tar on non-linux environments

---

.github/workflows/release_prep.sh

This is a strongly recommended default to prevent foot guns for new users. For example, https://bazelbuild.slack.com/archives/CEZUUKQ6P/p1685918918219999?thread_ts=1685915820.300699&cid=CEZUUKQ6P.
---
Next release should have this included in release snippet.

chore: add verify_node_modules_ignored to bzlmod release snippet

---

npm/private/npm_package_info.bzl
npm/private/npm_package_store.bzl
npm/private/npm_package_store_info.bzl

This is useful when you want to know where a linked package was originally copied from before the virtual store.
---

feat: add src_directory attribute to NpmPackageStoreInfo provider

---

e2e/bzlmod/MODULE.bazel
e2e/js_run_devserver/MODULE.bazel
e2e/js_run_devserver/pnpm-lock.yaml
e2e/npm_translate_lock/MODULE.bazel
e2e/npm_translate_lock_empty/MODULE.bazel
e2e/npm_translate_lock_partial_clone/MODULE.bazel
e2e/pnpm_workspace/MODULE.bazel
e2e/webpack_devserver/MODULE.bazel
e2e/webpack_devserver_esm/MODULE.bazel

CI is broken at HEAD due to rules_go 0.35.0 dep since it is yanked; 0.38.1 exists but it depends on a yanked gazelle version so bumping all the way to the latest 0.40.1.

chore: bump rules_go dep to 0.40.1 since 0.35.0 is yanked from BCR

---

e2e/bzlmod/BUILD.bazel
e2e/bzlmod/package.json
e2e/bzlmod/pnpm-lock.yaml
e2e/bzlmod/test.spec.js
js/private/js_binary.bzl

Work-around for https://github.com/aspect-build/rules_js/issues/1137.
Turns out fs patches are broken on Windows and they break transitive npm dependency resolution in runfiles.
This PR disables fs patches on Windows for now. They can be re-enabled once #1137 is fixed. There is no sandbox on Windows so the patches are less important.
This should resolve the BCR Windows CI failures for rules_jasmine & friends.
---
Added a `//:jasmine_test` to `e2e/bzlmod`. Jasmine has a transitive dep that will fail on Windows without the work-around:
```
Executing tests from //:jasmine_test
-----------------------------------------------------------------------------
node:internal/modules/cjs/loader:998
throw err;
^
Error: Cannot find module …
```

fix: disable fs patches on Windows

---

.github/workflows/ci.yaml

Windows & MacOS CI run on main branch only and only for `e2e/bzlmod` job for now. They will run on PRs if the branch name contains `windows` or `macos` respectively.
This PR also removes RBE CI from PRs to reduce the matrix size for PRs.
---
This PR will run the new CI matrix jobs

chore: add Windows and MacOS CI

---

MODULE.bazel
WORKSPACE
e2e/js_run_devserver/MODULE.bazel
npm/extensions.bzl
npm/private/pnpm_repository.bzl

This allows users to choose a version we haven't vendored integrity hashes for.
Fixes #1173
---
Seems like we are missing docgen for `pnpm_repository.bzl` - I'll add in a followup.
I changed the versions we use ourselves and tested that I can still run pnpm with/without bzlmod

feat: accept (version, integrity) for pnpm_version

---

js/BUILD.bazel
js/defs.bzl
js/private/BUILD.bazel
js/private/js_run_devserver.bzl
js/private/test/coverage/BUILD.bazel
js/private/test/create_launcher/custom_test.bzl
npm/private/npm_import.bzl
npm/private/npm_link_package.bzl
npm/private/npm_translate_lock_generate.bzl

rules_jest, rules_jasmine and others use the js_binary API which requires a select() that needs these config_settings.
So, they are broken by the (unreleased) #1178
See https://github.com/aspect-build/rules_jasmine/blob/049a30281525c0fd4819d2989515d47f6728f288/jasmine/defs.bzl#L71-L78
So, we should just make these public API so we know we cannot change them. Add two `alias` targets to make this change non-breaking.
---

fix(public api): expose two targets that downstream rulesets need

---

docs/npm_package.md
npm/BUILD.bazel
npm/private/npm_package.bzl

Tested in bazel-examples repo that by passing this flag, I can build an app that is downstream of a typecheck error, even though an npm_package is used to link the package.
This helps to solve https://github.com/aspect-build/rules_ts/issues/352 and makes rules_ts users less reliant on the Persistent Worker mode for performant dev round-trip.
- Relevant documentation has been updated
- Manual testing; instructions above

feat: introduce option to override npm_package#include_declarations

---

e2e/js_image_docker/BUILD.bazel
e2e/js_image_docker/package.json
e2e/js_image_docker/src/main.js

This PR creates a failing test case in order to reproduce an issue where bazel/docker can't resolve symlinks in pnpm node_modules.
Type of change
Red PR
Test plan
Covered by existing test cases

created failing bazel run for js_image_docker e2e test

---

npm/private/npm_translate_lock_generate.bzl

Needed to support https://github.com/aspect-build/rules_ts/issues/308
---
`bazel query @npm//:typescript/resolved.json` works and the content is what I expect

feat: expose pnpm lockfile content for tool version sync

---

.github/workflows/release_prep.sh

This is possible now that we ship our distribution artifact and calculate its hash, we aren't bound to produce something similar to GitHub's archive file.
---
- Covered by existing test cases - we have some testing of our distribution artifact in BCR. Otherwise this is risky since we've always assumed we ship the whole repo.
```
alexeagle@MacBook-Pro rules_js % ls -lh rjs.tgz
-rw-r--r--@ 1 alexeagle  staff   1.5M Aug 21 17:45 rjs.tgz
alexeagle@MacBook-Pro rules_js % rm .git/info/attributes 
alexeagle@MacBook-Pro rules_js % git archive --format=tar HEAD | gzip > rjs.tgz
alexeagle@MacBook-Pro rules_js % ls -lh rjs.tgz                                
-rw-r--r--@ 1 alexeagle  staff   2.1M Aug 21 17:48 rjs.tgz
```

fix: reduce distribution size by excluding e2e,examples

---

.aspect/workflows/README.md
.aspect/workflows/config.yaml
.aspect/workflows/terraform/.terraform.lock.hcl
.aspect/workflows/terraform/README.md
.aspect/workflows/terraform/main.tf
.aspect/workflows/terraform/vpc.tf
.aspect/workflows/terraform/workflows.tf
.gitignore

Enable new deployment of Aspect Workflows on GCP + Buildkite and land the terraform here so it serves as a live example of the full GCP + Buildkite Workflows configuration.

chore: add Aspect Workflows CI (on GCP + Buildkite)

---

.github/workflows/release_prep.sh

Fixes a copy-paste mistake, somehow between testing this and making the PR I used the wrong flag. Was distracted in the Vancouver office!
```
echo -n "e2e export-ignore\nexamples export-ignore" > .git/info/attributes
cat .git/info/attributes
e2e export-ignore\nexamples export-ignore
echo -e "e2e export-ignore\nexamples export-ignore" > .git/info/attributes
cat .git/info/attributes
e2e export-ignore
examples export-ignore
```

fix: make releases smaller

---

.aspect/workflows/terraform/workflows.tf

scaling_polling_frequency > 1 supported on GCP in 5.7.1 release

chore: update to Aspect Workflows 5.7.1

---

npm/private/test/yaml_tests.bzl
npm/private/yaml.bzl

See https://github.com/aspect-build/rules_js/issues/1279
Today, rules_js crashes when parsing invalid YAML, such as when there are git conflicts. If a developer uses the rules_js version of pnpm, it will crash when there are merge conflicts (because the repo rule parses the YAML?), unlike when using pnpm outside bazel.
Pnpm has some interesting [merge conflict parsing](https://github.com/pnpm/pnpm/blob/37fffbefa5a9136f2e189c01a5edf3c00ac48018/packages/supi/test/lockfile.ts#L1237). This change just outputs an error and prevents it from crashing.
---

fix: do not crash when parsing invalid yaml

---

docs/npm_import.md
npm/private/npm_import.bzl

See the reference just above, it has one more underscore.
Closes #1265

docs: fix the npm_import documentation to have the correct self-reference

---

.aspect/workflows/terraform/main.tf
.aspect/workflows/terraform/vpc.tf
.aspect/workflows/terraform/workflows.tf

Also switch to using local vars for the `project` and `region` instead of a global provider so we assert that the `project` and `region` passed to the Workflows module is routed to all GCP resources.

chore: upgrade to Aspect Workflows 5.8.0-rc9

---

npm/private/npm_import.bzl

Solves the problem flagged in: 
https://github.com/aspect-build/rules_js/pull/1226#issuecomment-1738259673

Do not pass --arch or --platform if none of the known platforms can be matched. 

---

npm/extensions.bzl
npm/private/npm_translate_lock.bzl
npm/private/npm_translate_lock_generate.bzl
npm/private/npm_translate_lock_helpers.bzl
npm/private/npm_translate_lock_state.bzl
npm/private/test/BUILD.bazel
npm/private/test/npm_auth_test.bzl
npm/private/test/translate_lock_helpers_tests.bzl

Have been meaning to clean this up for a while.
No code changes. Just moving functions around.
---

refactor: move npm_translate_lock helper functions to npm/private/npm_translate_lock_helpers.bzl

---

WORKSPACE
e2e/bzlmod/MODULE.bazel
js/private/js_image_layer.bzl
js/repositories.bzl
npm/private/npm_package.bzl

Note: users might still bring 1.x version of bazel-lib, and we permit that to the extent that it still works.

chore: bump bazel-lib to 2.0

---

.aspect/workflows/terraform/workflows.tf

Set new scale_out_factor to 10 which is equal to max_runners since Workflows will create more than 10 tasks per job

chore: upgrade to Aspect Workflows 5.8.2

---

js/private/coverage/merger.bzl
js/private/expand_template.bzl
js/private/js_binary.bzl
js/private/js_filegroup.bzl
js/private/js_run_devserver.bzl
npm/private/list_sources.bzl
npm/private/npm_link_package_store.bzl
npm/private/npm_package_internal.bzl
npm/private/npm_package_store.bzl

I found this annoying when viewing profiles in chrome and the only info is `Starlark user function call _impl`

refactor: provide specific names for rule implementations

---

.aspect/workflows/terraform/workflows.tf

Patch release that includes the `unique_writer_identity` flipping fix for GCP

chore: upgrade to Aspect Workflows 5.8.6

---

js/defs.bzl

---
In https://github.com/vgijssel/setup/pull/601 I tried using `js_binary` from within a macro called `release_manager` which was located in the rules_release workspace. The rules_release macro was called from the main workspace which resulted in the following error:
```
ERROR: Analysis of target '//:release_manager' failed; build aborted: no such package '@[unknown repo 'aspect_rules_js' requested from @]//js': The repository '@[unknown repo 'aspect_rules_js' requested from @]' could not be resolved: No repository visible as '@aspect_rules_js' from main repository
INFO: Elapsed time: 0.188s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets …
```

fix: Use js_binary in macro in external repository

---

.github/workflows/ci.yaml
e2e/npm_translate_lock_multi/MODULE.bazel
e2e/npm_translate_lock_subdir_patch/MODULE.bazel
e2e/npm_translate_package_lock/MODULE.bazel
e2e/npm_translate_yarn_lock/MODULE.bazel
e2e/package_json_module/MODULE.bazel
e2e/patch_from_repo/MODULE.bazel
e2e/pnpm_workspace_deps/MODULE.bazel
e2e/pnpm_workspace_rerooted/MODULE.bazel
e2e/update_pnpm_lock/MODULE.bazel
e2e/update_pnpm_lock_with_import/MODULE.bazel
e2e/vendored_node/MODULE.bazel
e2e/vendored_tarfile/MODULE.bazel
e2e/verify_patches/MODULE.bazel
e2e/webpack_devserver/MODULE.bazel
e2e/webpack_devserver_esm/MODULE.bazel

Apparently we weren't running the bzlmod/e2e matrix entries under bzlmod :flushed:. Many of the e2es need a direct dependency on bazel-lib because in their .bazelrc they import from the root workspace.
```
import %workspace%/../../.bazelrc.common
```
The root .bazelrc contains a reference to the `@aspect_bazel_lib//lib:flag_bzlmod` flag from bazel-lib.

fix: run e2es under bzlmod

---

.github/workflows/ci.yaml
.github/workflows/release_prep.sh
MODULE.bazel
e2e/bzlmod/MODULE.bazel
e2e/js_run_devserver/MODULE.bazel
e2e/npm_translate_lock/MODULE.bazel
e2e/npm_translate_lock_empty/MODULE.bazel
e2e/npm_translate_lock_partial_clone/MODULE.bazel
e2e/pnpm_workspace/MODULE.bazel
examples/js_library/two/BUILD.bazel
examples/macro/BUILD.bazel
js/private/js_binary.bzl
js/private/js_library.bzl
js/repositories.bzl

Support bazel-lib 1.x and 2.x. Please review the first commit only.
- Second commit (to be removed) tests against bazel-lib 1.x changes.

feat: import toolchains to use for copy actions

---

js/repositories.bzl

https://github.com/aspect-build/rules_js/pull/1311 reverted the rules_nodejs version back to 5.8.2. This drops support for Node.js v18.17.0. This PR re-reverts the rules_nodejs version to 5.8.4

Bump rules_nodejs back to 5.8.4

---

e2e/pnpm_workspace/MODULE.bazel
e2e/pnpm_workspace/WORKSPACE
e2e/pnpm_workspace_deps/MODULE.bazel
e2e/pnpm_workspace_deps/WORKSPACE

Switch two e2es to test against bazel-lib 2.x. The bzlmod e2e already tests against 2.x.
Closes #1363 

chore: test some e2es against bazel-lib 2.x

---

.github/workflows/ci.yaml
MODULE.bazel
e2e/js_run_devserver/MODULE.bazel
e2e/npm_translate_lock/MODULE.bazel
e2e/npm_translate_lock_empty/MODULE.bazel
e2e/npm_translate_lock_partial_clone/MODULE.bazel
e2e/stamped_package_json/.bazelignore
e2e/stamped_package_json/.bazelrc
e2e/stamped_package_json/.bazelversion
e2e/stamped_package_json/BUILD.bazel
e2e/stamped_package_json/MODULE.bazel
e2e/stamped_package_json/WORKSPACE
e2e/stamped_package_json/WORKSPACE.bzlmod
e2e/stamped_package_json/package.json
js/repositories.bzl
npm/private/BUILD.bazel
npm/private/npm_package.bzl

Fixes a breakage where stamping for this rule doesn't work under bazel-lib 2.x, which had some breaking changes when stamping using jq.
Closes https://github.com/aspect-build/rules_js/issues/1373

fix: support stamped_package_json stamping with bazel-lib 2.x

---

npm/private/test/transitive_closure_tests.bzl
npm/private/transitive_closure.bzl

refactor: reduce duplication in gather_transitive_closure util

---

npm/private/npm_translate_lock_helpers.bzl

The `_get_npm_imports` fails to account for the ports in URL, meaning it will not pass through auth if a port is specified. We work around this by checking the URL with and without ports
---
- Closes #1443 
- No breaking changes
- Create a yarn lock with a private registry (something like `@private`)
- Add a package with this registry with a port (like 443) in the download URL
- In the home npmrc, make sure that the registry has auth, and no port in the URL
- `rules_js` will now fail to download the package

Make sure that auth is respected, even if lockfiles have ports

---

MODULE.bazel
WORKSPACE
examples/npm_deps/patches/patches
examples/npm_deps/patches/test-a.patch
examples/npm_deps/patches/test-a@0.0.1.patch
examples/npm_deps/patches/test-b.patch
npm/private/test/repositories_checked.bzl

I think the e2e/verify-patches tests the exact same thing already so I don't think we also need these in the main workspace? They get quite annoying when doing testing in the repo so keeping them in e2e tests is a lot nicer.

test: move patch tests to e2e/verify-patches

---

npm/private/npm_translate_lock.bzl

When looking into the bzlmod pnpm-import issue it seems the import sometimes wasn't running at all which seemed to be from the `yarn.lock` not being in the `data`.
WDYT? Worth doing?

fix: include npm and yarn lock files in npm_translate_lock(data)

---

npm/private/transitive_closure.bzl

I come across a case where this property was not set. It looks like we treat it as optional in `npm/private/npm_translate_lock_helpers.bzl` so we should here as well. I have not investigated further why it might be null or if it was a lockfile issue vs rules_js issue, but we should treat it as optional consistently.
---

fix: accept pnpm pkg resolution without tarball

---

.github/workflows/ci.yaml
npm/private/npm_translate_lock.bzl

Exit with a message instead of crashing. Maybe we'll fix this in the future, maybe we'll completely remove the `reload_lockfile()` in v2?
---

fix: exit with message when pnpm-lock.yaml updated in bzlmod

---

e2e/webpack_devserver/.bazelignore
e2e/webpack_devserver/BUILD.bazel
e2e/webpack_devserver/mylib/BUILD.bazel
e2e/webpack_devserver/mylib/index.js
e2e/webpack_devserver/mylib/package.json
e2e/webpack_devserver/package.json
e2e/webpack_devserver/pnpm-lock.yaml
e2e/webpack_devserver/pnpm-workspace.yaml
e2e/webpack_devserver/serve_test.sh
e2e/webpack_devserver/src/index.js
e2e/webpack_devserver_esm/.bazelignore
e2e/webpack_devserver_esm/BUILD.bazel
e2e/webpack_devserver_esm/mylib/BUILD.bazel
e2e/webpack_devserver_esm/mylib/index.js
e2e/webpack_devserver_esm/mylib/package.json
e2e/webpack_devserver_esm/package.json
e2e/webpack_devserver_esm/pnpm-lock.yaml
e2e/webpack_devserver_esm/pnpm-workspace.yaml
e2e/webpack_devserver_esm/serve_test.sh
e2e/webpack_devserver_esm/src/index.js
js/private/js_run_devserver.bzl
js/private/js_run_devserver.mjs
js/private/test/js_run_devserver/BUILD.bazel
js/private/test/js_run_devserver/js_run_devserver.spec.mjs

Customer request to optimize js_run_devserver watch mode for first-party linked dependencies.
Adds special handling to copy 1p linked deps into the js_run_devserver custom sandbox instead of just symlinking the link symlink. We keep the symlinking the link symlink for 3p deps since coping those would add signifiant overhead for large graphs.
Adds further handling to checksum files before copying so even if their timestamps have changed the will not be copied if their contents have not. This is required since 1p linked deps under rules_js are directory artifacts so if any one file changes within the linked package then bazel re-creates the entire folder which makes any watchers think that all files have changed.
---
- New …

feat: add special handling to js_run_devserver for 1p deps to improve watch mode performance

---

npm/extensions.bzl
npm/private/npm_translate_lock_state.bzl
npm/private/test/parse_pnpm_lock_tests.bzl
npm/private/test/yaml_tests.bzl
npm/private/utils.bzl
npm/private/yaml.bzl

Today yaml errors cause failures in the util methods far too soon. The util methods now propagate the errors and are handled more appropriately such as only outputting a warning for lockfile errors if the lockfile is being updated.
---
- Relevant documentation has been updated

fix: only output warnings on lockfile parsing when regenerating lockfile

---

MODULE.bazel
WORKSPACE
js/private/test/node-patches/BUILD.bazel
js/private/test/node-patches_legacy/BUILD.bazel

I don't recall what originally prompted adding node v20 tests, but we probably should have basic node20 tests since it is LTS now.

test: add node20 toolchain tests

---

npm/private/npm_package_info.bzl
npm/private/npm_package_internal.bzl
npm/private/npm_package_store.bzl

Fixes https://github.com/aspect-build/rules_js/issues/1412.
---
I'm not entirely sure on the reason that this resolves #1412 but I have some loose theories listed below and I've tested it against a consistent and fast repro of the issue in https://github.com/bazelbuild/examples and found that the two consistent fixes are:
1. set `--modify_execution_info=CopyDirectory=+no-remote` on the build
2. don't use hardlink when copying the `/package` source directory in the `copy_directory_bin_action` inside `npm_package_store` (this PR)
Somehow a cache hit for an npm_package_store that has hardlinked files within a tree artifact to the `/package` directory of the external repository leads to the failure:
```
Copying directory npm__some_pkg__1.2.3/package failed: Exec failed due to IOException: …
```

fix: don't hardlink the /package source directory in npm_package_store

---

js/private/js_info.bzl

Just a bit of cleanup before I start the rules_js 2.0 branch

chore: cleanup JsInfo docstrings

---

MODULE.bazel
npm/extensions.bzl

This stops duplicating all the info from the pnpm lockfile into the Bazel one. Tested by upgrading to Bazel 7.1.1 and `bazel test --lockfile_mode=update //...`. Lockfile dropped from 79K lines to 4.4K.
There are still some gains to be had from python and go rules also using deterministic node, but that's outside the scope of this PR.

[bzlmod] Mark npm extension as reproducible

---

js/private/test/js_library_test.bzl
npm/private/npm_link_package_store.bzl

While working on the rules_js 2.0 branch where I thought I needed to make changes to the JsInfo provider to get this perf improvement, I realized that the source of the issue is that `npm_link_package_store` sets `declarations` and `transitive_declarations` which it does not need to set since linked npm packages are already in runfiles for runtime dependencies and ts_project doesn't need them in declarations.
The perf improvement here is that npm_package (when include_runfiles is set to False) will no longer get all npm packages in its manifest. In rules_js 2.0, npm_package include_runfiles can flip to False and this perf improvement will be the default case.
---
- Performance (a code change that improves performance)

perf: don't set JsInfo declarations and transitive_declarations in npm_link_package_store

---

npm/private/npm_import.bzl
npm/private/npm_translate_lock_helpers.bzl

refactor: remove aspect_rules_js.npm. repo-name logic

---

MODULE.bazel
e2e/bzlmod/MODULE.bazel
e2e/gyp_no_install_script/MODULE.bazel
e2e/gyp_no_install_script/WORKSPACE
e2e/js_run_devserver/MODULE.bazel
e2e/npm_translate_lock/MODULE.bazel
e2e/npm_translate_lock_auth/MODULE.bazel
e2e/npm_translate_lock_empty/MODULE.bazel
e2e/npm_translate_lock_git+ssh/MODULE.bazel
e2e/npm_translate_lock_multi/MODULE.bazel
e2e/npm_translate_lock_partial_clone/MODULE.bazel
e2e/npm_translate_lock_subdir_patch/MODULE.bazel
e2e/npm_translate_package_lock/MODULE.bazel
e2e/npm_translate_yarn_lock/MODULE.bazel
e2e/package_json_module/MODULE.bazel
e2e/patch_from_repo/MODULE.bazel
e2e/pnpm_workspace/MODULE.bazel
e2e/pnpm_workspace/WORKSPACE
e2e/pnpm_workspace_deps/MODULE.bazel
e2e/pnpm_workspace_deps/WORKSPACE
e2e/pnpm_workspace_rerooted/MODULE.bazel
e2e/stamped_package_json/MODULE.bazel
e2e/update_pnpm_lock/MODULE.bazel
e2e/update_pnpm_lock_with_import/MODULE.bazel
e2e/vendored_node/MODULE.bazel
e2e/vendored_tarfile/MODULE.bazel
e2e/verify_patches/MODULE.bazel
e2e/webpack_devserver/MODULE.bazel
e2e/webpack_devserver_esm/MODULE.bazel
js/repositories.bzl

bazel-lib 1.42.2 updates the bsdtar toolchain to use a pre-build binary that is linked against musl instead of glibc. this drops the system dep on glibc for the npm package extract action.
---

fix: bump minimum bazel-lib version to 1.42.2

---

js/private/coverage/merger.bzl
js/private/js_binary.bzl
npm/private/npm_translate_lock_helpers.bzl
npm/private/utils.bzl

Start of the rules_js 2.0 train stars with a few hoisted TODOs that are handled on the stack.

chore: hoist more TODOS to 2.0

---

npm/private/npm_import.bzl

This prevents npm_import from pulling data with the same integrity.
---
TBD
TL;DR: @joeljeske and I discovered a situation where the SHA mismatched on a url pull through and this needed to be added to fix 
https://docs.bazel.build/versions/3.0.0/repo/http.html#http_archive-canonical_id

fix: add cannonical_id to npm_import

---

docs/npm_import.md
npm/extensions.bzl
npm/private/npm_import.bzl

NB: `lifecycle_hooks_no_sandbox` still exists on `npm_translate_lock`. This changes only removes it from `npm_import` where it is deprecated.

refactor: remove deprecated lifecycle_hooks_no_sandbox from npm_import

---

npm/private/npm_import.bzl
npm/private/test/fsevents_links_defs_checked.bzl

Now that we have a minimum aspect_bazel_lib of 2.6.1 this attribute is always available on run_binary

refactor: always set use_default_shell_env on generated lifecycle hook js_run_binary

---

npm/extensions.bzl
npm/private/test/snapshots/bzlmod/unused_links_defs.bzl

This was missed when `package_visibility` support was added
---

fix: add package_visibility support to npm_translate_lock and npm_import on bzlmod

---

js/private/test/js_binary_sh/BUILD.bazel

This shows the difference in the env var between WORKSPACE and bzlmod.
---

chore: add a bzlmod variant of the js_binary_sh test for JS_BINARY__WORKSPACE

---

examples/genrule/BUILD.bazel
npm/private/npm_link_package_store.bzl
npm/private/npm_package_store.bzl
npm/private/utils.bzl

I've been waiting to make this optimization for a long time
BREAKING CHANGES:
If using npm packages with genrule, the default output of a target such as `//:node_modules/foo` is _only_ the link directory so if you will also need to add `//:node_modules/foo/dir` which is the virtual store directory to the genrule srcs.

perf: reduce size of npm_package_store transitive_files depset

---

e2e/worker/BUILD.bazel
e2e/worker/defs.bzl
examples/coverage/BUILD.bazel
examples/js_binary/BUILD.bazel
js/private/coverage/merger.bzl
js/private/js_binary.bzl
js/private/js_image_layer.bzl
js/private/test/image/checksum.expected
js/private/test/image/custom_owner_app.listing
js/private/test/image/default_app.listing

fix: drop .sh extension from js_binary, merger and js_image_layer launchers

---

npm/private/test/BUILD.bazel

Unintentionally commented out in #1590: https://github.com/aspect-build/rules_js/pull/1590/files#r1550785682.

chore: restore test that was commented out unintentionally

---

MODULE.bazel
WORKSPACE
e2e/pnpm_repo_install/MODULE.bazel
e2e/pnpm_workspace/MODULE.bazel
e2e/pnpm_workspace_rerooted/MODULE.bazel
e2e/vendored_node/MODULE.bazel
e2e/worker/MODULE.bazel

Does not bump the minimum version of rules_nodejs for rules_js 1.x. That will come soon with rules_js 2.0.

chore: test against latest rules_nodejs release 6.1.0 to ensure backward compat that release with rules_js 1.x

---

js/private/coverage/merger.bzl
js/private/js_binary.bzl

rules_nodejs 6.1.0 toolchain exports canonical and more ergonomic File objects instead of paths. This change supports those new attributes while keeping backward compat for older versions of rules_nodejs. In the future, after some sufficient grace period, support for the older less ergonomic attributes can be dropped.
---

feat: support rules_nodejs improved toolchain attributes in rules_nodejs 6.1.0 with backward compat for older versions

---

.aspect/workflows/config.yaml

Latest 5.10 alpha version of Workflows running on rules_js has fixes to the rebase stategy.

chore: enable branch_freshsness rebase strategy

---

js/libs.bzl
js/private/js_helpers.bzl
js/private/js_info_files.bzl
js/private/js_run_devserver.bzl
js/private/test/create_launcher/custom_test.bzl

`gather_files_from_js_info` is more descriptive since the function only gathers files from JsInfo and not from other providers

refactor: renamed gather_files_from_js_providers to gather_files_from_js_info

---

npm/private/npm_translate_lock_state.bzl

When no `pnpm_lock` attribute is set the `patched_dependencies` never gets initialized. This fix just sets a default initial value for `patched_dependencies`, essentially the exact same as `importers` which has a default and is only overridden if a `pnpm_lock` is set.
I'm also dropping the `lockfile_is_loaded = "importers" in priv` since `importers` is set 100% of the time. The alternative (for `importers` and `patched_dependencies`) is to set the initial value to `None` and change how this works a bit. WDYT?
The only way I can reproduce this is having an e2e test with no `pnpm-lock.yaml`, then running the test updates the lockfile in the root of the repo. I'm not sure if that's it's own bug?
- Verified manually

fix: set default internal npm_translate_lock state

---

.bcr/presubmit.yml

Currently broken in the BCR tho we have coverage for Windows on rules_js itself.
Failures on BCR running bsdtar.exe
```
(15:23:57) ERROR: C:/b/bk-windows-jcc1/bazel-org-repo-root/output/rules_js-1.41.0/e2e/bzlmod/BUILD.bazel:14:22: Extracting npm package semver@5.7.1 failed: (Exit -1073741515): bsdtar.exe failed: error executing command (from target //:.aspect_rules_js/node_modules/semver@5.7.1/pkg)
cd /d C:/b/fcl55ko6/execroot/_main
external\aspect_bazel_lib~2.6.1~toolchains~bsd_tar_windows_amd64\libarchive\bin\bsdtar.exe --extract --no-same-owner --no-same-permissions --strip-components 1 --file external/aspect_rules_js~override~npm~npm__semver__5.7.1/package.tgz --directory bazel-out/x64_windows-fastbuild/bin/node_modules/.aspect_rules_js/semver@5.7.1/node_modules/semver
``` …

chore: disable windows tests on BCR pre-submit

---

npm/private/npm_link_package_store.bzl
npm/private/npm_package_store.bzl
npm/private/utils.bzl

Pre-factor from https://github.com/aspect-build/rules_js/pull/1646 where a make_symlink function that takes a path and not a File is needed.

chore: tweak make_symlink util to take a path instead of a File

---

.aspect/rules/external_repository_action_cache/npm_translate_lock_LTE4Nzc1MDcwNjU=
examples/npm_package/packages/pkg_a/package.json
examples/npm_package/packages/pkg_b/BUILD.bazel
examples/npm_package/packages/pkg_b/README.md
examples/npm_package/packages/pkg_b/package.json
js/private/js_library.bzl
npm/private/test/snapshots/bzlmod/npm_defs.bzl
npm/private/test/snapshots/bzlmod/repositories.bzl
npm/private/test/snapshots/wksp/npm_defs.bzl
npm/private/test/snapshots/wksp/repositories.bzl
pnpm-lock.yaml

Update `examples/npm_package/packages/pkg_b` to use `:node_modules` for transitive deps instead of explicitly stating the deps. Gather `npm_package_store_deps` from `srcs`, which this PR fixes, is needed for that to work.
Update `examples/npm_package/packages/pkg_a` to show that in some cases, peer deps of 1p deps are handled correctly in rules_js. In other cases such as peer deps on other 1p deps they are not (https://github.com/aspect-build/rules_js/issues/1092).
---

fix: also gather npm_package_store_deps from srcs in js_library

---

js/private/js_image_layer.bzl

Usually, application's `node_modules` don't change often, as a application `code`, so I suggest to provide "strong" default: `[node_modules, app]`
Suggested release notes are provided below:
Make the `node_modules` layer the first in the `js_image_layer` rule, as the `node_module` don't change often.

fix: change order of node_modules and app in `js_image_layer`

---

js/private/js_helpers.bzl
npm/private/npm_package_store.bzl

This was a bad pattern to pull from NpmPackageStoreInfo in the helper. Instead npm_package_store should just put its transitive files closure in DefaultInfo runfiles and also provide a JsInfo for when it is used directly in a js_run_binary or other js rules.

refactor: don't gather files from NpmPackageStoreInfo providers in gather_files_from_js_info

---

npm/private/test/parse_pnpm_lock_tests.bzl
npm/private/utils.bzl

refactor: remove references to pnpm-lock specifiers field

---

e2e/pnpm_lockfiles/lockfile-test.bzl
e2e/pnpm_lockfiles/package.json
e2e/pnpm_lockfiles/setup.sh
e2e/pnpm_lockfiles/v53/pnpm-lock.yaml
e2e/pnpm_lockfiles/v54/pnpm-lock.yaml
e2e/pnpm_lockfiles/v60/pnpm-lock.yaml
e2e/pnpm_lockfiles/v61/pnpm-lock.yaml

Removing `sharp` which doesn't seem to add any test cases not covered by others.
Adding `rollup` which contains an `optionalDependencies` to demonstrate the `optionalDependencies` key within the `packages`.

test: update e2e/pnpm_lockfiles setup to update existing lockfiles

---

js/libs.bzl
js/private/js_helpers.bzl
js/private/js_info_files.bzl
js/private/js_run_devserver.bzl
js/private/test/create_launcher/custom_test.bzl

Very much a nit but since the function was renamed already may as well get the naming right before the 2.x release.

refactor: rename gather_files_from_js_info to gather_files_from_js_infos

---

.aspect/workflows/config.yaml

`branch_freshness` is now `checkout`
non-default workspaces no longer inherit root tasks by default

chore: update workflows config

---

MODULE.bazel
e2e/bzlmod/MODULE.bazel
e2e/gyp_no_install_script/MODULE.bazel
e2e/gyp_no_install_script/WORKSPACE
e2e/js_run_devserver/MODULE.bazel
e2e/npm_translate_lock/MODULE.bazel
e2e/npm_translate_lock_auth/MODULE.bazel
e2e/npm_translate_lock_empty/MODULE.bazel
e2e/npm_translate_lock_git+ssh/MODULE.bazel
e2e/npm_translate_lock_multi/MODULE.bazel
e2e/npm_translate_lock_partial_clone/MODULE.bazel
e2e/npm_translate_lock_subdir_patch/MODULE.bazel
e2e/npm_translate_package_lock/MODULE.bazel
e2e/npm_translate_yarn_lock/MODULE.bazel
e2e/package_json_module/MODULE.bazel
e2e/pnpm_workspace/MODULE.bazel
e2e/pnpm_workspace_deps/MODULE.bazel
e2e/pnpm_workspace_deps/WORKSPACE
e2e/pnpm_workspace_rerooted/MODULE.bazel
e2e/stamped_package_json/MODULE.bazel
e2e/update_pnpm_lock/MODULE.bazel
e2e/update_pnpm_lock_with_import/MODULE.bazel
e2e/vendored_node/MODULE.bazel
e2e/vendored_tarfile/MODULE.bazel
e2e/verify_patches/MODULE.bazel
e2e/webpack_devserver/MODULE.bazel
e2e/webpack_devserver_esm/MODULE.bazel
e2e/worker/MODULE.bazel
js/repositories.bzl

Fixes #1597
Also bumps bazel-lib 2.x usage to 2.7.1 which includes the same bsdtar fix.
---

chore: bump minimum bazel-lib version to 1.42.3

---

.github/workflows/ci.bazelrc
.github/workflows/ci.yaml

--test_tag_filters are not additive so in order to set multiple tag filters from matrix settings we need to do some on the CLI

chore: set --test_tag_filters on cli and not via bazelrc

---

.aspect/workflows/bazelrc

`--remote_download_minimal` is an alias for `--remote_download_outputs=minimal`: https://bazel.build/reference/command-line-reference#flag--remote_download_minimal

chore: use canonical --remote_download_outputs=minimal flag for BwoB

---

.aspect/workflows/config.yaml
.bazelrc
workspace_status.sh

Show a simple example of setting both `--stamp` and `--workspace_status_command` in Workflows `delivery.stamp_flags`

chore: tweak delivery stamping

---

js/private/js_binary.sh.tpl
js/private/js_run_binary.bzl
js/private/js_run_devserver.mjs
js/private/test/image/checksum.expected
js/private/test/image/custom_owner_app.listing
js/private/test/image/default_app.listing
js/private/test/shellcheck_launcher.sh

Internal attribute that is poorly named

refactor: rename JS_RUN_BINARY__USE_EXECROOT_ENTRY_POINT to JS_BINARY__USE_EXECROOT_ENTRY_POINT

---

npm/extensions.bzl

Align bzlmod and workspace default values.
- Manual testing; removing `patch_args = [...]` from tests such as `e2e/npm_translate_lock_subdir_patch` should fail the same with bzlmod and workspace.

fix: align bzlmod and workspace patch_args default

---

e2e/pnpm_workspace/WORKSPACE
e2e/pnpm_workspace_deps/WORKSPACE

When you upgraded to 2.7.1 `aspect_bazel_lib` was removed as a direct dep of these so we shouldn't be invoking `aspect_bazel_lib_dependencies` anymore.
This is a `!fixup` on that commit, assuming we'll rebase/squash and `push -f` at some point still?

fixup! refactor: set minimum aspect_bazel_lib to 2.7.1 (#1580)

---

.bazelrc

`--incompatible_strict_action_env1` is already set in `import %workspace%/.aspect/bazelrc/correctness.bazelrc`

chore: remove redundant bazelrc flag

---

.github/workflows/ci.yaml
docs/README.md
e2e/update_pnpm_lock/test.sh
e2e/update_pnpm_lock_with_import/test.sh
npm/private/npm_translate_lock.bzl
npm/private/npm_translate_lock_state.bzl

Reloading isn't supported with bzlmod so we should not support it with non-bzlmod just to make things consistent.
Close https://github.com/aspect-build/rules_js/issues/1445
---
- Breaking change (forces users to change their own code or config): yes
When `npm_translate_lock(update_pnpm_lock)` updates the lockfile it will exit with a non-0 exit code and must be rerun with the updated lockfile.

refactor: remove support for reloading lockfile on update

---

docs/js_image_layer.md
e2e/js_image_docker/BUILD.bazel
e2e/js_image_docker/smoketest.yaml
e2e/js_image_oci/WORKSPACE
e2e/js_image_oci/src/BUILD.bazel
e2e/js_image_oci/src/test.yaml
js/private/js_image_layer.bzl

Non-breaking 1.x pre-factor from 2.x change https://github.com/aspect-build/rules_js/pull/1690.
With this change, the executable output path of js_binary can change without affecting the runfiles directory of js_image_layer: https://github.com/aspect-build/rules_js/pull/1690/commits/d4c87b2c500697322a4d85bf350da9a2853eb803

refactor: cleanup js_image_layer impl and docs

---

e2e/worker/BUILD.bazel
e2e/worker/defs.bzl
examples/coverage/BUILD.bazel
js/private/coverage/merger.bzl
js/private/js_binary.bzl
js/private/test/image/checksum.expected
js/private/test/image/custom_owner_app.listing
js/private/test/image/default_app.listing

Follow-up to #1586.
The trouble with the change in #1586 with the name of the executable in the output tree the same as the target name is that a target name such as `test` could be in a BUILD file where a subdirectory named test exists which can lead to build failures such as:
```
ERROR: One of the output paths 'bazel-out/k8-fastbuild/bin/foo/test' (belonging to //foo:test) and 'bazel-out/k8-fastbuild/bin/foo/test/active_file_users_test.ts' (belonging to //foo:foo) is a prefix of the other. These actions cannot be simultaneously present; please rename one of the output files or build just one of them
```
This change resolves that issue without bringing back the `.sh` suffix that #1586 was addressing.

refactor: update js_binary executable path to {name}_/{name}

---

MODULE.bazel
WORKSPACE
examples/npm_deps/patched-dependencies-test.js
examples/npm_deps/patches/meaning-of-life@1.0.0-after_pnpm.patch
examples/npm_deps/patches/patches
npm/private/npm_translate_lock_helpers.bzl
npm/private/test/snapshots/wksp/repositories.bzl

Fix #1427
An alternative to #837 or #1693. This removes the option of mixing `pnpm.patchedDependencies` + `npm_translate_lock(patches, patch_args)` on a single package and instead providing simple defaults to patch args when using `pnpm.patchedDependencies`.
---
- Breaking change (forces users to change their own code or config): yes
Patches from both `pnpm.patchedDependencies` and `npm_translate_lock(patches)` can no longer be applied to the same npm package.

fix: do not support mixing pnpm.patchedDependencies and npm_translate_lock(patches)

---

.github/workflows/ci.yaml
e2e/npm_translate_lock_auth/test.sh

This e2e test was disabled on bzlmod from a while ago when we didn't have support for `use_home_npmrc` in the bzlmod extension. It should be run now.

ci: run e2e/npm_translate_lock_auth with bzlmod on CI

---

docs/js_image_layer.md
e2e/js_image_docker/BUILD.bazel
js/private/js_image_layer.bzl

Useful for when using js_image_layer with rules_docker in consistent manner for all images regardless of which layers are empty:
```
RULES_JS_LAYERS = [
"node",
"package_store_3p",
"package_store_1p",
"node_modules",
"app",
]
def js_container_layers(name, binary, root, tags = []):
js_image_layer(
name = "{}/layers".format(name),
binary = binary,
generate_empty_layers = True,
root = root,
visibility = ["//visibility:__pkg__"],
)
[
[
native.filegroup(
name = "{}/layers/{}.tar".format(name, layer),
srcs = ["{}/layers".format(name)],
output_group = layer,
),
container_layer(
name = "{}/{}_layer".format(name, layer),
tars = [":{}/layers/{}.tar".format(name, layer)],
tags = tags + ["manual"],
),
]
for layer in RULES_JS_LAYERS
]
```
with `generate_empty_layers = False` the above example may fail …

feat: add generate_empty_layers attribute to js_image_layer

---

npm/private/npm_translate_lock_state.bzl

Why load them different when running pnpm update? That makes it inconsistent, ~~especially with lockfile v5.3 where the lockfile vs package.json will give different results~~ (edit: but we no longer support 5.3).
Unlike other `pnpm.*` properties from the package.json this one does end up in the lockfile with additional metadata, so we will always read it from the lockfile and not package.json.
---

refactor: always read pnpm.patchedDependencies from lockfile

---

npm/extensions.bzl
npm/private/npm_translate_lock.bzl
npm/private/npm_translate_lock_state.bzl

This way common logic such as parsing `pnpm.*` from the package.json can live in the `npm_translate_lock_state.bzl` util.
---

refactor: reuse npm_translate_lock_state parse logic in bzlmod

---

npm/private/npm_translate_lock_state.bzl

This code path wasn't run on the previous PR CI.
---

refactor: fix npm_translate_lock(npmrc) setup

---

js/dev_repositories.bzl

bzlmod is already on 6.4.0. This puts WORKSPACE in alignment.

chore: bump to buildifier 6.4.0

---

e2e/pnpm_lockfiles/.bazelignore
e2e/pnpm_lockfiles/MODULE.bazel
e2e/pnpm_lockfiles/WORKSPACE
e2e/pnpm_lockfiles/base/package.json
e2e/pnpm_lockfiles/setup.sh
e2e/pnpm_lockfiles/v90/BUILD.bazel
e2e/pnpm_lockfiles/v90/package.json
e2e/pnpm_lockfiles/v90/patches
e2e/pnpm_lockfiles/v90/pnpm-lock.yaml
npm/private/npm_translate_lock_helpers.bzl
npm/private/test/utils_tests.bzl
npm/private/transitive_closure.bzl
npm/private/utils.bzl

With the lockfile `requiresBuild` flag removed (https://github.com/pnpm/pnpm/issues/7707) lifecycle hooks must now be manually specified using [pnpm.onlyBuiltDependencies](https://pnpm.io/package_json#pnpmonlybuiltdependencies).
---

feat: support pnpm lock v9

---

npm/extensions.bzl

Fixes https://github.com/aspect-build/rules_js/issues/1479
Thanks to @hunshcn for pointing on the fix in https://github.com/aspect-build/rules_js/pull/1716.

fix(bzlmod): npm_translate_lock should read registry from npmrc

---

MODULE.bazel

We have dropped support for Bazel 5 in rules_js 2

refactor: set bazel_compatibility for bzlmod to >=6.0.0

---

e2e/pnpm_lockfiles/lockfile-test.bzl
npm/private/test/snapshots/bzlmod/npm_defs.bzl
npm/private/test/snapshots/bzlmod/repositories.bzl
npm/private/test/snapshots/wksp/npm_defs.bzl
npm/private/test/snapshots/wksp/repositories.bzl
npm/private/utils.bzl

Lockfile v5 had `1.2.3_hash` where v6+ has `1.2.3_(patch_hash=1.2.3)`. In 2.x we can add the extra test case that is broken in lockfile v5.3 (which we dropped in 2.x).
---

refactor: align pnpm lock v6+ with v5 target names

---

npm/private/npm_translate_lock.bzl
npm/private/npm_translate_lock_helpers.bzl
npm/private/npm_translate_lock_state.bzl
npm/private/test/parse_pnpm_lock_tests.bzl
npm/private/utils.bzl

To ensure users always set `onlyBuildDependencies` for pnpm 9+ where we can not automatically detect lifecycle events from only the lockfile.
---

fix: fail lockfile translation for pnpm pnpm v9+ when no onlyBuildDependencies specified

---

npm/extensions.bzl
npm/private/npm_translate_lock_helpers.bzl
npm/private/transitive_closure.bzl
npm/private/utils.bzl

Some of these were useful when debugging pnpm 9, some name changes just for consistency, one WARNING for a case that I think is a bug today.
---

refactor: detect and log duplicate package keys

---

e2e/pnpm_lockfiles/README.md
e2e/pnpm_lockfiles/base/package.json
e2e/pnpm_lockfiles/lockfile-test.bzl
e2e/pnpm_lockfiles/v54/pnpm-lock.yaml
e2e/pnpm_lockfiles/v54/snapshots/defs.bzl
e2e/pnpm_lockfiles/v60/pnpm-lock.yaml
e2e/pnpm_lockfiles/v60/snapshots/defs.bzl
e2e/pnpm_lockfiles/v61/pnpm-lock.yaml
e2e/pnpm_lockfiles/v61/snapshots/defs.bzl
e2e/pnpm_lockfiles/v90/pnpm-lock.yaml
e2e/pnpm_lockfiles/v90/snapshots/defs.bzl
npm/private/test/parse_pnpm_lock_tests.bzl
npm/private/test/snapshots/wksp/repositories.bzl
npm/private/test/transitive_closure_tests.bzl
npm/private/test/utils_tests.bzl
npm/private/transitive_closure.bzl
npm/private/utils.bzl

This way the data is standardized to a format for rules_js at parse time instead of elsewhere throughout the code.
Today the lockfile parsing normalizes to a version similar to pnpm lock v5, then `_gather_package_info` normalizes that a bit to a more rules_js specific format. The idea of this PR is to directly convert to that rules_js format as part of parsing, instead of `pnpm vX => pnpm v5 => rules_js` (where X = 5,6,9) we will have `pnpm vX => rules_js` and ideally have less code...
---

refactor: normalize pnpm lockfile data in parser

---

docs/npm_package.md
npm/private/npm_package.bzl
npm/private/test/npm_package/BUILD.bazel

Since npm packages are no longer included in type in rules_js 2.0, adding the option `include_npm_sources` covers the use case where users want to include `node_modules` folders in their `npm_package`
- Added new test case

feat: add include_npm_sources to npm_package

---

docs/faq.md

The cause is now (very likely) understood and fixed in Bazel.
---

docs: update section on "Exec failed due to IOException"

---

examples/genrule/BUILD.bazel
npm/private/npm_link_package_store.bzl
npm/private/test/npm_package/BUILD.bazel

Having a dangling symlink as the default output of `:node_modules/foo` `npm_link_package_store` targets breaks genrules that worked in rules_js 1.0 since they needed to also depend on `:node_modules/foo`. This change fixes that use case.
It also resolves an `npm_package` bug where if a `:node_modules/foo` was included in sources, the underlying copy_to_directory action would fail to resolve the realpath of the dangling symlink and fail. This bug was reported in RELEASE 2.0 tracking issue: https://github.com/aspect-build/rules_js/issues/1671#issuecomment-2111386386. The issue was due to `:node_modules/foo` targets only having the symlink to package store in their default output and not the package store itself. This caused copy_to_directory to fail to follow the symlink since the package …

fix: include package store directory in default output of npm_link_package_store

---

MODULE.bazel
e2e/bzlmod/MODULE.bazel
e2e/gyp_no_install_script/MODULE.bazel
e2e/js_image_oci/MODULE.bazel
e2e/js_run_devserver/MODULE.bazel
e2e/npm_translate_lock/MODULE.bazel
e2e/npm_translate_lock_empty/MODULE.bazel
e2e/pnpm_lockfiles/MODULE.bazel
e2e/pnpm_workspace/MODULE.bazel
e2e/repo_mapping/MODULE.bazel
e2e/stamped_package_json/MODULE.bazel
e2e/webpack_devserver/MODULE.bazel
e2e/webpack_devserver_esm/MODULE.bazel
e2e/worker/MODULE.bazel
js/repositories.bzl

Pick up fix for copy_to_directory that affects npm_package: https://github.com/aspect-build/bazel-lib/pull/857.
---
CI

chore: bump minimum aspect_bazel_lib to 2.7.7

---

e2e/pnpm_lockfiles/README.md
e2e/pnpm_lockfiles/base/package.json
e2e/pnpm_lockfiles/lockfile-test.bzl
e2e/pnpm_lockfiles/v54/pnpm-lock.yaml
e2e/pnpm_lockfiles/v54/snapshots/defs.bzl
e2e/pnpm_lockfiles/v60/pnpm-lock.yaml
e2e/pnpm_lockfiles/v60/snapshots/defs.bzl
e2e/pnpm_lockfiles/v61/pnpm-lock.yaml
e2e/pnpm_lockfiles/v61/snapshots/defs.bzl
e2e/pnpm_lockfiles/v90/pnpm-lock.yaml
e2e/pnpm_lockfiles/v90/snapshots/defs.bzl
npm/private/utils.bzl

It's possible this bug has existed with lockfile v5 for quite some time, although I'm not certain.
--

fix(pnpm): support npm: alias dependencies with pnpm lockfile v5

---

e2e/pnpm_lockfiles/lockfile-test.bzl
e2e/pnpm_lockfiles/v90/snapshots/defs.bzl
npm/private/npm_translate_lock_helpers.bzl
npm/private/transitive_closure.bzl
npm/private/utils.bzl

fix(pnpm): npm aliases to url specifiers 

---

npm/private/npm_import.bzl
npm/private/npm_translate_lock_generate.bzl
npm/private/test/utils_tests.bzl
npm/private/transitive_closure.bzl
npm/private/utils.bzl

This intermediate "pnpm package key" state isn't needed outside the parse logic.
---

refactor(pnpm): remove .parse_pnpm_package_key util

---

e2e/pnpm_lockfiles/MODULE.bazel
e2e/pnpm_lockfiles/README.md
e2e/pnpm_lockfiles/WORKSPACE
e2e/pnpm_lockfiles/cases/BUILD.bazel
e2e/pnpm_lockfiles/cases/docusaurus-direct-peer-v6.yaml
e2e/pnpm_lockfiles/cases/docusaurus-direct-peer-v9.yaml
npm/private/utils.bzl

Transitive `npm:` deps that contain peers were not being escaped.
---

fix(pnpm): pnpm9 npm: dependencies with peers

---

npm/BUILD.bazel

This alias was added for backward compat for the `--@aspect_rules_js//npm:exclude_declarations_from_npm_packages` config flag, which was renamed to `--@aspect_rules_js//npm:exclude_types_from_npm_packages` but it turns out that aliases don't work for config flags so the alias is non-functional:
```
ERROR: @aspect_rules_js//npm:exclude_declarations_from_npm_packages :: Unrecognized option: @aspect_rules_js//npm:exclude_declarations_from_npm_packages
```
---

refactor: remote non-functional exclude_declarations_from_npm_packages alias

---

.github/workflows/release_prep.sh
MODULE.bazel
e2e/js_image_oci/MODULE.bazel
e2e/js_image_oci/WORKSPACE
e2e/pnpm_lockfiles/MODULE.bazel
e2e/pnpm_repo_install/MODULE.bazel
e2e/pnpm_workspace/MODULE.bazel
e2e/pnpm_workspace_rerooted/MODULE.bazel
e2e/vendored_node/MODULE.bazel
e2e/worker/MODULE.bazel
js/repositories.bzl

Fixes https://github.com/aspect-build/rules_js/issues/1530 by bringing in the rules_nodejs fix https://github.com/bazelbuild/rules_nodejs/pull/3750 which was released with rules_nodejs [v6.1.2](https://github.com/bazelbuild/rules_nodejs/releases/tag/v6.1.2).
---
Minimum Aspect bazel-lib version is now 6.1.2
On darwin, where the issue #1530 occurs, ran `bazel test //src:image_test` and confirmed it currently fails on `main` and passes with this fix.
Without fix:
```
--- FAIL
duration: 180.569083ms
stderr: …
```

fix: fix issue with bzlmod toolchain registration by bumping minimum rules_nodejs to 6.1.2

---

.bazelrc

```
try-import %workspace%/.aspect/bazelrc/user.bazelrc
```
is the established pattern for our rule sets where we have the bazel-lib presets in place
__plus__
Don’t want to push a rules author to update their deps if not needed.
https://bazel.build/reference/command-line-reference#flag--check_direct_dependencies
https://bazelbuild.slack.com/archives/C014RARENH0/p1691158021917459?thread_ts=1691156601.420349&cid=C014RARENH0
Setting this flag in our the rule sets we maintain.

chore: fixup pattern for try-import of user.bazelrc

---

js/private/js_helpers.bzl

This shouldn't be needed in both `runfiles(files)` + `runfiles(transitive_files)`
---

perf: do not put files_runfiles in files + transitive_files

---

js/private/js_helpers.bzl

Avoids looping over the data when it will be a noop anyway.
---

perf: avoid cloning data_files when not copy_data_files_to_bin

---

js/private/js_info.bzl

If we're using default params then there's no reason to do `type(p)` to validate them.
---

perf: avoid js_info param validation on default values

---

.github/workflows/release_prep.sh
MODULE.bazel
e2e/js_image_oci/MODULE.bazel
e2e/pnpm_lockfiles/MODULE.bazel
e2e/pnpm_repo_install/MODULE.bazel
e2e/pnpm_workspace/MODULE.bazel
e2e/pnpm_workspace_rerooted/MODULE.bazel
e2e/vendored_node/MODULE.bazel
e2e/worker/MODULE.bazel
js/repositories.bzl

Ensures users pick up https://github.com/bazelbuild/rules_nodejs/pull/3760 fix which is a footgun that should be avoided.

chore: bump minimum rules_nodejs to 6.2.0

---

npm/private/npm_translate_lock.bzl
npm/private/utils.bzl

This saves around .5s analysis time in our repo, extracted from https://github.com/aspect-build/rules_js/pull/1797

perf: minimize cost of checking bazel version

---

npm/private/npm_package_store.bzl

Existing calls to `paths.join` can be done more quickly.
Before:
After:
---

[perf] Optimize npm_package_store

---

js/private/js_helpers.bzl
js/private/js_library.bzl
npm/private/npm_package.bzl

If we state that all these attributes are "required" on `JsInfo` and we enforce that in the `js_info` factory then we can avoid checking if the attributes are present everywhere we access them.
See alternative: https://github.com/aspect-build/rules_js/pull/1791
---

perf: do not check JsInfo hasattr for always-set attributes

---

js/private/js_info.bzl

This also puts all deprecated logic into one `if` that can be dropped in v3.
---

perf: only validate deprecated js_info params when extra params specified

---

.aspect/rules/external_repository_action_cache/npm_translate_lock_LTE4Nzc1MDcwNjU=
e2e/gyp_no_install_script/.aspect/rules/external_repository_action_cache/npm_translate_lock_LTE4Nzc1MDcwNjU=
e2e/npm_translate_lock/.aspect/rules/external_repository_action_cache/npm_translate_lock_LTE4Nzc1MDcwNjU=
e2e/npm_translate_lock_auth/.aspect/rules/external_repository_action_cache/npm_translate_lock_LTE4Nzc1MDcwNjU=
e2e/npm_translate_lock_empty/.aspect/rules/external_repository_action_cache/npm_translate_lock_LTE4Nzc1MDcwNjU=
e2e/npm_translate_lock_git+ssh/.aspect/rules/external_repository_action_cache/npm_translate_lock_LTE4Nzc1MDcwNjU=
e2e/npm_translate_package_lock/.aspect/rules/external_repository_action_cache/npm_translate_lock_LTE4Nzc1MDcwNjU=
e2e/npm_translate_yarn_lock/.aspect/rules/external_repository_action_cache/npm_translate_lock_LTE4Nzc1MDcwNjU=
e2e/pnpm_workspace/.aspect/rules/external_repository_action_cache/npm_translate_lock_LTE4Nzc1MDcwNjU=
e2e/pnpm_workspace_deps/.aspect/rules/external_repository_action_cache/npm_translate_lock_LTE4Nzc1MDcwNjU=
e2e/pnpm_workspace_rerooted/.aspect/rules/external_repository_action_cache/npm_translate_lock_LTE1MzU4OTk=
e2e/pnpm_workspace_rerooted/.aspect/rules/external_repository_action_cache/npm_translate_lock_MzAwMTUzNTg5OQ==
e2e/update_pnpm_lock_with_import/.aspect/rules/external_repository_action_cache/npm_translate_lock_LTE4Nzc1MDcwNjU=
e2e/verify_patches/.aspect/rules/external_repository_action_cache/npm_translate_lock_LTE4Nzc1MDcwNjU=
npm/private/npm_translate_lock_state.bzl

`dict.items` has no guaranteed order, even if it did I assume the items are added in a non-guaranteed order.
This sorts the elements to ensure the order listed in the action cache is consistent which will minimize diffs when updated.
---

refactor: sort lock translation action cache content

---

js/private/js_helpers.bzl

perf: do not include sources,types when transitive_sources,type already included

---

npm/private/npm_import.bzl
npm/private/npm_link_package_store.bzl
npm/private/npm_translate_lock_generate.bzl

In most scenarios we don't need all the logic detecting empty segments or detecting absolute paths in individual parts.
---

perf: reduce use of bazel_skylib paths.join

---

npm/extensions.bzl
npm/private/npm_translate_lock.bzl
npm/private/npm_translate_lock_helpers.bzl

These are processed differently in bzlmod in extensions.bzl where the bzlmod invocation of `npm_import` is done.
See what is no longer unnecessarily duplicated in bzlmod: https://github.com/aspect-build/rules_js/blob/b6e94d3d1b09c34cbdb70e1515f1a147b3b0fa9a/npm/private/npm_translate_lock.bzl#L512-L562
---

perf: do not double process lifecycle_hooks* attributes in bzlmod

---

js/private/js_binary.bzl
js/private/js_helpers.bzl
js/private/js_library.bzl
npm/private/npm_package.bzl

In almost all use cases these are lists, or for `gather_runfiles` always depsets. rules_ts seems to follow this pattern already
---

perf: change js_helpers gather_* utils to accept list, not depset

---

npm/private/pnpm.bzl
npm/private/test/parse_pnpm_lock_tests.bzl

This is unused. I believe any peer dep data has been resolved into `dependencies` already.
---

refactor: remove unused peer_dependencies field

---

js/private/dev_deps.bzl

This reverts the aspect_rules_lint upgrade from commit df5ef9e218f3a5548c37a1177a3cf685139ce642.
---

Revert "chore(deps): update aspect rulesets (#1631)"

---

npm/private/npm_package_store.bzl

Minor cleanup changes:
* aligning the 3 branches (`NpmPackageInfo` vs `JsInfo` vs `not ctx.attr.src`)
* reduce repeated access to providers
* do not pre-declare potentially unused computations 
---

refactor: cleanup npm_package_store.bzl

---

npm/private/npm_package.bzl

When the `publishable` attribute was added, the default was already `False`, so there is no TODO to DO

chore: remove stray TODO

---

e2e/pnpm_lockfiles/base/package.json
e2e/pnpm_lockfiles/v54/pnpm-lock.yaml
e2e/pnpm_lockfiles/v60/pnpm-lock.yaml
e2e/pnpm_lockfiles/v61/pnpm-lock.yaml
e2e/pnpm_lockfiles/v90/pnpm-lock.yaml
npm/private/pnpm.bzl

When a specifier uses `npm:` to reference itself the resolved version is just the raw version, where normally `npm:` specifiers result in `actual-pkg@version`.
Fix https://github.com/aspect-build/rules_js/issues/1843
---

fix(pnpm): npm: aliases to self

---

e2e/pnpm_lockfiles/lockfile-test.bzl
e2e/pnpm_lockfiles/v54/snapshots/is-odd_resolved.json
e2e/pnpm_lockfiles/v60/snapshots/is-odd_resolved.json
e2e/pnpm_lockfiles/v61/snapshots/is-odd_resolved.json
e2e/pnpm_lockfiles/v90/snapshots/is-odd_resolved.json
npm/private/npm_translate_lock_generate.bzl

The generated `@npm//v61/BUILD.bazel` had:
```
export_files(["v61/is-odd/resolved.json"])
```
Which should not have the `v61/` because this is the `v61/BUILD`. The majority of use cases the lockfile is in the root and we don't see this problem.
---

fix(npm): invalid export of package/resolved.json

---

e2e/pnpm_lockfiles/base/aliases-test.js
e2e/pnpm_lockfiles/base/package.json
e2e/pnpm_lockfiles/lockfile-test.bzl
e2e/pnpm_lockfiles/v54/pnpm-lock.yaml
e2e/pnpm_lockfiles/v54/snapshots/defs.bzl
e2e/pnpm_lockfiles/v60/pnpm-lock.yaml
e2e/pnpm_lockfiles/v60/snapshots/defs.bzl
e2e/pnpm_lockfiles/v61/pnpm-lock.yaml
e2e/pnpm_lockfiles/v61/snapshots/defs.bzl
e2e/pnpm_lockfiles/v90/pnpm-lock.yaml
e2e/pnpm_lockfiles/v90/snapshots/defs.bzl

I saw an alias such as `foo/bar` somewhere and there are probably some edge cases here to fix or watch for bugs when refactoring. This just adds tests ensuring it doesn't crash.
---

test(npm): add tests for odd package names

---

e2e/gyp_no_install_script/snapshots/bzlmod/segfault-handler_defs.bzl
e2e/gyp_no_install_script/snapshots/wksp/segfault-handler_defs.bzl
e2e/pnpm_lockfiles/v54/snapshots/defs.bzl
e2e/pnpm_lockfiles/v54/snapshots/rollup_links_defs.bzl
e2e/pnpm_lockfiles/v60/snapshots/defs.bzl
e2e/pnpm_lockfiles/v60/snapshots/rollup_links_defs.bzl
e2e/pnpm_lockfiles/v61/snapshots/defs.bzl
e2e/pnpm_lockfiles/v61/snapshots/rollup_links_defs.bzl
e2e/pnpm_lockfiles/v90/snapshots/defs.bzl
e2e/pnpm_lockfiles/v90/snapshots/rollup_links_defs.bzl
npm/private/npm_import.bzl
npm/private/npm_translate_lock_generate.bzl
npm/private/test/snapshots/bzlmod/chalk_links_defs.bzl
npm/private/test/snapshots/bzlmod/fsevents_links_defs.bzl
npm/private/test/snapshots/bzlmod/npm_defs.bzl
npm/private/test/snapshots/bzlmod/rollup_links_defs.bzl
npm/private/test/snapshots/bzlmod/unused_links_defs.bzl
npm/private/test/snapshots/wksp/chalk_links_defs.bzl
npm/private/test/snapshots/wksp/fsevents_links_defs.bzl
npm/private/test/snapshots/wksp/npm_defs.bzl
npm/private/test/snapshots/wksp/rollup_links_defs.bzl
npm/private/test/snapshots/wksp/unused_links_defs.bzl
npm/private/utils.bzl

perf(npm): reduce use of string.split

---

e2e/pnpm_lockfiles/v54/snapshots/defs.bzl
e2e/pnpm_lockfiles/v60/snapshots/defs.bzl
e2e/pnpm_lockfiles/v61/snapshots/defs.bzl
e2e/pnpm_lockfiles/v90/snapshots/defs.bzl
npm/private/npm_import.bzl
npm/private/npm_translate_lock_generate.bzl
npm/private/test/snapshots/bzlmod/npm_defs.bzl
npm/private/test/snapshots/wksp/npm_defs.bzl

perf(npm): reduce array concatenation

---

examples/linked_consumer/BUILD.bazel
examples/linked_lib/BUILD.bazel
examples/linked_lib/one.d.ts
examples/linked_lib/one.js
npm/private/npm_link_package_store.bzl
npm/private/npm_package_store.bzl

The `NpmPackageStoreInfo` `files` and `transitive_files` now only contain the files/symlinks required to put the package into the store. All sources + types are only in the `JsInfo` which was already passed around throughout these targets but now must be read in addition to the `NpmPackageStoreInfo`.
Close #1847
---
- New test cases added, see rules_ts: https://github.com/aspect-build/rules_ts/pull/651

fix: do not put sources+types into NpmPackageStoreInfo.files

---

e2e/webpack_devserver/.bazelignore
e2e/webpack_devserver/mylib/BUILD.bazel
e2e/webpack_devserver/mypkg/BUILD.bazel
e2e/webpack_devserver/mypkg/index.js
e2e/webpack_devserver/mypkg/package.json
e2e/webpack_devserver/package.json
e2e/webpack_devserver/pnpm-lock.yaml
e2e/webpack_devserver/pnpm-workspace.yaml
e2e/webpack_devserver/serve_test.sh
e2e/webpack_devserver/src/index.js
e2e/webpack_devserver_esm/.bazelignore
e2e/webpack_devserver_esm/mylib/BUILD.bazel
e2e/webpack_devserver_esm/mypkg/BUILD.bazel
e2e/webpack_devserver_esm/mypkg/index.js
e2e/webpack_devserver_esm/mypkg/package.json
e2e/webpack_devserver_esm/package.json
e2e/webpack_devserver_esm/pnpm-lock.yaml
e2e/webpack_devserver_esm/pnpm-workspace.yaml
e2e/webpack_devserver_esm/serve_test.sh
e2e/webpack_devserver_esm/src/index.js
js/private/js_run_devserver.mjs
js/private/test/js_run_devserver/js_run_devserver.spec.mjs

Fixes syncing of 1p js_library (JsInfo) linked deps in js_run_devserver.
The code was already handling detecting of 1p deps in the transitive 1p dep case. To handle js_library 1p deps we only needed to ensure that the 1p directory that the symlink in the package store was pointing to is copied first for the dep to be detected as 1p.
---
e2e/webpack_devserver & e2e/webpack_devserver_esm test cases updated to include js_library linked 1p deps and verified manually that the sync works as expected:
```
Starting js_run_devserver //:dev
+ Syncing 18 files && folders...
+ Syncing 6 non-node_modules files & folders...
Syncing file package.json (347 B)
Syncing file webpack.config.js (554 B)
Syncing file mylib/package.json (83 B)
Syncing file src/index.js (448 B)
Syncing file mylib/index.js (144 B) …
```

fix: handle js_library 1p deps correctly in js_run_devserver

---

e2e/webpack_devserver/BUILD.bazel
e2e/webpack_devserver/serve_test.sh
e2e/webpack_devserver/src/404.html
e2e/webpack_devserver_esm/BUILD.bazel
e2e/webpack_devserver_esm/serve_test.sh
e2e/webpack_devserver_esm/src/404.html
js/private/js_run_devserver.mjs

`js_run_devserver` is aware of all of the files to sync per sync so it is easy enough to delete files that are no longer synced out of the custom sandbox on each sync.
Run `ibazel run //:dev` in `e2e/webpack_devserver` and manually delete a synced file such as `src/404.html`. Expected output is:
```
Deleting src/404.html
1 file/folder deleted in 1 ms
+ Syncing 18 files && folders...
+ Syncing 6 non-node_modules files & folders...
Skipping file mylib/index.js since its timestamp has not changed
Skipping file mylib/package.json since its timestamp has not changed
Skipping file package.json since its timestamp has not changed
Skipping file src/index.html since its timestamp has not changed …
```

fix: delete old files & folders on each js_run_devserver sync

---

e2e/bzlmod/BUILD.bazel
e2e/bzlmod/MODULE.bazel
e2e/bzlmod/other_module/.bazelignore
e2e/bzlmod/other_module/.npmrc
e2e/bzlmod/other_module/BUILD.bazel
e2e/bzlmod/other_module/MODULE.bazel
e2e/bzlmod/other_module/WORKSPACE
e2e/bzlmod/other_module/package.json
e2e/bzlmod/other_module/pnpm-lock.yaml
e2e/pnpm_lockfiles/v54/snapshots/rollup3_package_json.bzl
e2e/pnpm_lockfiles/v54/snapshots/rollup_package_json.bzl
e2e/pnpm_lockfiles/v60/snapshots/rollup3_package_json.bzl
e2e/pnpm_lockfiles/v60/snapshots/rollup_package_json.bzl
e2e/pnpm_lockfiles/v61/snapshots/rollup3_package_json.bzl
e2e/pnpm_lockfiles/v61/snapshots/rollup_package_json.bzl
e2e/pnpm_lockfiles/v90/snapshots/rollup3_package_json.bzl
e2e/pnpm_lockfiles/v90/snapshots/rollup_package_json.bzl
npm/extensions.bzl
npm/private/test/snapshots/bzlmod/package_json.bzl
npm/private/test/snapshots/bzlmod/package_json_with_dashes.bzl

This prevents an error such as the following when trying to run a `js_binary` defined in another module with Bzlmod:
```
ERROR: .../external/rules_pyright~/BUILD:6:23: no such package '@@[unknown repo 'rules_pyright~' requested from @@rules_pyright~]//': The repository '@@[unknown repo 'rules_pyright~' requested from @@rules_pyright~]' could not be resolved: No repository visible as '@rules_pyright~' from repository '@@rules_pyright~' and referenced by '@@rules_pyright~//:pyright__entry_point'
```
---
Fixed an issue when using `js_binary` from another module with Bzlmod.

Use canonical repo name for cross-repo `npm_translate_lock`

---

README.md
docs/README.md
docs/migrate_2.md

- Add a migration guide, adapted from #1671
- Add eslint in a few spots so it's more likely users discover it
- Promote Aspect Workflows for CI/CD
---
Docs only

chore: docs updates for 2.0

---

npm/private/npm_package_store.bzl

It seems buildbarn can be configured such that it protects the output directory of an action from being touched. This changes the chmod in `npm_package_store` to act on the contents of the output directory instead of on the directory itself.
See https://bazelbuild.slack.com/archives/CEZUUKQ6P/p1723821643734399 more context.

fix: fix permission denied failure on buildbarn RBE

---

MODULE.bazel
npm/private/npm_package_store.bzl

Addresses https://github.com/aspect-build/rules_js/issues/1637 (the original issue that brought in `chmod -R a+X *` as the fix). See Bazel Slack thread https://bazelbuild.slack.com/archives/CEZUUKQ6P/p1723821643734399 for more context.
- Breaking change (forces users to change their own code or config): for some users yes but unavoidable as this is fixing a blocking bug
Backing out of the blanket chmod after npm package tarball extract since it can lead to exceeding MAX_ARGS on the command with the glob expansion in npm packages with a very large number of files.
Instead, users should opt-in packages such as `pngjs@5.0.0` that have malformed tarball content file permissions and …

fix: remove problematic chmod extract command in npm_package_store in favor of using a custom postinstall

---

npm/private/npm_package_store.bzl

Now that the [chmod command was removed](https://github.com/aspect-build/rules_js/commit/4f5ef8c92e30ac8d5760900fc7bc1435cf60df76) the bazel action can be a single bazel action.
---

perf(npm): use actions.run instead of actions.run_shell

---

js/private/js_helpers.bzl

Avoid doing the same `+` operations multiple times and use `+=` instead of `.extends` to avoid the starlark method invocation.
---

perf: avoid large array concatenation

---

docs/README.md

When this attribute is not set in the call to `npm_translate_lock`, the queries return no results, the `package_json.bzl` file is not directly findable, and users may be very confused.
---
Manually confirmed the queries work after setting this setting but not before.
See also https://bazelbuild.slack.com/archives/CEZUUKQ6P/p1724827171385349 .

doc: add callout for dependency on generate_bzl_library_targets

---

e2e/bzlmod/MODULE.bazel
npm/private/npm_translate_lock_helpers.bzl

Also add a missing Bzlmod dependency that otherwise fails the example with `--noenable_workspace`.
---
```
bazel build //examples/... --incompatible_use_plus_in_repo_names
```

Add support for `+` in canonical repo names

---

docs/npm_package.md
npm/private/npm_package.bzl

This fact is already mentioned further down in the docs, but this commit makes it more apparent when only scanning the summary.
The default value for `publishable` was changed in https://github.com/aspect-build/rules_js/pull/1683.

docs: Clarify that $npm_package.publish requires publishable = True

---

npm/extensions.bzl
npm/private/pnpm_extension.bzl
npm/private/test/BUILD.bazel
npm/private/test/pnpm_test.bzl

Fixes #1907.
---
- Suggested release notes appear below: no

feat(pnpm): allow `latest` as version to get the latest version

---

docs/migrate_2.md

This is maybe a bit less technically correct, but less confusing: I only saw the first line first and renamed to the intermediate name first.

docs: merge gather_files_from_js_infos rename PRs in migration docs

---

npm/private/npm_translate_lock_helpers.bzl

Packages referencing files such as tarballs or URLs should support patches, lifecycle hooks etc. It is only file: references to directories that should not.
---

fix(npm): support patches, lifecycle hooks for non-directory file: packages

---

.aspect/bazelrc/BUILD.bazel

`main` is currently failing with non-bzlmod due to workspace and bzlmod resolving to different versions
---

build: disable aspect_bazelrc_presets tests in non-bzlmod

---

.aspect/bazelrc/convenience.bazelrc
.aspect/bazelrc/correctness.bazelrc
.github/workflows/bazel7.bazelrc
MODULE.bazel
js/private/test/js_binary_sh/BUILD.bazel

This is to include https://github.com/bazel-contrib/bazel-lib/commit/73d021fb368c67be40ae204a62cfa789e14515a7 which fixed a bug in `run_binary` and therefore `js_run_binary`.
Currently the rules_js WORKSPACE deps have this fix but bzlmod does not. This change upgrades the minimum bazel-lib version to include this fix.
The updated assertions align with running node outside bazel on the cli:
```
> echo 'console.log(`${process.argv[2]} + ${process.argv[3]}`)' | node - --x='3' '4'
--x=3 + 4
```
The stdout has no quotes despite the arguments being quoted. The tests updated in this change show rules_js now does the same.
---

fix: upgrade bazel-lib to include run_binary param parsing fix

---

.github/workflows/ci.yaml
e2e/runfiles/WORKSPACE
e2e/runfiles/WORKSPACE.bzlmod
examples/runfiles/BUILD.bazel

See https://github.com/bazel-contrib/rules_nodejs/issues/3797
---

build: do not run e2e/runfiles on non-bzlmod

---

.github/workflows/ci.yaml

This seems to have been an accident and disabled all bazel6 testing by default.
---

chore: enable bazel6 ci tests

---

npm/private/npm_translate_lock_generate.bzl

This seems significantly clearer to me that this is not an array meant to have values appended to it.
---

refactor(npm): replace truthy value in set with True

---

.github/workflows/ci.yaml
MODULE.bazel
WORKSPACE
docs/BUILD.bazel
docs/docs.bzl
docs/js_binary.md
docs/js_image_layer.md
docs/js_info_files.md
docs/js_library.md
docs/js_run_binary.md
docs/js_run_devserver.md
docs/npm_import.md
docs/npm_link_all_packages.md
docs/npm_link_package.md
docs/npm_package.md
docs/npm_translate_lock.md
e2e/pnpm_lockfiles/lockfile-test.bzl
js/private/dev_deps.bzl
js/private/test/BUILD.bazel
js/private/test/image/BUILD.bazel

build: only run bazel 6 unit tests with bzlmod

---

docs/js_run_devserver.md
js/private/js_run_devserver.bzl

This is quite important and should be documented better.
See https://github.com/bazelbuild/bazel-watcher/issues/100
---

docs(js_run_devserver): add note about ibazel issue 100

---

js/private/js_run_devserver.mjs

I think this removes the possibility of processing multiple build events in parallel.
---

fix(js_run_devserver): ensure files are synced before waiting for next build event

---

npm/private/npm_translate_lock_state.bzl

I have no idea if this will have any side-effects or fixes, but my ide highlighted that the args were wrong 😨 
---

fix(npm): add missing patch copy action key

---

npm/private/pnpm.bzl

This has been useful debugging and I think should always be done. For now it outputs errors to stdout, maybe we can change that to `fail` if/when we are more confident.
---

refactor(npm): add validation of parsed pnpm-lock data

---

.github/workflows/ci.yaml

We updated `.bazelversion` but not CI.
---

chore: update ci to bazel 7.4

---

js/private/js_run_devserver.mjs

See individual commits. Primarily changing async fs operations to be run in parallel instead of sequentially.
---

perf(js_run_devserver): run fs delete operations in parallel

---

js/private/js_image_layer.bzl

Fixes #1973 based on https://bazelbuild.slack.com/archives/C014RARENH0/p1734404555241159.

fix: include `_repo_mapping` in runfiles dir

---

e2e/bzlmod/MODULE.bazel

To include the bazel-lib windows fixes: https://github.com/bazel-contrib/bazel-lib/commit/d042d563c6a91f7e11f66c42c83429199bd3d5d9
---

test: override bazel-lib in e2e/bzlmod to include windows fix

---

e2e/pnpm_lockfiles/MODULE.bazel
e2e/pnpm_lockfiles/README.md
e2e/pnpm_lockfiles/WORKSPACE
e2e/pnpm_lockfiles/cases/BUILD.bazel
e2e/pnpm_lockfiles/cases/patches/aspect-test-e-pnpm.patch
e2e/pnpm_lockfiles/cases/versionless-patch-v9.yaml
e2e/pnpm_lockfiles/cases/versionless-patch.spec.js
npm/private/npm_translate_lock_helpers.bzl

Fix #2031
---
PNPM v9.7+ supports `pnpm.patchedDependencies` specifiers with no version specified.

fix(npm): support pnpm v9.7+ patches without version specifier

---

e2e/npm_translate_lock_disable_hooks/snapshots/defs.bzl
e2e/npm_translate_lock_replace_packages/snapshots/bzlmod/npm_defs.bzl
e2e/npm_translate_lock_replace_packages/snapshots/wksp/npm_defs.bzl
e2e/pnpm_lockfiles/v54/snapshots/defs.bzl
e2e/pnpm_lockfiles/v60/snapshots/defs.bzl
e2e/pnpm_lockfiles/v61/snapshots/defs.bzl
e2e/pnpm_lockfiles/v90/snapshots/defs.bzl
npm/private/npm_translate_lock_generate.bzl
npm/private/test/snapshots/bzlmod/npm_defs.bzl
npm/private/test/snapshots/wksp/npm_defs.bzl

Was there any reason these were not relative? In all cases we are already checking if we are in the `native.package_name()` so I think this can all be relative.
---

refactor: reduce runtime string format calls, use local target paths

---

npm/private/npm_translate_lock_helpers.bzl
npm/private/pnpm.bzl
npm/private/test/parse_pnpm_lock_tests.bzl

Fix the usage of the lockfile `dev` flag, rename vars where possible to better indicate the meaning.
---
- Manual testing; please provide instructions so we can reproduce: https://github.com/jbedard/rules_js/commit/cf3f12a7194e62b8194afa596fc0213b23df7bd8 and toggling `npm_translate_lock` `dev` and `prod` flags.

fix(npm): correct use of pnpm lockfile dev flag

---

npm/private/pnpm.bzl

To clarify differences between lockfiles as well as differences between lockfiles and this struct which is normalized across lockfile versions as much as possible.

chore: add comments/docs for pnpm lockfile fields

---

npm/private/npm_translate_lock.bzl

Used: https://github.com/aspect-build/rules_js/issues/2070 as reproduction steps
Create e package.json with atleast one package with a strict version.
Add Bazel build with update_pnpm_lock set to False
Run Bazel build
Change the version of the package
Run bazel query for this package similar to: `bazel query "filter('is-odd', kind(npm_package, //...))" --output=build`
Expected: New version to be observed
Real: Older version is observed
After fix real: New version is observed

fix(npm): use bazel 8 rctx.watch for pnpm-lock

---

npm/private/npm_package_store.bzl

Based on feedback from users, we have to set this specific env variable for bsdtar or every invocation prints
```
INFO: From Extracting npm package @opentelemetry/sdk-metrics@1.27.0_at_opentelemetry_api_1.4.1:
tar: Failed to set default locale
```
---

refactor: fix locale spam from tar

---

js/private/js_binary.bzl
js/private/js_helpers.bzl
js/private/js_image_layer.bzl
npm/extensions.bzl
npm/private/npm_link_package_store.bzl
npm/private/npm_package_store.bzl
npm/private/npm_translate_lock_state.bzl
npm/private/repository_label_store.bzl

According to the documentation, Label.workspace_name is deprecated:
https://bazel.build/rules/lib/builtins/Label.html#workspace_name
Label.repo_name behaves identically and is available in Bazel 6 and later.

Use Label.repo_name instead of Label.workspace_name

---

docs/pnpm.md
npm/private/npm_translate_lock_helpers.bzl

Our longstanding bug https://github.com/bazelbuild/bazel/issues/7093 was fixed!
---
Docs only.
I did try this out in an example repo and see Bazel 8 does what's expected.

refactor(bazel 8): point out ignore_directories function

---

npm/private/versions.bzl

There may still be lockfile issues (see #2101) but those may be edge cases and we can add v10 to `versions.bzl` since pnpm v8 is still the default.
---
Add pnpm v10 

chore: mirror external pnpm v10 releases

---

MODULE.bazel
e2e/js_run_devserver/MODULE.bazel
e2e/js_run_devserver/WORKSPACE
e2e/webpack_devserver/MODULE.bazel
e2e/webpack_devserver/WORKSPACE
e2e/webpack_devserver_esm/MODULE.bazel
e2e/webpack_devserver_esm/WORKSPACE

I don't know why this was here? The e2e rules_docker test specifies it's there to fix a rules_docker bug so I left it there.
---

chore: remove unused rules_go dev dep

---

js/private/js_run_devserver.mjs

Without this change, it is theoretically possible for the `IBAZEL_*` messages to be combined in to one chunk, or have one message be split across other chunks. This would cause the `.includes` checks to either fail to see a message, or only see one message when in reality both were present.
This is somewhat difficult to test as it depends on timing. It does seem to reliably happen when the devserver is first starting up and receives a bunch of messages quickly as it hasn't processed any of them yet.

devserver: use readline instead of reading from raw stdin

---

docs/README.md

The previous approach does not seem stable .
It was working with initial tests but now it's not, and I'd hate for someone to encounter this sort of snag based on my contribution.
Here's the type of error I was seeing
```
RR_PNPM_WORKSPACE_PKG_NOT_FOUND  In ../../../../../../../../external/aspect_rules_js+/js/private/test/image: "@mycorp/pkg-a@workspace:*" is in the dependencies but no package named "@mycorp/pkg-a" is present in the workspace
```
This happens if you add anything like - `'./**/*'` , `- '**'` , or `- '*'`  to workspace packages. It doesn't seem to matter if you have `- !..` , it still tries to look there.
So this new approach is to manually add project dirs and their subfolders. Easy enough.
```
- 'experimental/**'
- 'users/**'
- 'some_deeply_nested_project/**'
```

Update pnpm workspace example in docs to avoid edge cases

---

.aspect/bazelrc/correctness.bazelrc
.aspect/bazelrc/performance.bazelrc
.github/workflows/bazel6.bazelrc
.github/workflows/bazel7.bazelrc
MODULE.bazel
js/repositories.bzl
npm/private/npm_package_store.bzl

Updates the minimum version of bazel-lib. Users who don't update will see #2044 effectively reverted.
Fixes #2114

fix: extract tar with correct environment

---

e2e/js_run_devserver/.bazelrc

Related to: https://github.com/bazelbuild/bazel/issues/6627
Test was broken by a performance optimization: https://github.com/aspect-build/rules_js/commit/5522ff8c4bd970598497dcfc98363899e91b36e0#diff-7e21af0f988e602e8c7f2058dbed8d5e92b044c8d833e3795bb7a8c84a13425aR15
Proposed fix is to stop the optimization for this test.
---

[chore] fix CI test, disable performance optimization for js_run_devserver e2e test

---

docs/npm_import.md
npm/private/npm_import.bzl

Added bzlmod example to npm_import docs
This was created as I was working on: https://github.com/aspect-build/rules_js/pull/2125 and it took me some time to find the proper way for using npm_import in `MODULE.bazel`.

Improve npm_import docs to include example also for bzlmod

---

.gitignore

Just a developer improvement if the rules_js dev is using the new idea Bazel plugin: https://plugins.jetbrains.com/plugin/22977-bazel-eap-
This plugin creates this folder for keeping the project view. I think it should be ignored as it is specific to the used IDE of the rules_js dev.

Add new idea bazel plugin folder to gitignore

---

npm/private/npm_translate_lock_generate.bzl
npm/private/npm_translate_lock_helpers.bzl
npm/private/test/translate_lock_helpers_tests.bzl

- Searched for relevant documentation and updated as needed: no
feat: exclude package contents now accepts also star pattern for selecting all npm packages in the package-lock.json
Tested with manually adding * as a pattern to the e2e test for exclude patterns and checking the result.
TODO: Discuss if we want to merge the * pattern excludes with the specific modules excludes and make a test for the decided approach.

[feat] handle star pattern in exclude package contents

---

npm/extensions.bzl

```
rm pnpm-lock.yaml
bazel run @pnpm -- -C $(pwd) i --lockfile-only
bazel build //...
```
This will recompute transitive deps in pnpm-lock.yaml and the build should pass now.

Watch pnpm-lock from the module extension

---

npm/private/repository_label_store.bzl

There have been discussions about ["invalid lockfile entry error"](https://bazelbuild.slack.com/archives/C014RARENH0/p1742987773306169) that this may resolve.
---

fix: bzlmod invalid lockfile entry error

---

npm/private/npm_translate_lock_helpers.bzl

This allows overriding the default to not exclude anything such as:
```
exclude_package_contents = {
"next": [],
}
```
---
- Manual testing; used the [default list](https://github.com/aspect-build/rules_js/pull/2136) on a repo using nextjs which depends on a `/images/` directory.

fix: npm_translate_lock(exclude_package_contents["*"]) should only be a fallback if no explicit package found

---

.bazelrc
.github/workflows/bazel8.bazelrc
.github/workflows/ci.yaml
docs/BUILD.bazel
examples/runfiles/BUILD.bazel
js/private/test/BUILD.bazel
js/private/test/image/asserts.bzl
npm/private/test/BUILD.bazel

chore: add bazel8 ci

---

.github/workflows/ci.yaml

This test seems broken since [upgrade bazel from 7.5 to 7.6.1](https://github.com/aspect-build/rules_js/commit/396b2822ba26fa8f2894c9f56c38e7fd47508a4b) when bzlmod is not enabled.
Since it was not a rules_js change, and this is non-bzlmod, I think we may as well just disable the test?
See failure: https://github.com/aspect-build/rules_js/actions/runs/14412788652/job/40424230118
---

chore: disable e2e/js_image_oci with bazel 7+non-bzlmod

---

npm/private/npm_translate_lock_generate.bzl

This code has not changed in 2y so it's probably always been there and not a recent regression.

refactor: remove unused dep_path var and initialization

---

e2e/pnpm_lockfiles/.bazelignore
e2e/pnpm_lockfiles/MODULE.bazel
e2e/pnpm_lockfiles/base/package.json
e2e/pnpm_lockfiles/lockfile-test.bzl
e2e/pnpm_lockfiles/projects/peers-combo-1/BUILD.bazel
e2e/pnpm_lockfiles/projects/peers-combo-1/package.json
e2e/pnpm_lockfiles/projects/peers-combo-2/BUILD.bazel
e2e/pnpm_lockfiles/projects/peers-combo-2/package.json
e2e/pnpm_lockfiles/v54/pnpm-lock.yaml
e2e/pnpm_lockfiles/v54/snapshots/defs.bzl
e2e/pnpm_lockfiles/v54/snapshots/repositories.bzl
e2e/pnpm_lockfiles/v60/pnpm-lock.yaml
e2e/pnpm_lockfiles/v60/snapshots/defs.bzl
e2e/pnpm_lockfiles/v60/snapshots/repositories.bzl
e2e/pnpm_lockfiles/v61/pnpm-lock.yaml
e2e/pnpm_lockfiles/v61/snapshots/defs.bzl
e2e/pnpm_lockfiles/v61/snapshots/repositories.bzl
e2e/pnpm_lockfiles/v90/pnpm-lock.yaml
e2e/pnpm_lockfiles/v90/snapshots/defs.bzl
e2e/pnpm_lockfiles/v90/snapshots/repositories.bzl

To prepare for changes to align with the v9 lockfiles which handle this better.
---

test: add pnpm lockfile peer dependency tests

---

e2e/pnpm_lockfiles/projects/c/package.json
e2e/pnpm_lockfiles/projects/d/package.json
e2e/pnpm_lockfiles/v54/pnpm-lock.yaml
e2e/pnpm_lockfiles/v54/snapshots/defs.bzl
e2e/pnpm_lockfiles/v60/pnpm-lock.yaml
e2e/pnpm_lockfiles/v60/snapshots/defs.bzl
e2e/pnpm_lockfiles/v61/pnpm-lock.yaml
e2e/pnpm_lockfiles/v61/snapshots/defs.bzl
e2e/pnpm_lockfiles/v90/pnpm-lock.yaml
e2e/pnpm_lockfiles/v90/snapshots/defs.bzl
npm/private/npm_translate_lock_generate.bzl
npm/private/pnpm.bzl

Add tests for the scenario fixed in https://github.com/aspect-build/rules_js/commit/a8c192eed0e553acb7000beee00c60d60a32ed82
Fix the issue when reproduced in pnpm v9+
FWIW I was trying to understand when this pnpm <v9 `id` field is used and no tests failed when removing it. It seems it is declared in pnpm <v9 when `file:` or `link:` dependencies have peer dependencies, the `id` will be the `file:` path without the peer dependency information.
The ugly v9 workaround can be removed in https://github.com/aspect-build/rules_js/pull/2177 but I wanted to add tests before that PR

fix: pnpm v9 peer deps with workspace/link: deps

---

npm/private/npm_translate_lock_generate.bzl
npm/private/pnpm.bzl

To move more of the path/data normalization into the lockfile parsing instead of being spread throughout the repo.
---

refactor: normalize npm file/link: paths at parse time

---

npm/private/npm_import.bzl
npm/private/npm_translate_lock_generate.bzl
npm/private/pnpm.bzl
npm/private/test/parse_pnpm_lock_tests.bzl

The lockfile `id` property is removed with v9. Our only use of it is to resolve `file:` paths in some scenarios however the `resolution.directory` always has the same information available across all lockfile versions.
The `resolution.directory` property also already has the `file:` prefix removed and `resolution.type == "directory"` is a more reliable way of checking for references to directories.
---

refactor: reduce use of pnpm <9 lockfile properties

---

e2e/pnpm_lockfiles/v54/snapshots/defs.bzl
e2e/pnpm_lockfiles/v60/snapshots/defs.bzl
e2e/pnpm_lockfiles/v61/snapshots/defs.bzl
e2e/pnpm_lockfiles/v90/snapshots/defs.bzl
e2e/pnpm_workspace/snapshots/defs.bzl
e2e/pnpm_workspace_rerooted/snapshots/defs.bzl
npm/private/npm_import.bzl
npm/private/npm_package_store.bzl
npm/private/npm_translate_lock_generate.bzl
npm/private/test/snapshots/npm_defs.bzl

Reduce the inspecting of packages and simply assuming all packages (imported and local) have store implementations for the regular + `/ref` + `/pkg` targets.
Create the `npm_local_package_store_internal` wrapper macro instead of expanding the template further.
---

refactor: create /ref and /pkg targets for local package store entries

---

e2e/pnpm_lockfiles/.bazelignore
e2e/pnpm_lockfiles/base/package.json
e2e/pnpm_lockfiles/lockfile-test.bzl
e2e/pnpm_lockfiles/projects/peer-types/BUILD.bazel
e2e/pnpm_lockfiles/projects/peer-types/package.json
e2e/pnpm_lockfiles/v54/pnpm-lock.yaml
e2e/pnpm_lockfiles/v54/snapshots/defs.bzl
e2e/pnpm_lockfiles/v60/pnpm-lock.yaml
e2e/pnpm_lockfiles/v60/snapshots/defs.bzl
e2e/pnpm_lockfiles/v60/snapshots/repositories.bzl
e2e/pnpm_lockfiles/v61/pnpm-lock.yaml
e2e/pnpm_lockfiles/v61/snapshots/defs.bzl
e2e/pnpm_lockfiles/v61/snapshots/repositories.bzl
e2e/pnpm_lockfiles/v90/pnpm-lock.yaml
e2e/pnpm_lockfiles/v90/snapshots/defs.bzl
e2e/pnpm_lockfiles/v90/snapshots/repositories.bzl
npm/private/utils.bzl

A similar test found an issue involving `file:` deps + peers, but I'd like to merge this first.

fix: pnpm v9 url version specifiers without resolved semver

---

npm/private/test/parse_pnpm_lock_tests.bzl

This was part of a lockfile copy+pasted and shouldn't include references to these packages that aren't part of the test.

test: remove invalid pnpm lockfile test data

---

js/private/js_image_layer.bzl
js/private/js_image_layer.mjs
js/private/test/image/BUILD.bazel

Fixes https://github.com/aspect-build/rules_js/issues/2212, https://github.com/aspect-build/rules_js/issues/2215
Fixes js_image_layer to correctly track treeartifact contents.
- Manual testing; please provide instructions so we can reproduce:  Try the repro in https://github.com/aspect-build/rules_js/issues/2212
Unfortunately its not trivial to add test for this case since it requires two step `bazel build` reproduce.

fix: correctly track treeartifact contents

---

js/defs.bzl

Fix https://github.com/aspect-build/rules_js/issues/1899
---

fix: add warnings for deprecated js_run_devserver,js_run_binary include_types,npm_sources attrs

---

js/private/js_run_devserver.mjs

Today the `{sandbox}/_main` subdirectory is removed but leaves behind the (normally empty) `{sandbox}` directory.
Fix `js_run_devserver` temp directory not being fully deleted on exit.
- Manual testing; run a `js_run_devserver` target and kill it via cmd-c

fix(js_run_devserver): delete full sandbox directory on exit

---

js/private/js_run_devserver.bzl
js/private/js_run_devserver.mjs

This removes a `lstat` call on almost all files being synced. Only those within directory artifacts will still be done.
- Manual testing; profile while using `aspect run --watch`

perf: determine js_run_devserver file vs directory in rule

---

js/private/js_run_devserver.mjs

To discourage users from hitting ctrl-c again while a slow delete operation is running.

fix: add console log when removing js_run_devserver sandbox

---

npm/private/npm_translate_lock.bzl

This PR updates the helper message to the user when `ASPECT_RULES_JS_FROZEN_PNPM_LOCK=true` is set. Under `bzlmod` the output label to run is the canonical label, however, only includes one `@` symbol, so if the user copy/pastes the command it fails to run. This PR tries to rectify it by adding the correct number of `@@` symbols prior to the canonical label, eg:
```
bazel run @@aspect_rules_js~~npm~npm//:sync
```
---
- Suggested release notes appear below: no
1. Add `update_pnpm_lock = True` to `e2e/bzlmod/MODULE.bazel`
```
diff --git a/e2e/bzlmod/MODULE.bazel b/e2e/bzlmod/MODULE.bazel …
```

Update helper message when ASPECT_RULES_JS_FROZEN_PNPM_LOCK=true

---

npm/private/pnpm.bzl
npm/private/test/parse_pnpm_lock_tests.bzl

`_parse_lockfile` is expected to return 5 values. If pnpm lockfile is invalid user gets an error about getting 4 instead of 5 expected values and nothing about actual error. Happy path worked ofc, but error path was broken.

fix: correct early exit from _parse_lockfile

---

MODULE.bazel
README.md
e2e/worker/BUILD.bazel
e2e/worker/MODULE.bazel
npm/extensions.bzl

See also https://github.com/aspect-build/rules_py/pull/612
- Suggested release notes appear below: yes/no
`aspect_tools_telemetry` is now used for coarse grained usage tracking.
- Manual testing (`build ...`) produced a telemetry report.

chore: turn on tools_telemetry

---

js/private/js_run_devserver.mjs

Individual message send/receive actions should have specific error handling, not every error should spam stdout.
- Manual testing; please provide instructions so we can reproduce: kill the devserver such as cmd-c

fix: do not output every js_run_devserver watch protocol error

---

MODULE.bazel
js/BUILD.bazel
js/defs.bzl
js/repositories.bzl
npm/defs.bzl
npm/extensions.bzl

chore: update tools_telemetry to 0.2.8

---

js/private/js_run_devserver.mjs

When the process is terminated with something such as cmd-c it is very common the process will not finish sending/receiving the full EXIT message from the CLI so we shouldn't spam stdout.
- Manual testing; please provide instructions so we can reproduce: `aspect run --watch` on a `js_run_devserver` target such as webpack/rspack, cmd-c and ensure no error is outputted

fix(js_run_devserver): do not output run--watch EXIT errors by default

---

npm/private/pnpm_extension.bzl
npm/private/test/pnpm_test.bzl

I keep seeing
`DEBUG: /private/var/tmp/_bazel_alexeagle/9a577879aedc63bdf5030f4fbc898758/external/aspect_rules_js+/npm/extensions.bzl:272:18: NOTE: repo 'pnpm' has multiple versions ["8.6.7", "8.6.7"]; selected 8.6.7`
which is not useful.

fix(pnpm): don't print dumb warning

---

npm/private/pnpm_extension.bzl
npm/private/test/pnpm_test.bzl

Update `pnpm_version_from` to support `package.json` `packageManager` fields with a `+sha512.<hash>` suffix.
For example: 
```json
"packageManager": "pnpm@10.17.0+sha512.fce8a3dd29a4ed2ec566fb53efbb04d8c44a0f05bc6f24a73046910fb9c3ce7afa35a0980500668fa3573345bd644644fa98338fa168235c80f4aa17aa17fbef",
```
---
`pnpm_version_from` now supports `packageManager` fields with a `+sha512.<hash>` suffix.

fix: update `pnpm_version_from` to support `packageManager` fields with `+sha512.<hash>`
